### ISSUE TITLE
Issue: Front matter panel fails to load on posts

### ISSUE THREAD

**Issue by timschps** [estruyf/vscode-front-matter#114]
**Describe the bug**
The Front matter side pannel fails to load on posts 

**To Reproduce**
1. Go to a markdown file in hugo
2. Click on the frontmatter button in the sidebar
3. see emptyness ;)
4. to investigate, I opened the vscode dev tools and when doing the same steps again, I got to see the following errors:
![front matter error](https://user-images.githubusercontent.com/13098307/134622603-a9b2303a-41ee-4f29-a83d-f70235f4a63c.png)
> DevTools failed to load source map: Could not load content for https://file+.vscode-resource.vscode-webview.net/c%3A/Users/timsc/.vscode/extensions/eliostruyf.vscode-front-matter-4.0.0/dist/viewpanel.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED

**Expected behavior**
the front matter side pannel should load 

**Screenshots**

![front matter screenshot](https://user-images.githubusercontent.com/13098307/134622835-0bb48da0-23a6-4fdc-b862-9efd6738ae7d.png)

**Desktop (please complete the following information):**
 - OS: Wind 10

**Additional context**
tried this on regular vscode and the insiders build too
somethimes it works though, very briefly

**Comment by estruyf** [comment]
@timschps would you be able to pass me some details about the used tags and article front matter? You know where to find me if you want to do it privately 😁

**Comment by timschps** [comment]
of course! here you are: 

---
layout: post
title: Running a build in Azure DevOps with Cake and Azure Artifacts
featureImage: ''
thumbnail: /images/cake-artefacts/thumbnail.png
tags:
  - Cake
  - CakeBuild
  - Azure DevOps
  - Azure Artifacts
  - DevRel
  - DevOps
  - Microsoft
date: 2021-05-08T12:39:24.850Z
categories: DevOps
series: build (migration) management
draft: false
slug: running-a-build-in-azure-devops-with-cake-and-azure-artefacts
lastmod: '2021-09-23T19:10:09.673Z'
---
if you want to, we can also do a screensharing session if that's easier for you

**Comment by estruyf** [comment]
I found one small issue where no data was returned, this might have caused it. Would you be able to verify it with the latest beta version: https://marketplace.visualstudio.com/items?itemName=eliostruyf.vscode-front-matter-beta

In order to test, you'll need to uninstall the other extension (all settings will be remained).

**Comment by timschps** [comment]
Just installed the beta, but behavior seems the same...

**Comment by estruyf** [comment]
Ok, let us set up a call :-)

**Comment by timschps** [comment]
@estruyf investigated with me. The categories entry in frontmatter was "only" a string, where an array was expected. So correcting this, fixed my current issue. @estruyf was going to investigate a way to improve this though...

**Comment by estruyf** [comment]
Fix has just been pushed and will be released together with two other minor issues.

**Comment by estruyf** [comment]
Releasing this right now to the main version.
