### ISSUE TITLE
Issue: Adding metadata from Frontmatter extension UI, mouse cursor gets to md file but all of frontmatter gone

### ISSUE THREAD

**Issue by ValerasNarbutas** [estruyf/vscode-front-matter#125]
Frontmatter UI is disapearing on adding metadata

1. Go to the folder with md file in visual studio
2. Right-click on the folder and add a folder to project
3.  Open md file and if in Frontmatter section "Metadata" title and description empty, try type text.
4. UI quickly disappears and only way i found how to open it again restart VS code

**Expected behavior**
UI should be still visible

**Screenshots**
![image](https://user-images.githubusercontent.com/16476453/135600889-d31ba435-2a1b-41b6-9f2c-d7b93c7ff432.png)

**Desktop (please complete the following information):**
 - windows

**Comment by estruyf** [comment]
Hi @ValerasNarbutas would you be able to record a video about the behavior? Seems I'm missing something in your steps in order to reproduce the issue.

**Comment by ValerasNarbutas** [comment]
sure, i just need to find some tool to record it :)

**Comment by ValerasNarbutas** [comment]
> @ValerasNarbutas is this still occurring?

hey, sorry did not responded and yes still an issue, but i have a feeling its due to my pre existing redme's.
what do you use if you want to record a gif? i can do small demo or we can have a teams call.

**Comment by estruyf** [comment]
That is a good idea, but first, could you try out the latest beta to see if that gives you the same result. https://marketplace.visualstudio.com/items?itemName=eliostruyf.vscode-front-matter-beta

**Comment by estruyf** [comment]
Good to know. Thanks for testing it out!
