### ISSUE TITLE
Showcase: SelectedTech

### ISSUE THREAD

**Issue by appieschot** [estruyf/vscode-front-matter#130]
**Title you want to give your site**

SelectedTech

**Link to the site**

https://www.selectedtech.show/

**A nice and clean description**

SelectedTech is a group of four MVP's doing sessions on Microsoft 365 and the AI ecosystem. Build on Hugo and Front Matter and hosted in Azure.

**Comment by estruyf** [comment]
Thanks @appieschot, added it to the showcases: https://beta.frontmatter.codes/showcase - currently only available on the beta docs. When the new release goes out, it will be available on the main docs.
