### ISSUE TITLE
Front Matter: Export all tags and categories to your settings

### ISSUE THREAD

**Issue by Fasani** [estruyf/vscode-front-matter#14]
Hey FYI,

Seems to fail on both my Mac and on my PC. Is their a prerequisite for this feature to work some form of agreed folder structure or is it perhaps just a bug.

I notice the editor opening files but in the end, the popup modal in the bottom right-hand corner hangs about and I have to restart VS Code. After restarting on the mac sometimes the only tags in my settings are from the current open post.

On the pc, it failed completely and after I relaunched it, I was told my editor is now corrupt and I should reinstall.

**Comment by estruyf** [comment]
The PR for the `lastmod` date has just been merged and released in version `1.4.0`.

**Comment by Fasani** [comment]
FYI, I have not been able to identify the issue with this. I will just maintain the list by myself.
