### ISSUE TITLE
SEO Description length is hard-coded to 60 but should be variable ${length}

### ISSUE THREAD

**Issue by Fasani** [estruyf/vscode-front-matter#16]
Hey, I noticed a small issue with version 1.3.0.

SEO Description length is hard-coded to 60 but should be variable ${length}

![screenshot](https://user-images.githubusercontent.com/448410/90990890-3e8cc980-e5a5-11ea-8e58-9eea97ca619a.png)

https://github.com/estruyf/vscode-front-matter/blob/master/src/helpers/SeoHelper.ts#L21

**Comment by estruyf** [comment]
🤦‍♂️ - My mistake. I'll fix it right away. Thanks!!!

**Comment by estruyf** [comment]
Fix is in.
