### ISSUE TITLE
Issue: Preview button not showing when setting is defined

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#166]
I did set `frontMatter.preview.host` to `http://localhost:1313`. Tried restarting whole system, not only VS Code, but no change. Tried in 2 different OSs (Win, Linux - Ubuntu) still no change.

![image](https://user-images.githubusercontent.com/68782815/139573589-9ce0311a-c976-4b32-b74e-7b5d4fc55133.png)

I have also added my content folder by right clicking -> add folder. So the dashboard is appearing correctly. Only this preview option is not.

![image](https://user-images.githubusercontent.com/68782815/139573664-0e1206d9-a755-439b-9ff1-c9bc52c34ab8.png)

_Originally posted by @sid-r-singh in https://github.com/estruyf/vscode-front-matter/discussions/165#discussioncomment-1565018_

**Comment by estruyf** [comment]
Oh, I just noticed, you should first open one of your pages. Once you opened a page, you should see the preview button show up.

**Comment by estruyf** [comment]
Just in case, I have added the button on the panel to its base view. Which means that it will show up once the setting is present. Currently available in the beta version of the extension.

**Comment by sid-r-singh** [comment]
> Oh, I just noticed, you should first open one of your pages. Once you opened a page, you should see the preview button show up.

I tried that already. Let me post a video of what I am seeing.

**Comment by sid-r-singh** [comment]
> Just in case, I have added the button on the panel to its base view. Which means that it will show up once the setting is present. Currently available in the beta version of the extension.

How do I install the beta version ?

**Comment by estruyf** [comment]
You can install it via the following steps: https://beta.frontmatter.codes/docs/getting-started#beta-version

**Comment by estruyf** [comment]
Oh 🤦‍♂️ - it the slug of your article, as there is none defined in your front matter of the content, it will not show the button. I'll implement a logic for this.

**Comment by estruyf** [comment]
Logic has been implemented into the beta.

It will get the slug from the following things:

1. Slug in the front matter
2. The filename, if its not `index.md`
3. The folder name

**Comment by sid-r-singh** [comment]
Wow ! Preview button is appearing now but another small problem cropped up. All my markdown files are within `content/blog` folder. So accordingly, the preview URL should be `http://localhost:1313/blog/slug`. But that is not what I am seeing. The `blog` part is missing in the preview URL. 

![image](https://user-images.githubusercontent.com/68782815/139858084-90b0664f-f2ac-4c61-9f8d-0be468dc54b5.png)


You might wonder whether I have registered my `blog` folder or not. I have done it. The proof I guess lies in my `frontmatter.json`, which is:

```
{
  "$schema": "https://frontmatter.codes/frontmatter.schema.json",
  "frontMatter.framework.id": "hugo",
  "frontMatter.content.publicFolder": "static",
  "frontMatter.content.pageFolders": [
    {
      "title": "blog",
      "path": "c:/Users/SIDHARTH R/Documents/blog-new/content/blog"
    }
  ]
}
```

**Comment by estruyf** [comment]
You will need to specify one last thing, the preview pathname:  https://frontmatter.codes/docs/settings#frontmatter.preview.pathname

So in your case, you'll need to add:

```
{
  "frontMatter.preview.pathName": "'blog/'"
}
```

As all SSGs and sites are different, this pathname setting is used for it. Now that there is the `frontMatter.content.pageFolders` setting, it can be good to extend it with a custom pathname as well.

**Comment by sid-r-singh** [comment]
That worked like a charm 🎉✨🤩. Thanks a lot for helping me out. I'm happy that I contributed to the project in some way.

**Comment by estruyf** [comment]
Thank you @sid-r-singh! Already using the extension and providing feedback is a great contribution! 🙏

**Comment by estruyf** [comment]
FYI: the preview path can now also be defined per content type: https://beta.frontmatter.codes/docs/content-types#preview-path

**Comment by sid-r-singh** [comment]
Thanks a ton for that. This is exactly what I was about to try out today. I was planning to add a `content/snippets` folder apart from the `content/blog` which I have now. In this case the URL needs to be ` http://localhost:1313/snippets/slug`. 

I was thinking whether it will be possible to achieve this or not & here you have already shipped this new feature.

**Comment by estruyf** [comment]
@sid-r-singh this is now released in the main version.
