### ISSUE TITLE
Indent seems wrong

### ISSUE THREAD

**Issue by Fasani** [estruyf/vscode-front-matter#17]
I have several settings to ensure 4 spaces as indent but frontmatter seems to not use them.

```
  "[markdown]": {
    "files.trimTrailingWhitespace": false,
    "editor.tabSize": 4,
    "files.autoSave": "afterDelay"
  },
```
And:
```
  "editor.tabSize": 4,
```

But after setting/updating the date it reverts my tags to 2 spaces:

```
tags:
  - productivity
  - typescript
```

**Comment by estruyf** [comment]
Hi @Fasani, I have added the support for this in `1.5.0`. Thanks for reporting this.

**Comment by Fasani** [comment]
@estruyf your welcome! Have a great day!
