### ISSUE TITLE
Enhancement: Publish this extension to OpenVSX.

### ISSUE THREAD

**Issue by zivbk1** [estruyf/vscode-front-matter#170]
Please publish the extension per the process outlined on this site.
https://github.com/open-vsx/publish-extensions

This will allow me to use this "Front Matter" extension within GitPod.io.

**Comment by estruyf** [comment]
@zivbk1 thanks for the suggestion. Didn't know of its existence 🤓. I added this to GitHub Actions. The BETA version has already been published. The main version will be published with the new release.

At the moment I'm still waiting for the verification of my publisher ID, but that should be an issue for already using the extension. Let me know if it works.

https://open-vsx.org/extension/eliostruyf/vscode-front-matter-beta

**Comment by zivbk1** [comment]
Excellent, thank you for being so quick to respond to this request! I'll test it out in GitPod later this morning.

**Comment by zivbk1** [comment]
It works perfectly, thank you!
