### ISSUE TITLE
Enhancement: Add the ability to sort by date field.

### ISSUE THREAD

**Issue by iveptawebadmin** [estruyf/vscode-front-matter#173]
Currently, you can sort by last modified, but my content doesn't have that field.
The file list shows the 'date' field that I do have in my content, but I can't sort files by it.

![image](https://user-images.githubusercontent.com/30990811/140983804-6fff3c2c-86f8-4a93-9d88-5495de1cc144.png)

**Comment by estruyf** [comment]
This can be linked to #76 as I want to allow open sorting based on anything you define. 

Currently, the last modified sorting is done based on the file stats itself, not from a metadata field in the file,

**Comment by estruyf** [comment]
Support for custom sorting will be added in `5.5.0`. You can already test it out in the latest beta. For this, a new setting has been added. More information about it can be found here: https://beta.frontmatter.codes/docs/settings#frontmatter.content.sorting

```
"frontMatter.content.sorting": [
  {
    "title": "Date (asc)",
    "name": "date",
    "order": "asc",
    "type": "date"
  },
  {
    "title": "Date (desc)",
    "name": "date",
    "order": "desc",
    "type": "date"
  }
]
```

**Comment by bwklein** [comment]
It works as expected in beta.  One preference I would have is to find a way to preserve the last chosen sort method, so that when you go back to the Dashboard, the same sort as last time is applied.

**Comment by estruyf** [comment]
Again, a great suggestion!

**Comment by estruyf** [comment]
@bwklein sorting state is now kept. So when opening the dashboard again, it will use the last used selection.
