### ISSUE TITLE
Enhancement: Exclude content from subfolders?

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#174]
Add the option to exclude sub-directories.

@iveptawebadmin Thanks for opening the discussion. Let us follow it up here as this will become an enhancement to the CMS.

### Discussed in https://github.com/estruyf/vscode-front-matter/discussions/172

<div type='discussions-op-text'>

<sup>Originally posted by **iveptawebadmin** November  9, 2021</sup>
On my Hugo site, many of my pages like `about.md`, `contact.md`, etc. are in the root of my `content` directory.
Then I have subdirectories for subsections of the site like `blog`, `events`, etc. that have pages within them.

I would like the root content pages to be shown in a 'Pages' section, and then news posts to be in a 'News' section and so on.
Is there a way to set this up so that the 'Pages' folder does not look into any of the subdirectories within the `content` directory?

```
"frontMatter.content.pageFolders": [
    {
      "title": "Pages",
      "path": "[[workspace]]/content"
    },
    {
      "title": "News",
      "path": "[[workspace]]/content/news"
    }
  ],
```

Right now the 'Pages' folder has all the files from every subdirectory within `content`.</div>

**Comment by estruyf** [comment]
@iveptawebadmin thanks for asking this. You will be able with version `5.5.0` of the extension to specify an extra `excludeSubdir` property for the `pages` folder.

```
"frontMatter.content.pageFolders": [
    {
      "title": "Pages",
      "path": "[[workspace]]/content",
      "excludeSubdir": true
    },
    {
      "title": "News",
      "path": "[[workspace]]/content/news"
    }
  ],
```

You'll be able to test it out with the latest beta version: https://frontmatter.codes/docs/getting-started#beta-version

**Comment by iveptawebadmin** [comment]
Are you automatically pushing out updates to Open VSX on these updates to 'Beta'?

**Comment by estruyf** [comment]
@iveptawebadmin yes. It is part of the same release flow. If a main (with the upcoming version) or beta version is released, it gets published to both.
