### ISSUE TITLE
Enhancement: have a different icon for the Dashboard than for previewing the article

### ISSUE THREAD

**Issue by LuiseFreese** [estruyf/vscode-front-matter#179]
**Is your feature request related to a problem? Please describe.**
I don't want to hover over the icons to actually see which one is which

**Describe the solution you'd like**
have a different icon for dashboard

**Comment by estruyf** [comment]
Thanks @LuiseFreese for the feedback! I'll see what I can do with the icons.

**Comment by estruyf** [comment]
The dashboard icon will be changed to the `Front Matter` icon:

![image](https://user-images.githubusercontent.com/2900833/142169814-95395932-3332-4892-a2a6-ae014cff4c52.png)

**Comment by estruyf** [comment]
Now available in the `v5.6.0` release
