### ISSUE TITLE
Option to change `lastmod` and `date` attribute names

### ISSUE THREAD

**Issue by adambro** [estruyf/vscode-front-matter#18]
My notes editor (GitJournal) uses `modified` and `created` instead of `lastmod` and `date` attributes respectively.

Would it be possible to set those attribute names in configuration?

**Comment by estruyf** [comment]
I'll add it as an enhancement to the extension. Thinking about two settings which you can define your own property names you want to use.

**Comment by estruyf** [comment]
This functionality has now been added. You can change the field by setting the `frontMatter.taxonomy.dateField` and `frontMatter.taxonomy.modifiedField` config settings. Release `1.7.0` has been published.
