### ISSUE TITLE
Enhancement: add support for different taxonomies

### ISSUE THREAD

**Issue by spf13** [estruyf/vscode-front-matter#181]
I'm new to the project but from my exploration so far it seems that Categories and Tags are hard coded. 
Hugo provides the option to define new taxonomies. It would be great if this was configurable or at the very least, re-nameable. For example, my website, spf13.com uses tags and topics. If I could just alias categories to topics that would address my needs, though other Hugo sites take deeper advantage of the configurable taxonomies.

**Comment by estruyf** [comment]
Thanks @spf13 for the suggestion. Currently what comes close to it is the `choice` field which you can configure for your content type. It does not yet give you the full flexibility you are looking for, so this will make a lot of sense to enhance.

**Comment by estruyf** [comment]
Support for custom taxonomy fields is now supported in the latest `5.6.0` beta version. Documentation has been updated: https://beta.frontmatter.codes/docs/content-types#custom-taxonomy-field

@spf13 feel free to give it a try and let me know if this works for you.

**Comment by estruyf** [comment]
Now available in the `v5.6.0` release
