### ISSUE TITLE
Enhancement: Set the 'default' sort option in frontmatter config.

### ISSUE THREAD

**Issue by zivbk1** [estruyf/vscode-front-matter#182]
**Is your feature request related to a problem? Please describe.**
We can add new sort options for content types and media.  But when I reload the dashboard the last sort I used is not saved and I have to pick the sort option I like each time.

**Describe the solution you'd like**
I would like a config option to set the default sort and content type filter I want to be the 'default' state when the dashboard and media library open. 

**Describe alternatives you've considered**
Manual clicks in the UI allows me to recover the sort and filter I want.

**Additional context**
Maybe add a button to the UI to 'save' the filter and sort as the default to the frontmatter.json config file.

**Comment by estruyf** [comment]
This is a good idea, probably it has to do that GitPod starts each time with a fresh/clean instance. That is why your previous state is forgotten.

**Comment by zivbk1** [comment]
Will this also include storing the default 'Filter' for showing only certain content types on the dashboard by default?

**Comment by estruyf** [comment]
There will be two settings. One for the contents dashboard and one for the media dashboard. You can define the default by defining the ID of the sorting option (the IDs known by the extension or your custom ones).

**Comment by zivbk1** [comment]
I guess I am also asking about the selection of the  content type to show.  For example, I have 'Pages' and 'News', I only want to see News posts sorted by Date (desc), by default.

**Comment by estruyf** [comment]
Ok, so you want the combination with filters.

Think I need more hands to code all these great new features/enhancements/ideas.

What if you could just store the filters/sort as a view/navigation item?

**Comment by zivbk1** [comment]
That's an interesting Idea. I was thinking about it more and it would be cool to save the view state (filter + sort) and be able to recall it easily. Then if you had a set of saved views, you could pick one as the dashboard default for content and media.
Maybe the saved views can be named and you can select one in a 'select' field.  Then next to the 'Clear' button, you have 'Save' and 'Set Default'.

**Comment by estruyf** [comment]
Now available in the `v5.6.0` release
