### ISSUE TITLE
Enhancement: SvelteKit Support

### ISSUE THREAD

**Issue by zivbk1** [estruyf/vscode-front-matter#187]
**Is your feature request related to a problem? Please describe.**
This is more of a placeholder for now as I work through the process of integrating this CMS with SvelteKit content.  I'm really interested in supporting mdsvex content files which should allow me to take advantage of the 'snippets' UI as described by #175 as I could drop Svelte components into the markdown content to expand the functionality of the markdown documents.

**Describe the solution you'd like**
All the things I need for a SvelteKit site work well in this extension.

**Describe alternatives you've considered**
None, this is the only way forward. 😆

**Additional context**
https://kit.svelte.dev/

**Comment by estruyf** [comment]
Thanks, @zivbk1 for the feature/enhancement request. Svelte is still on my list of technologies to learn and explore, but haven't gotten the time for it yet.

As Svelte is becoming popular, it is indeed a good idea to keep this in mind to add support.

**Comment by estruyf** [comment]
@zivbk1 do you have a sample repository that you can share? I was thinking to create an additional repo where various sample project configurations can be shared as that would make testing easier.

If you would like to have SvelteKit support, would you be so kind to add the initial project with some example content here: https://github.com/FrontMatter/project-samples
