### ISSUE TITLE
Issue:  (Beta) Dashboard "settings" button does not show settings.

### ISSUE THREAD

**Issue by jorgeml** [estruyf/vscode-front-matter#191]
**Describe the bug**
When running the Beta version the settings button opens empty setting panes.

**To Reproduce**
1. Run the beta version.
2. Click on 'Dashboard'
3. Click on 'Settings'
4. See empty settings

**Expected behavior**
Expected to see the settings.

**Root cause**
The settings button takes you to a settings page that is filtered by "@ext:eliostruyf.vscode-front-matter" in the text box. Changing the text to "@ext:eliostruyf.vscode-front-matter-beta" fixes this issue.

**Comment by estruyf** [comment]
Thanks! Fixed this for the upcoming release.
