### ISSUE TITLE
Showcase: Maxim Orlov

### ISSUE THREAD

**Issue by Maximization** [estruyf/vscode-front-matter#192]
**Title you want to give your site**

Maxim Orlov

**Link to the site**

https://maximorlov.com/

**A nice and clean description**

Helping Node.js developers write better applications 🚀. Created with Eleventy & Tailwind. Content managed with Front Matter.

@estruyf Thank you for this wonderful project 🙏 🤩

**Comment by zivbk1** [comment]
@Maximization I just checked your site and there is a broken image for me.

![image](https://user-images.githubusercontent.com/6154767/143465472-4cf25ed5-a5aa-48e7-89d6-67fc627c5dff.png)

**Comment by estruyf** [comment]
I've added your website to the showcase page: https://frontmatter.codes/showcase

Thank you very much!

**Comment by Maximization** [comment]
@zivbk1 Thanks for letting me know! That sometimes happens yeah, although not often. Images are hosted on Netlify but resized and cached through Cloudinary API and sometimes either one fails 🤷🏼‍♂️

@estruyf That was a quick turnaround, thanks!
