### ISSUE TITLE
Additional media sorting options.

### ISSUE THREAD

**Issue by zivbk1** [estruyf/vscode-front-matter#198]
@estruyf Off the top of my head would be:
- filename
- size
- date
- title
- alt text

The last two above would need to come from the media DB file if defined.

If there is a way to query/store the following data I could see them as useful also.

-width (px)
-height (px)

_Originally posted by @zivbk1 in https://github.com/estruyf/vscode-front-matter/issues/178#issuecomment-974855407_

**Comment by estruyf** [comment]
- [ ] filename
- [ ] size
- [ ] date
- [ ] title
- [ ] alt text

**Comment by estruyf** [comment]
Media dashboard now supports the following sorting options:

![Screenshot 2022-01-12 at 14 43 06](https://user-images.githubusercontent.com/2900833/149151553-46746af4-f8e6-4a26-86a9-ffe515f0c2c1.png)

**Comment by zivbk1** [comment]
Thank you! Works perfectly!
