### ISSUE TITLE
Enhancement: Search for media by filename.

### ISSUE THREAD

**Issue by zivbk1** [estruyf/vscode-front-matter#199]
Looking for an image in the media folder, I know the filename, but have to sort alpha and click through the sets until I get to the correct page of images, then I can insert it.

I would like a search tool, similar to the content search feature, where I can search by filename, or words in the title (if set in the media DB). 

I could navigate the file tree and find the image there and copy it.  But this wouldn't work if I wanted to see a set of images with a similar filename, to pick the best one for the content (think of stock images).

**Additional context**

Add a search input for media, as we have for content.

![image](https://user-images.githubusercontent.com/6154767/144500191-d80bb92d-abee-43b0-94f7-88a0598495ad.png)

**Comment by estruyf** [comment]
Hi @zivbk1, the first implementation of the search functionality for media files has been completed. Feel free to give it a try in the latest beta.

**Comment by zivbk1** [comment]
> Hi @zivbk1, the first implementation of the search functionality for media files has been completed. Feel free to give it a try in the latest beta.

It works perfectly for me, thank you!!!

**Comment by estruyf** [comment]
Thanks for verifying! Will be released with the upcoming 2022 version. 🎉
