### ISSUE TITLE
Add support for removing tags/categories

### ISSUE THREAD

**Issue by waldekmastykarz** [estruyf/vscode-front-matter#2]
Add support for removing a tag/category, where the particular tag/category is removed from the settings file as well as from all blog posts using it. This functionality would be invaluable for cleaning up tags and categories over time.

**Comment by estruyf** [comment]
Sounds like a great idea!

**Comment by estruyf** [comment]
@waldekmastykarz when using `Front Matter: Remap or remove tag/category in all articles` you should now be able to remap or remove a tag/category.

**Comment by waldekmastykarz** [comment]
Hero!
