### ISSUE TITLE
Feature Request: Make selecting tags easier

### ISSUE THREAD

**Issue by montemartin** [estruyf/vscode-front-matter#20]
Selecting items via the Insert dialog becomes awkward if you have more than a few items. It's especially noticeable in a long list of items once you've narrowed the list down via search. Right now even if only a single item is visible you still have to move down to select it via the spacebar before applying it. If you then want to apply another tag you have to move back to the search bar to find it. The If you fail to do this the dialog closes with no tags applied.

My expectation would be that hitting enter on a highlighted tag would immediately apply that tag, whether it's been selected or not. Space would select that tag, but leave the cursor in the search box. That would allow selecting several tags from a long list without having to move up and down between each search. 

I'm not familiar enough with the extension API, so I'm not even sure this is possible, but it would make my life a LOT easier. Admittedly, my use case is unique because I'm using tags so heavily. I'm using [Foam](https://github.com/foambubble/foam) and several other tools to build a combined knowledge/GTD task management system for myself to replace Evernote. I have ~500 tags to help keep everything tidy. I'm applying between 3 and 6 tags on as many as 50 note files every day, (more right now as I migrate Evernote). All that navigation adds up.

**Comment by ketsapiwiq** [comment]
Hi, first, this extension is very useful thank you!
But I agree, it's quite hard to select the tags.
I would love to be able to easily apply the same tag to multiple files.
Ideally I would be just able to select them in the Explorer, then run a Command to tag them all at the same time!
Auto-complete could also be nice.
Sorry I don't know about the VSCode API, if I have some time I may try giving it a go myself!

**Comment by estruyf** [comment]
I'm afraid that is not possible with the current VS Code APIs, but if you know a way, or have seen a good approach from other extensions, I would be happy to implement it.

If you want, you can always do a PR to get this into the extension.

**Comment by ketsapiwiq** [comment]
Thanks for the answer, I looked it up and it seems to be that issue: https://github.com/microsoft/vscode/issues/3553#issuecomment-613693621
Theia implemented it but not VSCode, too bad...

**Comment by estruyf** [comment]
@ketsapiwiq happy to announce that with version `1.10.0` of the extension, there is now a panel available which allows you to quickly and easily add new tags/categories to your article. I hope you like it! https://github.com/estruyf/vscode-front-matter#frontmatter-panel-introduced-in-1100

![EoQbOR1XEAsqMXN](https://user-images.githubusercontent.com/2900833/100985777-a8c1ec80-354c-11eb-858d-deea12eb9865.gif)

If you have feedback, or ideas feel free to add them to the issue list.

**Comment by ketsapiwiq** [comment]
> @montemartin @ketsapiwiq happy to announce that with version `1.10.0` of the extension, there is now a panel available which allows you to quickly and easily add new tags/categories to your article. I hope you like it! https://github.com/estruyf/vscode-front-matter#frontmatter-panel-introduced-in-1100
> 
> ![EoQbOR1XEAsqMXN](https://user-images.githubusercontent.com/2900833/100985777-a8c1ec80-354c-11eb-858d-deea12eb9865.gif)
> 
> If you have feedback, or ideas feel free to add them to the issue list.

Awesome! Gonna try it right now. Thanks!

**Comment by montemartin** [comment]
This is lovely, exactly what I had in mind. Thank you so much! 

The only thing I'd add is a command to jump directly to tag entry (and back when done) from the editor.

**Comment by estruyf** [comment]
@montemartin thanks! I’ll check if that is possible.
