### ISSUE TITLE
Showcase: Jahir Fiquitiva

### ISSUE THREAD

**Issue by jahirfiquitiva** [estruyf/vscode-front-matter#204]
**Title you want to give your site**

`Jahir Fiquitiva`.

**Link to the site**

[https://jahir.dev](https://jahir.dev)

**A nice and clean description**

Personal website and blog from Jahir Fiquitiva created with NextJS, TypeScript and Styled Components. Blog content managed by Front Matter.

**Comment by estruyf** [comment]
Thanks @jahirfiquitiva! I've added your blog to the showcase list.
