### ISSUE TITLE
Enhancement: notification autohide or timeout

### ISSUE THREAD

**Issue by maliMirkec** [estruyf/vscode-front-matter#205]
I am somewhat annoyed by the notifications.

Is there a possibility to remove the notification when we fix the file without clicking on "Check file" manually? Or maybe suspend the notification after a timeout?

**Comment by estruyf** [comment]
Thanks, @maliMirkec for the suggestion! Unfortunately, VS Code its notifications are there for the user to dismiss. There is currently no programmatic way or timeout that can be set.

I can introduce a new setting that allows you to suppress warning and error messages.

**Comment by maliMirkec** [comment]
Hi, @estruyf, thank you for the quick response.
It sucks that notifications cannot be removed. 
The setting for suppressing warning and error messages sounds like a good idea.

**Comment by estruyf** [comment]
There is now a new setting called `frontMatter.global.notifications`. By default, it is set to show all notifications: `["info", "warning", "error"]`.

**Comment by maliMirkec** [comment]
Thanks, @estruyf!

**Comment by estruyf** [comment]
Will soon be available in BETA, when GitHub Actions start to work again.
