### ISSUE TITLE
Folding front-matter?

### ISSUE THREAD

**Issue by bs** [estruyf/vscode-front-matter#21]
Would you be open to a pull request that adds fold support for front matter in markdown files?

**Comment by estruyf** [comment]
Of course, that would be a great enhancement!

**Comment by bs** [comment]
Right on, I'm almost done with implementing it a separate extension, and then will push here.

The logic to get it to be foldable is quite easy. Harder is auto-folding, which isn't natively supported by VSCode.

**Comment by estruyf** [comment]
Great news! Looking forward to the PR.

**Comment by estruyf** [comment]
@bs did you ever happen to finish this?

**Comment by bs** [comment]
It was left at half-working prototype before I moved physical locations twice. :)

**Comment by estruyf** [comment]
All the best at your new location!

If you still are interested in adding the functionality. Always welcome to do so! 🙏

**Comment by estruyf** [comment]
Released in v2.4.0
