### ISSUE TITLE
Please extend the max description length

### ISSUE THREAD

**Issue by coliff** [estruyf/vscode-front-matter#22]
Currently the plugin warns on descriptions being longer than 140 characters, but many SEO guides suggest a description longer than that... for example the popular https://www.opengraph.xyz/ service recommends length between 155-160 characters.

Could you consider extending the max description length before showing an error to 160 characters? Or if not, maybe include option to set the length yourself or turn that warning off.

**Comment by estruyf** [comment]
Hi @coliff this is actually a great enhancement. I have implemented it with configurable settings: `

### `frontMatter.taxonomy.seoTitleLength`

Specifies the optimal title length for SEO (set to `-1` to turn it off). Default value: `60`.

```json
{
  "frontMatter.taxonomy.seoTitleLength": 60
}
```
### `frontMatter.taxonomy.seoDescriptionLength`

Specifies the optimal description length for SEO (set to `-1` to turn it off). Default value: `160`.

```json
{
  "frontMatter.taxonomy.seoDescriptionLength": 160
}
```

**Comment by estruyf** [comment]
Oh, btw, version `1.8.0` has now been released with this implemented.

**Comment by coliff** [comment]
awesome! thanks for fixing this so quickly. great extension. 👍
