### ISSUE TITLE
Enhancement: Option to Turn-off Slug prefixes

### ISSUE THREAD

**Issue by sureshkumargondi** [estruyf/vscode-front-matter#223]
There should be an option to disable the prefix feature for the slugs. 

As prefix adds the data as default and it doesn't make sense as it will be in the URL structure.

The workaround is I can rename the files as of now after generation though. 

frontMatter.templates.prefix

The simple process as you have for other SEO settings is by adding -1 to disable. 

Thank you
Suresh

**Comment by estruyf** [comment]
Hi @sureshkumargondi, you can change or disable it by using the [frontMatter.templates.prefix
](https://frontmatter.codes/docs/settings#frontmatter.templates.prefix). By default, this is set to `yyyy-MM-dd`, so if you change it to an empty string, it will create new files without the prefix.

**Comment by sureshkumargondi** [comment]
Thank you. 

it will be super easy if there is any toggle button for the UX point of view :) 

And also, it will be useful to create some random number as an ID to add it as a prefix. Like wordpress does. 

For everyone else, this is how to solve this issue. 

https://share.getcloudapp.com/8LupJk8P

**Comment by estruyf** [comment]
Might be a good idea to have prefix `placeholders` like: `id`, `random`, ...

**Comment by sureshkumargondi** [comment]
Id is perfect

**Comment by estruyf** [comment]
Closing the issue as this is supported in the product.
