### ISSUE TITLE
Enhancement: Start local server from extension

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#226]
Add the functionality to start the local server from the extension:

- Known server command or custom commands

**Comment by estruyf** [comment]
![image](https://user-images.githubusercontent.com/2900833/150100511-9090edf1-151f-40be-b89f-f4411c1d1dbc.png)

**Comment by bwklein** [comment]
What directory will this command run in?

**Comment by estruyf** [comment]
It will open a terminal at the given project location. If it needs to run somewhere else, you'll have to update the command. For instance, you should be able to use: `cd ./folder && hugo server -D`.

**Comment by bwklein** [comment]
The button works and launches the local dev based on the "Local server command".

The only issue I see is that it seems to state the command twice and then actually executes it in the terminal.  See the screenshot below.

![image](https://user-images.githubusercontent.com/12104446/150407501-3ec310c6-e7b2-430f-a139-c8bd451ab4b6.png)

**Comment by estruyf** [comment]
It is just a message, not the actual command. I'll change this to only mention it will start the local server.
