### ISSUE TITLE
Enhancement: New setting to specify supported file types

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#227]
New setting for supported file types: adoc, svx, mdsvex

**Comment by estruyf** [comment]
@zivbk1 feel free to test out the new `frontMatter.content.supportedFileTypes` setting. You can use it as follows: `"frontMatter.content.supportedFileTypes": [ "md", "markdown", "mdx", "svx" ]`

**Comment by zivbk1** [comment]
> @zivbk1 feel free to test out the new `frontMatter.content.supportedFileTypes` setting. You can use it as follows: `"frontMatter.content.supportedFileTypes": [ "md", "markdown", "mdx", "svx" ]`

I tried `.svx` and it didn't work for me, it just said something like 'No Markdown to Display', when I changed the extension to `.md` it worked as expected.

**Comment by zivbk1** [comment]
Also, using the .md extension enabled the markdown syntax highlighting to work, with the .svx extension it was like plain text.  I would need to configure that extension to work with some language tools.

**Comment by estruyf** [comment]
My head cannot think so clear due to covid atm. 😝 - I have done some checks and extra enhancements to get it fully supported. Should work right now with the `svx` file extension.

**Comment by bwklein** [comment]
Oh no!!! Please take care of yourself and don't worry about this.  It can wait until you have recovered.

**Comment by wemasoe** [comment]
Take care and best wishes. Get well soon.
