### ISSUE TITLE
Showcase: The Chris and Andre Show

### ISSUE THREAD

**Issue by apowell656** [estruyf/vscode-front-matter#237]
**Title you want to give your site**

The Chris and Andre Show

**Link to the site**

https://chrisandandreshow.com

**A nice and clean description**

We created "The Chris and Andre Show " with Pelican. Managed [in part](https://chrisandandreshow.com/front-matter-headless-cms-visual-studio-code/) with Front Matter.

**Comment by estruyf** [comment]
Thanks @apowell656 your article and website got added to the showcases page.

**Comment by apowell656** [comment]
Thank you! I really appreciate the hard work on this extension.

**Comment by apowell656** [comment]
@estruyf just checked and did not see it on the site.

**Comment by estruyf** [comment]
It is, but the main branch of the docs is waiting for the `v6.0.0` release. You can already view it here: https://beta.frontmatter.codes/showcase

**Comment by apowell656** [comment]
No worries, I would have not thought to look there.
