### ISSUE TITLE
Enhancement: Setting to limit taxonomy options to single selection

### ISSUE THREAD

**Issue by johnfuller** [estruyf/vscode-front-matter#241]
With choices, you have a setting to allow multiple selections. I don't know the intent behind the design of custom taxonomies, but I see this as essentially creating reusable choices fields. Constraining choices to a single selection allows for setting the front matter field to a string or an array of strings. Taxonomies should give you similar control over the resulting field type.

**Comment by estruyf** [comment]
The difference between custom taxonomy fields and choice fields is that taxonomy fields allow you to add new values and allow to store these. So you could start with an empty list, and let it fill up over time.

The limit on the taxonomy fields is a great new enhancement.

**Comment by estruyf** [comment]
You will now be able to specify the `taxonomyLimit` field property on your tags, category, and custom taxonomy fields in order to limit the number of options you can select.

**Comment by johnfuller** [comment]
This is a great enhancement, as a CMS requires user inputs to match rules in the code. As a further enhancement, it may be beneficial to allow setting the type to a string or an array. Because this is a developer concern, it may be good enough to assume that a limit of a single selection would be a string. A markdown front-matter structure has limited data types available, and I believe that enforcing a data type would make this more robust. Target parsers will output data differently based on these types. Thanks!

**Comment by estruyf** [comment]
Enhanced the field to show the limit

![image](https://user-images.githubusercontent.com/2900833/155675173-6f44d4ea-aa34-400a-984f-460befab9a81.png)

**Comment by estruyf** [comment]
@johnfuller the further enhancement on the taxonomy field makes sense indeed, I'm not sure if the right way to output a `string` when the limit is set to `1` is the best option here. Maybe an extra setting is required to specify its type.

**Comment by zivbk1** [comment]
It would break my code if an array data type output a string instead of an array with a single element.
