### ISSUE TITLE
working example of customTaxonomy

### ISSUE THREAD

**Issue by grahampcharles** [estruyf/vscode-front-matter#244]
Can you provide a working example of `customTaxonomy` in use? The example in the docs (https://frontmatter.codes/docs/content-types#custom-taxonomy-field) is not functioning correctly when used verbatim. It appears to link a `taxonomyId` of 'custom taxonomy' with a `name` property of a "taxonomy field" (rather than the `id` property?); there's also no sense of where one should define the custom fields. 

This, for example, does not work:

```
  "frontMatter.taxonomy.customTaxonomy": [
    {
      "title": "category singular",
      "name": "category",
      "type": "taxonomy",
      "taxonomyId": "categorySingular"
    }
  ]
```

I assume I just don't understand the expected syntax for `settings.json`.

Thanks!

**Comment by estruyf** [comment]
An example:

```JSON
{
	"frontMatter.taxonomy.contentTypes": [
    {
      "name": "page",
      "fields": [
        {
          "title": "Custom taxonomy",
          "name": "customTags",
          "type": "taxonomy",
          "taxonomyId": "yourCustomTaxId"
        },
        ...
      ]
    }
  ],
  "frontMatter.taxonomy.customTaxonomy": [
    {
      "id": "yourCustomTaxId",
      "options": [
        "Option 1",
        "Option 2",
        "Option 3"
      ]
    }
  ]
}
```

**Comment by grahampcharles** [comment]
Ah, brilliant -- thanks! I wasn't understanding that the `"frontMatter.taxonomy.contentTypes"` setting was related. 

Thanks again,

Graham
