### ISSUE TITLE
Enhancement:  allow multiple tags/keywords using separator (commas?)

### ISSUE THREAD

**Issue by inteist** [estruyf/vscode-front-matter#246]
**Is your feature request related to a problem? Please describe.**
It is frustrating to not be able to add multiple tags/keywords at once

**Describe the solution you'd like**
using a predefined separator (e.g. comma) or maybe a key combination e.g. CTRL/CMD + Enter to add the tag/keyword

**Comment by estruyf** [comment]
@inteist thanks for opening the issue. This is for sure a great enhancement to the taxonomy field.

**Comment by estruyf** [comment]
@inteist this enhancement will be added in the upcoming v7.1.0 release. Already testable in the latest beta version.
