### ISSUE TITLE
Enhancement: Possibility to setup a public path / front matter path, similiar to Forestry.io

### ISSUE THREAD

**Issue by latorante** [estruyf/vscode-front-matter#251]
**Is your feature request related to a problem? Please describe.**

~~This is not a bug, it's a feature request so nothing needs fixing. What I would love to see is a similar to how forestry.io has an ability to setup `public_path` and `front_matter_path` properties, which allow to `prefix` images with a folder.~~

~~In our current setup, we have an `.MD` file, which has a property of `image: image.jpg`, but the image is actually stored in a sub folder of `images/full/image.jpg`. Without changing a grusome number of files, is there a way to tell FrontMatter to look for images in that folder for the preview in the editor?~~

**Describe the solution you'd like**
~~Having an ability to preset a folder for images to look in.~~

**Describe alternatives you've considered**
~~Changing all the files to have full path.~~

### DISREGARD the above please.

Since I've I use the FrontMatter as editor, and the publishing and other actions are done through the automated actions in Github, I was able to edit `frontMatter.content.publicFolder` to point to the given image folder, and now everything works as expected.

**Thank you very much for amazing extension! Goodbye Forestry.io!**

**Comment by estruyf** [comment]
Thanks, @latorante that is great to hear you found your way! Have fun using Front Matter. Let me know if you miss anything or experience issues.
