### ISSUE TITLE
frontMatter.preview.host Feedback

### ISSUE THREAD

**Issue by grahampcharles** [estruyf/vscode-front-matter#254]
The `frontMatter.preview.host` setting does not work in the manner that it is documented on this page. If I set that value to `http://localhost:1313` as instructed (this is a hugo site), the preview attempts to load `http://localhost:1313/pagename` and gets a 404. Hugo's default permalink is `/:section/:title/`, though, which of course can be overridden in the configuration. Front Matter appears not to take that into account.

I have verified that the page does actually load at `localhost:1313/section/pagename`.

---
#### Document Details

⚠ *Do not edit this section*

* ID: site-preview
* URL: https://frontmatter.codes/docs/site-preview
* Content Source: /content/docs/site-preview.md

**Comment by estruyf** [comment]
Thanks @grahampcharles, that setting is to specify the base host location, if you want to further configure the sections/paths, you can check the following part of the documentation: https://frontmatter.codes/docs/content-types#preview-path

There are actually two other options to specify the path for your content: 

1. Via the content type
2. Via the `frontMatter.preview.pathName` setting

**Comment by estruyf** [comment]
FM is intended to work on any SSG, but it makes sense as well to retrieve settings from the SSG. Why FM doesn't use it yet? Just because you are the first that mentions it, so it would be a good enhancement to FM to be more SSG aware.

**Comment by grahampcharles** [comment]
I see! Thank you for your response.

**Comment by estruyf** [comment]
@grahampcharles we can keep the issue open, as this is a good enhancement for one of the upcoming version

**Comment by estruyf** [comment]
The CMS now has more capabilities to use front matter values in order for previews, and they can be defined on global, page folder, and content type levels.
