### ISSUE TITLE
Enhancement: Add default value support for group fields

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#255]
@estruyf , one word amazing! I have been able to rebuild my troublesome about-section. A couple of things, is it possible to add an image field to fieldGroup and add a default string to a field? 
When I select an image the dialog closes or when I look at the current about-section, the image is not found (that could be because it is not in the media folder).
A workaround for the default string is to create a string with one choice and I tried to use a placeholder without success.

_Originally posted by @apowell656 in https://github.com/estruyf/vscode-front-matter/issues/176#issuecomment-1042862808_

**Comment by bwklein** [comment]
I don't think that defaults work now for any fields in a field group.

In this video I set a default string of "Page Content" to the 'label' field in a field group.  When I add that page section to the array, the label is not pre-populated with the default string.

https://user-images.githubusercontent.com/12104446/154544047-519f8160-0fb2-4d47-acfb-699dac11e65c.mp4

**Comment by estruyf** [comment]
Correct, seems I myself did it wrong 🙈, it is for the group fields only indeed.

**Comment by zivbk1** [comment]
Can those defaults use placeholders like {{now}}?

**Comment by estruyf** [comment]
@zivbk1 took a bit more work, as this is something which is performed on the backend, but now the block fields can also leverage the same placeholder logic as the root fields.

**Comment by zivbk1** [comment]
Thank you!
