### ISSUE TITLE
Enhancement: Allow using preview images on multi-dimensional fields

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#257]
Related to this comment: https://www.eliostruyf.com/generate-open-graph-preview-image-code-front-matter/#comment-5744727905

This is what I thought too, but it seems that it doesn't work with the new subfields, regarding to [https://github.com/estruyf/...](https://disq.us/url?url=https%3A%2F%2Fgithub.com%2Festruyf%2Fvscode-front-matter%2Fissues%2F197%3AcS70Cxu1Tx9eZwwU_jfLV99Us8o&cuid=3638036).

I tried among others (see GitHub issue) following taxonomy:

- fields
...
- title: photograph
- name: photograph
- type: fields
...
- title: Social Media
- name: socialmedia
- type: image
- isPreviewImage: true

But the image doesn't show up in the dashboard.

**Comment by kristofzerbe** [comment]
Here's my (little bit stripped) taxonomy with the social media image in a subfield, which doesn't work as a preview image on the dashboard via ``isPreviewImage``:

```
  "frontMatter.taxonomy.contentTypes": [
    {
      "name": "default",
      "pageBundle": false,
      "fields": [
        {
          "title": "Title",
          "name": "title",
          "type": "string",
          "single": true
        },
        {
          "title": "Photograph",
          "name": "photograph",
          "type": "fields",
          "fields": [
            {
              "title": "File",
              "name": "file",
              "type": "string",
              "single": true
            },
            {
              "title": "Name",
              "name": "name",
              "type": "string",
              "single": true
            },
            {
              "title": "Social Media",
              "name": "socialmedia",
              "type": "image",
              "isPreviewImage": true
            }
          ]    
        },
        {
          "title": "Categories",
          "name": "categories",
          "type": "categories"
        },
        {
          "title": "Tags",
          "name": "tags",
          "type": "tags"
        },
        {
          "title": "Hidden",
          "name": "hidden",
          "type": "draft"
        }        
      ]
    }
  ]

```

**Comment by estruyf** [comment]
Thanks 🙏

**Comment by kristofzerbe** [comment]
The feature works now in the v6.1.1 release of Front matter, but not in the current Beta v7.0.1994549 !?

**Comment by estruyf** [comment]
@kristofzerbe where do you store the images? In a public/static folder?

**Comment by kristofzerbe** [comment]
A static one, defined in my taxonomy as described above, in the field PHOTOGRAPH > SOCIALMEDIA. Here's the Frontmatter of an article:

```
slug: lorem-ipsum
title: "Lorem Ipsum"
date: 2022-03-11 09:28:10
photograph:
  file: my-image.jpg
  name: My Image
  socialmedia: /static/images/social-media/lorem-ipsum.png
```

As I said, worked in the beta and now in release, but not in the beta from yesterday...

**Comment by estruyf** [comment]
🤦‍♂️ found the issue, fix is coming up right now

**Comment by kristofzerbe** [comment]
Works like a charm ... thank you Elio

**Comment by estruyf** [comment]
Thank you for reporting this!
