### ISSUE TITLE
Bug: Tags and Categories field names cannot be renamed

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#261]
I am trying to have a tags field called tag rather than tags

Despite creating new default content type, the Markdown file always ends up writing a field called 'tags'

```
  "frontMatter.taxonomy.contentTypes": [
    {
      "name": "default",
      "previewPath": null,
      "pageBundle": false,
      "fields": [

[[SNIP]]

        {
          "title": "My Tags",
          "name": "tag",
          "type": "tags"
        },
```

Should it be possible to use an alternate field name? Or have more than on tags type field?

_Originally posted by @jmatthewpryor in https://github.com/estruyf/vscode-front-matter/discussions/260_

**Comment by estruyf** [comment]
@jmatthewpryor a fix to support this is added to the latest beta. Feel free to give it a try.

**Comment by jmatthewpryor** [comment]
thanks @estruyf - apologies for the naive question but how do I test the beta?

**Comment by estruyf** [comment]
Beta can be installed by installing this version: https://marketplace.visualstudio.com/items?itemName=eliostruyf.vscode-front-matter-beta

Be sure to uninstall the main version. Nothing is lost during this process, but two extensions with the same ID cannot run at the same time.

**Comment by jmatthewpryor** [comment]
thanks - that seems to have fixed it

**Comment by estruyf** [comment]
Thanks for verifying!
