### ISSUE TITLE
Enhancement: Use WYSIWYG editor component for multi-line text fields.

### ISSUE THREAD

**Issue by zivbk1** [estruyf/vscode-front-matter#263]
Sometimes more complex content needs to be stored in a frontmatter field.
This suggestion would allow the editor to use a WYSIWYG editing tool to create multi-line HTML in a field.

There are lots of editors that might work. 
Ex. https://ourcodeworld.com/articles/read/1065/top-15-best-rich-text-editor-components-wysiwyg-for-reactjs 
Since the space is limited I would recommend something with minimal features or a way to add/remove buttons from the UI as needed.

I would make a new param for string fields `editor: true` or something like that to opt into the additional feature when needed.

**Comment by estruyf** [comment]
What would you like the output of the editor to be? Is it markdown or HTML?

**Comment by zivbk1** [comment]
I was thinking that HTML would be easiest. Since most editors like this already output HTML, and most site generator systems have methods for parsing, processing, injecting HTML. 

There are some that do not have native methods for rendering Markdown to HTML from a variable storing Markdown text.

**Comment by zivbk1** [comment]
@estruyf I've had some further discussions with editors, and so far it has been unanimous for the output of the WYSIWYG editor to be HTML.

**Comment by zivbk1** [comment]
I am getting close to needing this for a site I am about to hand off to a content editor.  Can this be bumped? 
I see it as being very useful for multi-line text content in front matter variables.

Thank you!

**Comment by estruyf** [comment]
I will put this on the next release.

**Comment by bwklein** [comment]
This works perfectly.  Thank you!
