### ISSUE TITLE
Issue: Paths within frontmatter.json should be relative

### ISSUE THREAD

**Issue by andikrueger** [estruyf/vscode-front-matter#264]
**Describe the bug**
Currently the paths in the frontmatter.json file are absolute paths. this cases issues when working in teams and sharing code by using a repository.

**To Reproduce**
1. Add Folder to frontmatter
1. Go to 'frontmatter.json'
1. the absolute path is stored.

**Expected behavior**
The path should be relative to the source directory of the project.

**Screenshots**
![image](https://user-images.githubusercontent.com/15608729/155346910-958e7986-caa4-4fd1-916b-2ff656eb59fa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by estruyf** [comment]
Thanks @andikrueger this must indeed be a bug on Windows and will be taken care of. All paths should be relative, the workspace path should normally get replaced by `[[workspace]]` placeholder.

**Comment by estruyf** [comment]
@andikrueger there was indeed an extra parsing required for the Windows path. This just got fixed in the latest beta version and will be added to the next main release. Thanks again for opening the issue.

**Comment by andikrueger** [comment]
Thank you so much for the quick fix. This will help a lot.
