### ISSUE TITLE
Enhancement: Media Library showing content folders.

### ISSUE THREAD

**Issue by zivbk1** [estruyf/vscode-front-matter#270]
It seems like there is a feature to show 'content' folders that have images in them.

This has been confusing my editors as they are dropping images in the content folder instead of into `static/uploads` where media should go for this project.  `"frontMatter.content.publicFolder": "static/uploads"`

Is there a way to strictly limit the folders that the 'Media' tab can show and at the same time get the paths correct to those assets when inserting them into frontmatter, image snippets, etc.?

If I had a preference, I would only let the 'Media' tab in the Dashboard show the editors the contents of the `static/uploads` folder and not allow them to navigate back up the file tree from there.  If they want to make subfolders in `uploads` and put stuff in there I am okay with that, but anything outside of static is not working well and leading to frustration and extra support.

**Comment by estruyf** [comment]
Further enhancement for page bundles is required. Think it will be best to check based on the content types that support page bundles. If there is no content type that uses it, the media dashboard should only show the files from the public folder setting.

This issue is related to #282

**Comment by estruyf** [comment]
Changes that will be implemented:

**Opening media dashboard**

- When none of the content types is set to use page bundles, it will only show the public folder
- When there is at least one content type that is set to use page bundles, it will show all content folders + public folders.

**On insert image from your content**

- If the current content supports page bundles, it will show all folders + files (content + public)
- If the current content does not support page bundles, it will only show folders and files from the public folder

**Comment by estruyf** [comment]
Also a small change in the folder view, the content folders are highlighted with the letter `c`.

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/2900833/157107187-73d434fe-0cde-42e4-8521-8cb1020f2f7b.png">

**Comment by estruyf** [comment]
This is now available in the latest beta.

**Comment by estruyf** [comment]
@zivbk1 is the latest beta working out for you?

**Comment by bwklein** [comment]
Working with it today and a couple of minor things have come up, but I think that this specific issue is resolved.

**Comment by estruyf** [comment]
Feel free to open another issue(s) for the minor thing that came up.
