### ISSUE TITLE
Enhancement Image size placeholders in media snippet

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#271]
### Discussed in https://github.com/estruyf/vscode-front-matter/discussions/267

<div type='discussions-op-text'>

<sup>Originally posted by **jmatthewpryor** February 24, 2022</sup>
Hi

It seems like it would be useful to have access to the media image width and height as snipper placeholders as described [here](https://frontmatter.codes/docs/markdown#insert-your-own-media-snippet)

Is that possible?

Thanks</div>

**Comment by estruyf** [comment]
Two new snippet placeholders got introduced:

- `{mediaWidth}`
- `{mediaHeight}`

**Comment by jmatthewpryor** [comment]
Amazing !! - thanks - works a treat....
