### ISSUE TITLE
Enhancement: Taxonomy output type setting

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#273]
This is a great enhancement, as a CMS requires user inputs to match rules in the code. As a further enhancement, it may be beneficial to allow setting the type to a string or an array. Because this is a developer concern, it may be good enough to assume that a limit of a single selection would be a string. A markdown front-matter structure has limited data types available, and I believe that enforcing a data type would make this more robust. Target parsers will output data differently based on these types. Thanks!

_Originally posted by @johnfuller in https://github.com/estruyf/vscode-front-matter/issues/241#issuecomment-1046998565_

**Comment by cvburgess** [comment]
Just want add a +1 here.

I tried making a taxonomy because I would love to look at posts by their "post_type" but I cant do this without converting post_type to an array with a limit of one and thats not an easy lift with some automation I am using.

**Comment by estruyf** [comment]
This functionality will be added by the new `singleValueAsString` field property which you can set on the `tags`, `categories`, and `customTaxonomy` fields. 

By default, it will be set to `false`, when set to `true`, when the array has a single value, it will be set as a `string`.

**Comment by estruyf** [comment]
@cvburgess you are able to give it a try in the latest beta version.

Example field configuration:

```json
{
  "title": "tags",
  "name": "tags",
  "type": "tags",
  "taxonomyLimit": 1,
  "singleValueAsString": true
},
{
  "title": "categories",
  "name": "categories",
  "type": "categories",
  "taxonomyLimit": 1,
  "singleValueAsString": true
},
{
  "title": "Custom taxonomy",
  "name": "customTags",
  "type": "taxonomy",
  "taxonomyId": "customTaxonomy",
  "taxonomyLimit": 1,
  "singleValueAsString": true
}
```

**Comment by cvburgess** [comment]
That worked PERFECTLY for me - thank you SO MUCH!

**Comment by estruyf** [comment]
Happy to hear!
