### ISSUE TITLE
Feature request: align file name with slug

### ISSUE THREAD

**Issue by waldekmastykarz** [estruyf/vscode-front-matter#28]
It would be helpful if there was a way to update the file name to match the slug.

This might need to be configurable. Not sure about other SSGs, but in Jekyll, file must be named like `yyyy-mm-dd-slug.markdown`

**Comment by estruyf** [comment]
@waldekmastykarz this will be supported in the upcoming release. You will have to enable this, by setting the `frontMatter.taxonomy.alignFilename` setting to `true`.

**Comment by estruyf** [comment]
Closing as this is now released in `v2.2.0`.
