### ISSUE TITLE
Enhancement: Sort by published date in Dashboard

### ISSUE THREAD

**Issue by jmatthewpryor** [estruyf/vscode-front-matter#283]
Hi,

It seems the dashboard only sorts by last modified date, I would find it far more helpful to sort by published date (taking the new `isPublishDate` feature into consideration)

Thanks

**Comment by estruyf** [comment]
Totally makes sense 🤓

**Comment by estruyf** [comment]
In the new beta the published date sorting options will be available

![image](https://user-images.githubusercontent.com/2900833/157192078-8e92b720-0f89-4ebb-909a-4ba00e59a27d.png)

**Comment by jmatthewpryor** [comment]
awesome - thanks
