### ISSUE TITLE
Issue: WYSIWYG controls not shown in MDX files

### ISSUE THREAD

**Issue by rolule** [estruyf/vscode-front-matter#284]
**Describe the bug**
The WYSIWYG controls work as expected when editing a .md file, but seem to be missing when editing a .mdx file.

**To Reproduce**
1. Open a .md file. The controls should be visible on the top right of vscode
3. Open a .mdx file. The controls are not visible

**Expected behavior**
The controls should be visible in both .md and .mdx files

**Screenshots**
The controls are visible in .md files:
![Screen Shot 2022-03-08 at 15 02 19](https://user-images.githubusercontent.com/73437576/157253054-b754a659-bc69-4648-b6a8-0aee293ff6af.png)

But not in .mdx files:
![Screen Shot 2022-03-08 at 15 02 22](https://user-images.githubusercontent.com/73437576/157253090-d0ce57d0-8584-4a37-ba15-46f6104e8b91.png)

**Desktop (please complete the following information):**
 - OS: MacOS 12.2 (21D49)
 - VScode: 1.65.0
 - Front Matter (v7.0.1951494-beta BETA)

**Additional context**
`frontMatter.content.wysiwyg` is set to `true`

**Comment by estruyf** [comment]
Thanks again @rolule, the extension was not yet validated the recently added `frontMatter.content.supportedFileTypes` setting. The fix has been included, now they will show up for all types defined in the setting.

**Comment by rolule** [comment]
Perfect, thanks again !
