### ISSUE TITLE
Enhancement: Set the 'time zone' for the dates added to the frontmatter through the UI.

### ISSUE THREAD

**Issue by bwklein** [estruyf/vscode-front-matter#285]
The date/time written to file does not match the selected date/time in the FM UI datepicker.

![image](https://user-images.githubusercontent.com/12104446/157570639-529ab264-8f4a-4b0f-87ad-d9aaf05db8b5.png)

I didn't see anything in the docs about how to set this up for a consistent time/date in the front matter.

**Comment by estruyf** [comment]
The date picker uses the UTC time, but shows it in the local time. Dates get stored by default in UTC - ISO format. That is why they do not include the timezone.

If you use the `frontMatter.taxonomy.dateFormat` setting, you can match the dates.

![Screenshot 2022-03-10 at 09 29 44](https://user-images.githubusercontent.com/2900833/157620286-3ef6b19a-830b-410f-bf7d-320b508cc653.png)

**Comment by estruyf** [comment]
@bwklein can this be closed? Or is there still something required?

**Comment by bwklein** [comment]
I haven't tried it yet. I didn't see an obvious way to make the date/time
the UI writes to the front matter date field in central US timezone.  I'm
sure it works right, but I don't know for sure.

**Comment by estruyf** [comment]
No problem, I'll leave it open for you to check 🤓

**Comment by bwklein** [comment]
Works as expected.
