### ISSUE TITLE
Enhancement: refresh search button

### ISSUE THREAD

**Issue by grahampcharles** [estruyf/vscode-front-matter#286]
If I search posts from the FM Dashboard with a filter (by tag, for example), and then edit some of those posts to remove the tag, the search results don't change -- there's no "Refresh" or re-search button. Even clearing and re-setting the search criteria doesn't refresh the search ; the stale results are still returned. Only closing and re-opening the dashboard triggers the search function to update.

A `Refresh` button on the search results (next to `(X) Clear`, maybe?) could trigger a re-catalog.

**Comment by estruyf** [comment]
Have been trying to reproduce the issue in order to see how we can improve things, but for now, all seems to work fine on my end.

https://user-images.githubusercontent.com/2900833/157909433-e03d3eca-b10d-4053-b1ab-cef686b65008.mp4

What and where does it behave differently on your end? If you are able, feel free to share a video on where and how it goes wrong in your environment.

**Comment by grahampcharles** [comment]
That's interesting. I did the same thing, essentially, and it did not refresh the filtered search. Only closing and opening the dashboard entirely did the trick:

https://user-images.githubusercontent.com/3606679/158256326-0ea3deeb-67a6-4772-9261-301300d31188.mp4

I have v.6.1.1 of FM, which VSCode reports is the latest available.

Hope that helps sort it out!

**Comment by grahampcharles** [comment]
Sure, I can do that. For now, though, I noticed that opening the dashboard gives me this error 129 times (which I think is every content page):

```["ERROR" - 12:03:35]  Front Matter: File error: ...\index.md - Cannot read property 'find' of undefined```

So I imagine that's what's at the root of it. Hang on, I'm going to clone your repo and see if I can find exactly where the error occurs.

**Comment by estruyf** [comment]
@grahampcharles just did a couple of test runs on a Windows machine, but haven't been able to reproduce the error you are seeing.

If you would be able to share a sample project or your project, feel free to do so. You can also send me an email to elio@struyfconsulting.be if there are things you do not want to share in this thread.

**Comment by grahampcharles** [comment]
Sure, I'm happy to share it semi-privately. I'll add you to my repo for it. It's not particularly sensitive stuff -- just schoolwork.

I am now getting the `file error` on every open and the FM tools aren't working at all since I uninstalled and reinstalled. Maybe I should open a new issue for that?

**Comment by grahampcharles** [comment]
I figured out the `file error` thing. I had added this setting:

```json
  "frontMatter.taxonomy.contentTypes": [
    {
      "name": "default",
      "pageBundle": true
    }
  ]
```

...but didn't add any fields to it. Whoops. (Probably worth catching, so it doesn't disable the whole plugin, but still, clearly user error.)

**Comment by estruyf** [comment]
Oh, that is great news! Will see what we can do to still make use of the default fields if this happens.

**Comment by grahampcharles** [comment]
Okay, now that I've cleared up the `file error` thing that was my fault, here's a recording of the same process from above (`test tag 1`, etc.) showing that the search list is not getting refreshed for me

https://user-images.githubusercontent.com/3606679/158656580-e5602246-4ac7-4e36-86e4-fde6116d0129.mp4

.

**Comment by estruyf** [comment]
It seems the saved file listener from VS Code isn't triggered. Another request, would you be able to test the `beta` version (https://marketplace.visualstudio.com/items?itemName=eliostruyf.vscode-front-matter-beta)? First uninstall the main version from VS Code, next install the beta version. Nothing will get lost in the process.

In the beta, there are already a couple of issues fixed, like the metadata flow.

**Comment by estruyf** [comment]
Wrapping up the tasks for the 7.0.0 release, and this one is still open. @grahampcharles have you had the change to check it out?

**Comment by grahampcharles** [comment]
Sorry to take so long. That's done it! You want me to record a screencap?

**Comment by grahampcharles** [comment]
Oh, incidentally, the plaintext search seems to have some problems. I think I'll start that as a new issue, though -- I'm not sure it's related to this.

**Comment by estruyf** [comment]
Thanks, @grahampcharles for confirming!
