### ISSUE TITLE
Enhancement: add parent directory to recently modified files list

### ISSUE THREAD

**Issue by grahampcharles** [estruyf/vscode-front-matter#287]
In hugo (and maybe other SSGs?), content is kept in an `index.md` file within a titled bundle directory. Therefore, the "Recently Modified" list on the FM toolbar generally lists only multiple instances of `index.md`. Adding the immediate parent directory would give more context.

![Screenshot 2022-03-10 11 29 00](https://user-images.githubusercontent.com/3606679/157740150-6e771a02-0630-407c-bbd3-c627dc2ef5a4.png)

**Comment by estruyf** [comment]
When using `index.md` files, the parent folder will now be shown.
