### ISSUE TITLE
plaintext search not returning expected results

### ISSUE THREAD

**Issue by grahampcharles** [estruyf/vscode-front-matter#292]
A search for "wallaby" returns posts that do not contain that word. 

Adding the word "wallaby" to a post (after the search) does not update the search.

Pressing the "refresh" button clears the search box, but then re-entering the search term still doesn't return the newly-edited post.

https://user-images.githubusercontent.com/3606679/159109863-5321ea94-d202-47cc-8950-a9c98a2b2d60.mp4

**Comment by estruyf** [comment]
The wallaby must be very good at hiding 🤓

Internally we only use the title, slug, description from the article in order to search for content and it might be that the three documents have a low score. A full text will probably help and will require some enhancements to the extension.

**Comment by estruyf** [comment]
Lowering the threshold for the fuzzy search. That should fix these results from showing up. Opened another issue for including the full-text search capability.
