### ISSUE TITLE
Enhancement: Allow full text search

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#294]
#292 - allow a full-text search to go through the contents of the pages/articles.

To offer this functionality, the search index needs to be maintained in the file storage, meaning that the search logic needs to move from the webview to the extension worker context.

**Comment by bwklein** [comment]
I'm already generating json files for full text search on my sites.  Maybe if you specify a json data structure that we can put in the root of our project, we can point your search function to it if we want to add full text search to the extension UI.

**Comment by estruyf** [comment]
@bwklein which library do you use for the search experience on the website?

**Comment by estruyf** [comment]
@bwklein it might start to create conflicts. Internally the extension was already using Fuse.js, but was not indexing the `body` content. In the upcoming beta, this will be changed.

**Comment by estruyf** [comment]
@grahampcharles this is enabled in the latest beta

**Comment by bwklein** [comment]
@estruyf this is great!  It will have an advantage of not requiring any specific setup for search to work.  Plus, just knowing that a word is in a file is enough, I don't really need to have a link to the specific section of the document like I do with my more advanced search index/results.
