### ISSUE TITLE
Issue: type of "default" value for fields is "string".

### ISSUE THREAD

**Issue by landure** [estruyf/vscode-front-matter#306]
**To Reproduce**

Create a custom default content type:

```
	"frontMatter.taxonomy.contentTypes": [
			{
			  "name": "default",
			  "pageBundle": false,
			  "fields": [
				{
				  "title": "Title",
				  "name": "title",
				  "type": "string",
				  "single": true,
				},
				{
				  "title": "Is in draft",
				  "name": "draft",
				  "type": "draft",
				  "default": true
				}
			  ]
			}
		  ],
```

In the problems section of visual studio code, this message appear:

> Incorrect type. Expected "string".

The message concern the default value of field "draft", which is a boolean.

Furthermore, If the default value is set to `"false"`, it is equivalent to `true` in Front Matter. An empty default (`""`) is equivalent to `false`.

**Expected behavior**

There should be no issue with a default value with a type other than string.

And if string type is the only possibility, A default set to `"false"` should set the field to `false`.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10 Impish Indri

**Comment by estruyf** [comment]
Thanks @landure for opening this issue. The `default` field was indeed set to `string` in the schema. This just got fixed and another code fix as well. It will be available in version 7.1.0 and the latest beta.
