### ISSUE TITLE
Enhancement: allow for string content fields with multiple values

### ISSUE THREAD

**Issue by landure** [estruyf/vscode-front-matter#307]
I'm using Hugo site generator. Hugo allow for [Aliases](https://gohugo.io/content-management/urls/#aliases).

The definition of the aliases front matter field should be:

```
				{
					"title": "Aliases",
					"name": "aliases",
					"type": "string",
					"single": true,
					"multiple": true
				},
```

But the "multiple" option is not valid for string fields.

The solution is to allow for "multiple" option to work for string fields, as it does for images.

**Comment by estruyf** [comment]
It might be better to have an option for a free text choice field.

**Comment by estruyf** [comment]
It made more sense to have a new `list` field.

![Screenshot 2022-06-02 at 09 16 46](https://user-images.githubusercontent.com/2900833/171574902-4b2bb571-f1c4-478c-9479-91b976671a32.png)

![Screenshot 2022-06-02 at 09 16 59](https://user-images.githubusercontent.com/2900833/171574920-e972b1eb-ede0-4bb6-bbe6-32d6ce1dc351.png)

Available for testing in the latest beta
