### ISSUE TITLE
Enhancement: Allow for file or media field type

### ISSUE THREAD

**Issue by landure** [estruyf/vscode-front-matter#308]
I'm using Hugo as a content generator. Hugo allow for `audio` and `videos` front matter fields for populating the corresponding opengraph values (see [Configure Open Graph](https://gohugo.io/templates/internal#configure-open-graph)).

According to Hugo documentation:

> audio and videos are URL arrays like images for the audio and video metadata tags, respectively.

The `audio` and `videos` fields definition should be:

```
				// an array of paths to audio files related to the page;
				// used by the opengraph internal template to populate og:audio.
				{
					"title": "Audio",
					"name": "audio",
					"type": "file",
					"multiple": true
				},
				// an array of paths to videos files related to the page;
				// used by the opengraph internal template to populate og:video.
				{
					"title": "Videos",
					"name": "v					ideos",
					"type": "file",
					"multiple": true
				}
```

with the file type working like the image type for any file type.

Additionally, a mime type or file extension filter for selected files should be possible:

```
				{
					"title": "Audio",
					"name": "audio",
					"type": "file",
					"multiple": true,
					allowed-mime-type: [ "audio/*", "audio/mp3" ],
					allowed-extensions: [ "mp3", "m4a", "wav", "flac" ],
				},
```

**Comment by estruyf** [comment]
Thank you @landure for the suggestion! It would definitely make sense to get this enhancement.

**Comment by estruyf** [comment]
The first implementation of the new `File` field is completed.

Sample field configuration:

```json
{
  "title": "Attachments",
  "name": "attachments",
  "type": "file",
  "multiple": true,
  "fileExtensions": ["pdf", "mp4", "wav"]
}
```

![Screenshot 2022-04-20 at 10 43 31](https://user-images.githubusercontent.com/2900833/164195919-f3496316-e54e-4569-88f3-9638bda49a27.png)
![Screenshot 2022-04-20 at 10 43 18](https://user-images.githubusercontent.com/2900833/164195925-1c6469ec-9838-4723-96a5-679447eeeb54.png)
![Screenshot 2022-04-20 at 10 37 04](https://user-images.githubusercontent.com/2900833/164195928-3358e9d4-401f-4ddf-b914-72c6076197d7.png)
![Screenshot 2022-04-20 at 10 36 58](https://user-images.githubusercontent.com/2900833/164195929-209c56c3-12f3-4718-af76-772df2278c48.png)

The new field type will be available for testing in the latest beta version.
