### ISSUE TITLE
Feedback: Missing the Snippet tool icon.

### ISSUE THREAD

**Issue by zivbk1** [estruyf/vscode-front-matter#309]
I have a Snippets section of the Dashboard and can see/edit them in that panel.  But, I am missing the tool to insert them into the document while editing markdown.  It is also not in the triple dots dropdown for additional editor tools.

![image](https://user-images.githubusercontent.com/6154767/161447067-8ed718ce-a42d-4cec-94c8-fdd073a74e54.png)

Using: Front Matter BETA  v7.1.2082782

---
#### Document Details

⚠ *Do not edit this section*

* ID: snippets/index
* URL: https://beta.frontmatter.codes/docs/snippets/index
* Content Source: /content/docs/snippets/index.md

**Comment by estruyf** [comment]
Related to #240 - which is now fixed.
