### ISSUE TITLE
Issue: Counts on dashboard tabs are wrong and/or invisible until clicked

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#315]
**Describe the bug**
The count of "published" and "draft" seems to be the count of total posts. Also, it would be nice to see the count without the tab being active:

**To Reproduce**
1. Clone git@github.com:davidsneighbour/kollitsch.de.git
1. start VSCode and see the counts. 

**Expected behavior**

I would expect the tabs to show something like

"All Articles (33)" "Published (30)" "Drafts (3)"

**Screenshots**

![20220408-20:48:07-Selection-001](https://user-images.githubusercontent.com/83281/162448964-0c2af7b6-67d9-4fc3-a67a-d85d866d9f73.png)

![20220408-20:48:18-Selection-001](https://user-images.githubusercontent.com/83281/162448993-fd28ad95-05a0-4e8e-90f6-cf05d26f1481.png)

![20220408-20:48:35-Selection-001](https://user-images.githubusercontent.com/83281/162449006-70cd935c-843c-4f21-9c70-6216cdd771e5.png)

**VSCode:**
- Version: 1.66.1
- Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
- Date: 2022-04-06T14:51:26.173Z
- Electron: 17.2.0
- Chromium: 98.0.4758.109
- Node.js: 16.13.0
- V8: 9.8.177.11-electron.0
- OS: Linux x64 5.13.0-39-generic
- Front Matter: v7.1.1

**Comment by estruyf** [comment]
Indeed, currently, they are shown on the fly. As in the latest version, there were some dashboard optimizations done for loading the content faster. It might be doable to have this kind of functionality.

**Comment by estruyf** [comment]
The fix is released in version 7.1.2
