### ISSUE TITLE
Issue: Background activity fails if dashboard is closed on startup

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#316]
**Describe the bug**

I am unable to properly phrase the issue, so please feel free to ask for details if I am missing anything. I have Front Matter set to open the dashboard automatically on startup of VSCode. Sometimes I close the dashboard tab before it is fully loaded. In that case, a bunch of errors pop up a little bit after that (see screenshots). I think whatever activity is running, should be "abandoned" when the tab is closed or issues with the "webview being disposed" should be caught. I do not have any additional or verbose debugging enabled, so I should not see the issues. It feels like there is some async stuff going on to populate the dashboard, that might be easily abandoned on tab-closure. 

**To Reproduce**
1. Set dashboard to "open on startup"
2. start VSCode and close the dashboard tab right after it pops up
3. wait for it...

**Expected behavior**
No errors, catching the problem behind the scenes.

**Screenshots**

![20220408-20:57:33-Selection-001](https://user-images.githubusercontent.com/83281/162451837-198805c4-1617-4d70-9d4d-03eab2dfc939.png)

![20220408-20:59:03-Selection-001](https://user-images.githubusercontent.com/83281/162451888-c915b628-22c5-44f3-9da6-d4faea8bef62.png)

![20220408-20:59:25-Selection-001](https://user-images.githubusercontent.com/83281/162451904-f3e2b378-cd90-4d35-8bac-c8aa490c86dc.png)

**VSCode:**
- Version: 1.66.1
- Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
- Date: 2022-04-06T14:51:26.173Z
- Electron: 17.2.0
- Chromium: 98.0.4758.109
- Node.js: 16.13.0
- V8: 9.8.177.11-electron.0
- OS: Linux x64 5.13.0-39-generic
- Front Matter: v7.1.1

**Comment by estruyf** [comment]
That is indeed the background processing of the content. Will suppress these error notifications, as they are not required. Thanks!
