### ISSUE TITLE
Feedback: Formatting of paths/dates

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#319]
I wonder if there is more to the formatting options of the preview path:

```
frontMatter.preview.pathName
Specify the path you want to add after the host and before your slug. This can be used for instance to include the year/month like: yyyy/MM. The date will be generated based on the article its date field value.

Type: string
Default: ""
Important: As the value will be formatted with the article's date, it will try to convert all characters you enter. In case you wan to skip some characters or all of them, you need to wrap that part between two single quotes. Example: "'blog/'yyyy/MM" will result in: blog/2021/08.
```

The documentation shows only `yyyy/MM`. I would expect, that there is more to this. Maybe adding a link to the formatting options of dates that are available? How to format "2022/january" or "22/jan" for instance?

**Comment by estruyf** [comment]
Internally we use `date-fns` and all the following formatting options are available: https://date-fns.org/v1.30.1/docs/format

**Comment by estruyf** [comment]
Closing this issue as the question was answered.
