### ISSUE TITLE
Issue: Typo in docs

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#320]
On https://frontmatter.codes/docs/settings#frontmatter.preview.pathname
there is a typo, but the link to "edit on github" ends up on an unrelated page, so I don't know where to fix the typo ;)

```
frontMatter.preview.pathName
Specify the path you want to add after the host and before your slug. This can be used for instance to include the year/month like: yyyy/MM. The date will be generated based on the article its date field value.

Type: string
Default: ""
Important: As the value will be formatted with the article's date, it will try to convert all characters you enter. In case you wan to skip some characters or all of them, you need to wrap that part between two single quotes. Example: "'blog/'yyyy/MM" will result in: blog/2021/08.
```

In the second group, there is "In case you wan to skip" which should be "want to skip".

**Comment by estruyf** [comment]
Thanks @davidsneighbour I updated it. Where do you end up? Because, `https://github.com/FrontMatter/web-documentation-nextjs/edit/main/content/docs/settings.md` is the correct one.

**Comment by davidsneighbour** [comment]
https://github.com/FrontMatter/web-documentation-nextjs/edit/main/content/docs/settings.md is indeed where I end up. But I couldn't locate `frontMatter.preview.pathName` on that page. Turns out that was a usability issue on Github, It thinks I am searching for regexpes and doesn't look for "real" dots. Next time I know :)
