### ISSUE TITLE
"Error: Cannot find module 'react'"??

### ISSUE THREAD

**Issue by ruifortes** [estruyf/vscode-front-matter#329]
Sorry if I missed something obvious but...
Aren't all installs supposed to be automagical?
I'm getting a "Error: Cannot find module 'react'" after starting the server.
Do I need to npm install anything??
Thanks

**Comment by ruifortes** [comment]
I do get a warning from "npx next info" though

 ```
   Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 17.3.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.5
      react: 18.1.0
      react-dom: 18.1.0

warn  - Latest canary version not detected, detected: "12.1.5", newest: "12.1.6-canary.17".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

**Comment by estruyf** [comment]
What do you mean with aren't all installs supposed to be automagical?

In case you want to use Front Matter with your site, you will have to run all installs manually. Front Matter will do the content management part.

**Comment by ruifortes** [comment]
I'm not used to these frameworks so I at least figured out I better start by learning them.
Maybe make that more explicit in the readme and you may avoid ignorant posts like these! ;-)
Thanks

**Comment by estruyf** [comment]
Closing as this was a question. 

Thanks, @ruifortes for the suggestion on enhancing the documentation.
