### ISSUE TITLE
Enhancement: Use data files for choices

### ISSUE THREAD

**Issue by barrymieny** [estruyf/vscode-front-matter#332]
**Is your feature request related to a problem? Please describe.**
Data files can be set up to store things like author information (e.g. name, slug, url), but if you want to use this information in your front matter as a dropdown you have to set up this data in duplicate as `choices` to a `choice` field in `frontMatter.taxonomy.contentTypes`.

**Describe the solution you'd like**
Add an option to use data files as the source for `choice` fields with key/value mapping.

**Describe alternatives you've considered**
I don't see any alternatives other than setting it up in duplicate or just manually entering the details instead of a choice dropdown.

**Additional context**
For example set up an authors data file:
```json
"frontMatter.data.files": [
  {
    "id": "authors",
    "title": "Authors",
    "file": "[[workspace]]/data/authors.json",
    "fileType": "json",
    "labelField": "name",
    "schema": {
      "title": "Authors",
      "type": "object",
      "required": [
        "slug",
        "name"
      ],
      "properties": {
        "slug": {
          "type": "string",
          "title": "Slug"
        },
        "name": {
          "type": "string",
          "title": "Name"
        },
        "url": {
          "type": "string",
          "title": "URL"
        }
      }
    }
  }
]
```

In the field configuration to store an ID/slug but display a name:
```json
{
  "title": "Author",
  "name": "author-slug",
  "type": "choice",
  "dataSource": "authors",
  "key": "slug",
  "value": "name"
}
```

Or for displaying/storing only a string:
```json
{
  "title": "Author",
  "name": "author-slug",
  "type": "choice",
  "dataSource": "authors",
  "value": "name"
}
```

**Comment by estruyf** [comment]
Thanks, @barrymieny for the suggestion of how we can improve this feature. 

Never used it in such a way, so need some more information. What I currently thinking of is to create it as a new field type, where, like you suggested, provide the data source. As that would make it easier to document and use.

**Example data**

```json
[
  {
    "name": "Person 1",
    "profile": "https://..."
  },
  {
    "name": "Person 2",
    "profile": "https://..."
  }
]
```

**Example field**

```json
{
  "title": "Author",
  "name": "author-slug",
  "type": "datasource",
  "dataSource": "authors",
  "key": "slug",
  "value": "name"
}
```

**Questions**

- What do you want to see in the UI? The value you define in the `value` property (`Person 1`, `Person 2`)?
- When selecting the data, do you want to have the whole author object added to the front matter or only the name?
	- I already know the answer, but it is more to consider the type of data structures we need to support.

**Comment by estruyf** [comment]
Hi @barrymieny, 

I've got good news for you. The new `dataFile` field just got implemented.

The field definition for your content type looks as follows:

```JSON
{
  "title": "Author",
  "name": "author",
  "type": "dataFile",
  // ID of the data file
  "dataFileId": "authors",
  // Data key that will be set in the front matter
  "dataFileKey": "slug",
  // Optional: the value defines the field that will be used for the label in the dropdown, if not present, the dataFileKey will be used instead
  "dataFileValue": "name",
  "multiple": true
}
```

**Comment by estruyf** [comment]
Available in the latest beta.

**Comment by barrymieny** [comment]
That's great news! I'll check it out ASAP.

**Comment by estruyf** [comment]
It will be release in v7.3.0
