### ISSUE TITLE
Issue: [7.2.0] Dashboard doesn't start.

### ISSUE THREAD

**Issue by ReLater** [estruyf/vscode-front-matter#334]
**Describe the bug**
- I can't say if it was the VS Code update to 1.67.0 (I just think so) or FM update to 7.2.0. As far as I remember 7.2.0 worked with VS Code 1.66.2.
- When I try to open the dashboard via button (above, on right side) I just see an endlessly rotating loading spinner.
- When I downgrade FM extension to 7.1.2 everything works like expected.
- Error is:

```
Uncaught Errors (1)
Cannot read properties of undefined (reading 'map')
```

**Desktop (please complete the following information):**

```
--VS Code version infos--
Version: 1.67.0 (user setup)
Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
Date: 2022-05-04T12:06:02.889Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044
```

**Additional context**
- It's a Hugo project with many mounts to external modules and internal folders.
- The Vs Code Workspace contains 2 folders. 1: just images. 2: the Hugo project inclusive frontmatter.json and .frontmatter folder.

**Comment by ReLater** [comment]
That's what I see in Developer Tools:

```
mainThreadExtensionService.ts:79 [[object Object]]Cannot read properties of undefined (reading 'map')
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79

mainThreadExtensionService.ts:80 TypeError: Cannot read properties of undefined (reading 'map')
 at w.<anonymous> (c:\Users\root\.vscode\extensions\eliostruyf.vscode-front-matter-7.2.0\dist\extension.js:1:21921)
 at w.t (c:\Users\root\.vscode\extensions\eliostruyf.vscode-front-matter-7.2.0\dist\vendors.99e176cb3d1be4575ec1.js:2:783733)
 at w.emit (node:events:390:28)
 at w._readdirError (c:\Users\root\.vscode\extensions\eliostruyf.vscode-front-matter-7.2.0\dist\vendors.99e176cb3d1be4575ec1.js:2:686029)
 at c:\Users\root\.vscode\extensions\eliostruyf.vscode-front-matter-7.2.0\dist\vendors.99e176cb3d1be4575ec1.js:2:685326
 at FSReqCallback.oncomplete (node:fs:188:23)
 
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
```

**Comment by estruyf** [comment]
Thank you for reporting the issue.

Tried to mimic your workspace to see if I can reproduce it.

<img width="411" alt="image" src="https://user-images.githubusercontent.com/2900833/167304736-851a89af-895c-40af-9d02-2be0ed85b236.png">

Unfortuntatly, I haven't been able yet to get the same error.

Do you use the `frontMatter.content.supportedFileTypes` setting?

Would you mind testing out the beta version to see if it is also happening there as well?

**Comment by ReLater** [comment]
> Do you use the frontMatter.content.supportedFileTypes setting?

No.

I will test these days in a "standard" hugo environment.

Mine is a bit weird concerning mounts and imports. A playground.

Hugo itself is in a subfolder `site` of the repo.

I've switched it to `public`. https://github.com/GHSVS-de/hugo_docsghsvs

Other frontmatter relevant configs are in files prefixed with `VSC-`. Don't try to run `hugo`. It will crash.

**Please don't waste your time with it if it's not worth it.**

> Would you mind testing out the beta version to see if it is also happening there as well?

If you have time to tell me how to do that. I use the feature "Install Another Version..." of VSC that only provides stable releases.

**Comment by estruyf** [comment]
Details of how you can install the beta can be found here: https://frontmatter.codes/docs/getting-started#beta-version

**Comment by estruyf** [comment]
Just tested out your project, and it loads fine. Think it might have to do with some Windows path parsing, that should have been fixed in the beta. If not, let me know. The beta does not use minified JS, so it should give a better clue of where it fails.

**Comment by ReLater** [comment]
- Uninstalled FM.
- Installed eliostruyf.vscode-front-matter-beta-7.3.2290413
- No success.
- Developper Tools: Log before opening FM dashboard: https://github.com/GHSVS-de/hugo_docsghsvs/blob/main/before-dashboard_vscode-app-1652037239176.log
- Developper Tools: Log after opening FM dashboard: https://github.com/GHSVS-de/hugo_docsghsvs/blob/main/after-dashboard_vscode-app-1652037239176.log

Concerning errors "Unable to resolve filesystem provider with relative file path" in both files.
- I have tested already "pageFolders" with relative path. Then these ERRs are gone but still no success.

More tested:
- Downgraded VSC to 1.66.2.
- No success.

**Comment by ReLater** [comment]
Please wait until I come back.

- I started a new standard Hugo project. It works.
- Now I will copy over files, configurations etc. step-by-step.

Let's see what happens when where...

**Comment by ReLater** [comment]
I have found the cause.

In the repo there is a folder [buildBefore](https://github.com/GHSVS-de/hugo_docsghsvs/tree/main/buildBefore).

There I run composer.

It creates a folders/file `buildBefore\vendor\bin\yaml-lint` that I can't upload to the online repo with "Github Desktop" (blocked by WIN ("unreadable" or so)). That's the reason why the forked repo worked for you without issues.

I can't find any configuration setting that protects FM to scan that folder.

After deleting the file `yaml-lint` FM works.

My last test environment:
- Front Matter BETA v7.3.2290413
- VS Code 1.67.0

I remain with a "Good to know!" ;-)

**Comment by estruyf** [comment]
That is indeed good to know, but let me try to find a solution for it so that these cases don't happen again.

**Comment by estruyf** [comment]
Feel free to give the latest beta a try. Hope that this resolves the issue on your end.
