### ISSUE TITLE
Enhancement: Allow multiple frontmatter types

### ISSUE THREAD

**Issue by SG60** [estruyf/vscode-front-matter#337]
**Is your feature request related to a problem? Please describe.**
My Hugo website currently uses TOML frontmatter for new content; however, I also have a large amount of YAML. Hugo copes with this fine, so it would be great for Frontmatter to support that as well if possible!

**Describe the solution you'd like**
To allow multiple frontmatter types, perhaps distinguished by the characters used as guards. E.g. `---` seems standard for YAML, while `+++` is standard for TOML. Could the frontmatterType option be changed to an array of accepted frontmatter types?

**Comment by estruyf** [comment]
Thank you @SG60 for the suggestion!

**Comment by estruyf** [comment]
Changed the logic of Front Matter to automatically detect this per file, no need for setting changes.

The original setting is still used for the creation of new files.

**Comment by SG60** [comment]
Just tried it, all seems to be working!! Thanks!

**Comment by estruyf** [comment]
Thanks for testing it out @SG60.

**Comment by estruyf** [comment]
It will be release in v7.3.0
