### ISSUE TITLE
Setting lastmod modifies creation

### ISSUE THREAD

**Issue by Yajo** [estruyf/vscode-front-matter#34]
See:

https://user-images.githubusercontent.com/973709/114273457-00e49000-9a12-11eb-9882-68316c32c246.mp4

It should have modified the `modified` field only.

**Comment by c-antin** [comment]
additionally it changes the date format

**Comment by estruyf** [comment]
This seems to be related to the `js-yaml` dependency which transforms it to UTC. Did a change internally to store the date as a string. This will make YAML not parse it.

This will not automatically work for you. The best is to wrap the dates with single quotes: `'`

**Comment by estruyf** [comment]
Fix will be released with `v1.17.1`
