### ISSUE TITLE
Enhancement: When initializing a site, populate frontmatter.json with default content type

### ISSUE THREAD

**Issue by anakinsleftleg** [estruyf/vscode-front-matter#353]
**Is your feature request related to a problem? Please describe.**
There is no way to see the default content type settings when starting fresh (not having created a new content type) because it must exist only in the background code, and does not exist in the `frontmatter.json` file. It only appears once a new different (or modified default) content type is made.

**Describe the solution you'd like**
When the `frontmatter.json` file gets initialized and created, it should be populated with all the default settings for that project/site already there, including but not limited to the default content type. This allows users to see how to structure future content types and also what all the default options are for the program.

**Describe alternatives you've considered**
None, only that one has to create a new content type to see the default appear.

**Additional context**
--

**Comment by estruyf** [comment]
Thanks @anakinsleftleg for the suggestion!
