### ISSUE TITLE
Issue: labelField parameter is not documented or in the json schema for use in Field Groups.

### ISSUE THREAD

**Issue by bwklein** [estruyf/vscode-front-matter#356]
**Describe the bug**
Add 'labelField' to the frontmatter.json file for a Field Group, the warning "Property labelField is not allowed" is shown for that param. Searching the documentation for 'labelField' doesn't return any results and it is not discussed in the Block or Field Groups section.

https://frontmatter.codes/docs/content-creation/fields#block  
https://frontmatter.codes/docs/settings#frontmatter.taxonomy.fieldgroups

This parameter is useful for indicating in a field group which value to show in the list of blocks in a Field Group data structure.

**Comment by bwklein** [comment]
As a side note, it does work to use that parameter.

**Comment by estruyf** [comment]
@bwklein was indeed not present in the JSON schema. Will be added.
