### ISSUE TITLE
Option to change front matter description field?

### ISSUE THREAD

**Issue by flikteoh** [estruyf/vscode-front-matter#36]
Like the `"frontMatter.taxonomy.modifiedField": "updated"`

Is it possible to have options to change the description field like `"frontMatter.taxonomy.seoDescriptionField": "summary"` ?

**Comment by estruyf** [comment]
Sure,that can be achieved

**Comment by estruyf** [comment]
This has been released in version `1.17.0`. Feel free to give it a try.

**Comment by flikteoh** [comment]
Thank you so much for your quick response and implementation! That helped a lot in our workflow!
