### ISSUE TITLE
Enhancement: Conditional UI for Metadata

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#362]
### Discussed in https://github.com/estruyf/vscode-front-matter/discussions/357

<div type='discussions-op-text'>

<sup>Originally posted by **bwklein** June 13, 2022</sup>
I would like to show only the fields that are required based on some boolean or choice field selections.

For example, I have a 'Heading' partial that can either have text based title or a logo based heading.
I would like to allow the editor to choose if they want a text or logo based heading with a boolean choice like "Logo Heading?"

If `true`, then I would like to show them a Logo choice field and a string field for 'Classes' that they can pass in to style the logo.  Essentially showing them a Field Group for the 'Logo' settings.

If `false`, then I would like to show the fieldgroup for the "Text" heading data.</div>

## Solution

```json
{
	"title": "Logo Heading",
	"name": "logoHeading",
	"type": "string",
	"when": {
		"property": "heading",
		"operator": "eq",
		"value": true
	}
}
```

**Comment by michaeltlombardi** [comment]
Love this idea. Another use case for conditional metadata is when it applies only to section pages (for example, `_index.md` files for a hugo site).

**Comment by estruyf** [comment]
Good news @michaeltlombardi and @bwklein, this is now supported in the latest beta version.

### Sample

```json
{
  "title": "Description",
  "name": "description",
  "type": "string",
  "when": {
    "fieldRef": "title",
    "operator": "contains",
    "value": "website",
    "caseSensitive": false
  }
}
```

> **Important**: By default it is case sensitive, if you want, you can turn this off by setting the `caseSensitive` property to `false`.

### Operator

The following operators are supported:

| type | value |
| --- | --- |
| equals | `eq` |
| notEquals | `neq` |
| contains | `contains` |
| notContains | `notContains` |
| startsWith | `startsWith` |
| endsWith | `endsWith` |
| greaterThan | `gt` |
| greaterThanOrEqual | `gte` |
| lessThan | `lt` |
| lessThanOrEqual | `lte` |
