### ISSUE TITLE
Issue: Front Matter is not loading in VS Code and showing an "Unexpected end of JSON input"

### ISSUE THREAD

**Issue by thedaviddias** [estruyf/vscode-front-matter#375]
**Describe the bug**

I previously installed Front Matter and activated it with my Github account. Everything worked fine.

I then discovered that one of my extensions made too many requests to the Github API and seems I got blocked from being able to sign in / sync my editor with Github (for how long, I don't know).

Now, seems that Front Matter is not loading in my VS Code. I uninstalled multiple times, the extension and VS Code, but seems I can't get it to work again.

**To Reproduce**
1. Click on the Front Matter logo in the sidebar
2. The panel is loading continiously  

**Expected behavior**
I should see the content of the Front Matter extension

**Screenshots**
![CleanShot 2022-07-22 at 17 05 40](https://user-images.githubusercontent.com/237229/180568546-7a598a3c-0c99-40e6-9ca3-403ccba1d24d.jpg)

**Desktop (please complete the following information):**

**Additional context**

**Comment by thedaviddias** [comment]
The issue related to auto-sync not working was due to an error in my `settings.json` file. Even after being fixed. Front Matter is still indefinitely loading.

**Comment by thedaviddias** [comment]
The issue was actually coming from a bad formating in my `frontmatter.json`. Once fixed, Front Matter loaded correctly! 🙌

**Comment by estruyf** [comment]
Thanks @thedaviddias for the updates! Glad you found what was causing it.
