### ISSUE TITLE
Enhancement: Post processing script on content type

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#376]
Add the ability to reference a script that will be executed after content creation happened.

**Comment by davidsneighbour** [comment]
I would add a complete "hook system" where we can reference scripts on several activities/events, but post-creation comes to mind first.

**Comment by davidsneighbour** [comment]
I have a specific use case in mind: I have a content type that is basically a youtube video. When creating that post I would want to retrieve that videos thumbnail as a preview image to be saved next to the markdown file of the content. Currently I am doing that via creating the content > manual action with frontmatter button. 

I would think that is what this feature might be about?

**Comment by estruyf** [comment]
@davidsneighbour correct, that is my use case as well.

The postscript functionality is now available in the latest beta.

Here is what you need to do:

**Create a script**

The postscript functionality uses the content scripts from the `frontMatter.custom.scripts` settings. All you have to do is add a new `id` property to the script.

```json
{
  "frontMatter.custom.scripts": [
    {
      "id": "generate-social-image",
      "title": "Generate social image",
      "script": "./scripts/social-img.js",
    }
}
```

> **Info**: If you want to hide the script/action from the UI, you can add a property `hidden` and set it to `true`.

**Define the postscript in the content type**

The content type has a new property called: `postScript`, which requires the `id` of the script to execute.
