### ISSUE TITLE
Issue: Delete content option is not available in Contents line view

### ISSUE THREAD

**Issue by anakinsleftleg** [estruyf/vscode-front-matter#383]
**Describe the bug**
In the Contents dashboard, when view is as lines, there is no option to delete a post. You must be in card view in order to see the option.

**To Reproduce**
1. Go to Dashboard
2. Click on line view mode
3. Notice there is no option to delete an entry

**Expected behavior**
There should be right click or icon or both option to delete, since a left click will view the entry.

**Screenshots**
![image](https://user-images.githubusercontent.com/77084568/183779811-99d72e10-c5f4-4299-971b-a5afbae7074a.png)

![image](https://user-images.githubusercontent.com/77084568/183779865-540b050b-421b-4205-9cac-0657c7d93c6c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
- VScode 1.7.0
 - Front Matter v 8.0.1

**Comment by estruyf** [comment]
The list view needs to get some more love. 🙂 - The same actions from the card view must also be added to this.

Thanks @anakinsleftleg for the suggestion!

**Comment by estruyf** [comment]
Working on it...

![Xnapper-2022-08-11-20 51 33](https://user-images.githubusercontent.com/2900833/184216945-22d4883b-84f0-45a4-8ff0-1d2b36f0ff5f.png)

**Comment by estruyf** [comment]
Will be available to test out in the beta

**Comment by anakinsleftleg** [comment]
you work quick man
