### ISSUE TITLE
Enhancement: Quick/bookmark/favorite files option

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#387]
From time to time, I see myself needing to update that one file. Instead of searching for the file, it would be nice to have a way to bookmark/favorite a file so it can be accessed quickly from a different file view.

**Comment by estruyf** [comment]
I started a new extension for this kind of functionality as I also require this in other projects. The extension is called: Squarl bookmarks and can be found here: https://marketplace.visualstudio.com/items?itemName=eliostruyf.vscode-squarl

For Front Matter, it will still be beneficial to have a similar experience that shows up on the content dashboard.

**Comment by dylan-k** [comment]
Squarl looks to be a lot more powerful than the simpler [favorites extension](https://marketplace.visualstudio.com/items?itemName=howardzuo.vscode-favorites) I have been using. Especially with the addition of project-links, I'm switching to this! Thanks for making it.

**Comment by estruyf** [comment]
Closed this as we now have the content pinning functionality: https://frontmatter.codes/docs/dashboard/content-view#content-pinning
