### ISSUE TITLE
Enhancement: Stop Server Command

### ISSUE THREAD

**Issue by apowell656** [estruyf/vscode-front-matter#388]
**Is your feature request related to a problem? Please describe.**
There is a "Start server" command, but a "Stop server" command does not exist. 

**Describe the solution you'd like**
A button under "Start server" to stop the server. Although you can use the terminal and the server stops when you end VSCode, it would be nice to have a visual option. This would also be a big plus for the non-technical user(s).

**Comment by estruyf** [comment]
Great suggestion @apowell656 - this feature will be added in the upcoming release.

![Xnapper-2022-09-02-13 40 58](https://user-images.githubusercontent.com/2900833/188132065-8d54643e-24ec-494f-83f9-19d9cc5488ab.png)
