### ISSUE TITLE
Examples for custom.scripts

### ISSUE THREAD

**Issue by xunhs** [estruyf/vscode-front-matter#39]
Hi, thanks for your great extension for Hugo user. I have a little problem when design a custom action. Would you please provide some codes / examples for `frontMatter.custom.scripts`? 
Thanks very much~

**Comment by estruyf** [comment]
On the readme, there was a sample provided. I have updated this one, hope it makes it a bit clearer. The script itself can also be found here: https://github.com/estruyf/vscode-front-matter/blob/master/sample/script-sample.js

Let me know if you have any other questions about it.

**Comment by xunhs** [comment]
> On the readme, there was a sample provided. I have updated this one, hope it makes it a bit clearer. The script itself can also be found here: https://github.com/estruyf/vscode-front-matter/blob/master/sample/script-sample.js
> 
> Let me know if you have any other questions about it.

Thank you very much for your kindly reply~ That is a great toturial example for a beginer like me. Actually, I want to active an action which can add a shortcode by only an action click on the panel. Anyway, I am going to read your source codes and have a try to achieve it. 

Best Regards

**Comment by estruyf** [comment]
Going to close this issue. Feel free to let me know if more details are required.

Also wrote an article about how I use it to generate my blog its preview images: https://www.eliostruyf.com/generate-open-graph-preview-image-code-front-matter/
