### ISSUE TITLE
Issue: Errors in configuration file prevent extension loading

### ISSUE THREAD

**Issue by skamansam** [estruyf/vscode-front-matter#390]
**Describe the bug**
If there are any validation errors in the `frontmatter.json` file, the extension fails to load anything but the sidebar icon and panel. When the panel is opened, there is a visible indeterminate progress bar but nothing else happens. Attempts to show the dashboard cause VSCode to throw an error that the `frontmatter.dashboard` command doesn't exist.

**To Reproduce**
1. Open `frontmatter.json`
2. add a comma at the end of a dictionary or invalidate the json is some other way.
3. reload the window

**Expected behavior**
1. A typical VSCode error notification is displayed upon extension load that says the `frontmatter.json` file has errors, and clicking on that notification will display the errors, as is typical for error reporting. 
2. The extension will load properly and all the default values are loaded instead.
3. When going to the frontmatter dashboard, a notice is given that there a `fontmatter.json` file exists and that there are problems with it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux (Fedora 36)
 - Browser n/a
 - Version: all

**Comment by estruyf** [comment]
@skamansam, thanks for opening an issue on this. We'll check what we can do to make the experience better.

**Comment by estruyf** [comment]
@skamansam, a new parser will be used to prevent these issues. Also, when it might happen again, it shows a message there is an issue with the `frontmatter.json` config and loads the default configuration.
