### ISSUE TITLE
Enhancement: Description/Help for metadata field definitions

### ISSUE THREAD

**Issue by michaeltlombardi** [estruyf/vscode-front-matter#391]
**Is your feature request related to a problem? Please describe.**

I'm working on a default `frontmatter.json` definition for users of my Hugo theme to be able to leverage because Front Matter seems like a tool that is _absolutely_ going to help me give those users a more delightful experience. While trying to configure the metadata fields, I noticed that they don't have something like an optional `description` key, which would help keep users from having to look things up.

**Describe the solution you'd like**

Ideally, there would be an optional `description` or `help` key (not fussed about the name) for metadata fields which would:

- Display when a user hovers over that field name in the UI
- Display in fainter text beside or below the field name

I think from a UX perspective, show-on-hover by default with an option to always display would be really stellar. If no description is provided, you get no hover text nor a description after the field name.

**Describe alternatives you've considered**

I could extend the `title` key for the metadata fields to include this information, but that could be distracting or confusing, I think.

**Additional context**

N/A

**Comment by estruyf** [comment]
What do you think about this:

![image](https://user-images.githubusercontent.com/2900833/190664186-5632ca61-abd0-42cb-a9b7-662023ca84f1.png)

First implementation and it is coupled to the #369 feature.

**Usage**

Add the `description` property to the field configuration, and you should see the message appear in the panel.

**Comment by michaeltlombardi** [comment]
That looks great to me! That definitely makes it easier to provide context as close to the work as possible for users. 😊

**Comment by michaeltlombardi** [comment]
Confirmed and it looks good! I tried using newlines which didn't work, but I think that's probably fine.

![Screenshot of the updated view with per-field descriptions, the markdown file, and the frontmatter json](https://user-images.githubusercontent.com/14190564/190673417-5464fde0-6b7c-40ab-b9bd-7fd694b5c857.png)

**Comment by estruyf** [comment]
It just a simpel description line that is supported, but this gave me an idea. 

Would a divider and header (which can include a description) make sense? That way, you can split the fields  in sections.
