### ISSUE TITLE
Add support for generating slugs without noise words

### ISSUE THREAD

**Issue by waldekmastykarz** [estruyf/vscode-front-matter#4]
It would be helpful if the extension could generate a SEO-optimized slug based on the post's title, but automatically converting it to lower-case and removing all noise words such as `a`, `the`, `in`, `for`, etc. I have a [SharePoint JS-based solution](https://blog.mastykarz.nl/generating-seo-slugs-cross-site-published-content-sharepoint-2013/) that does this including a Dutch and English dictionary of noise words, which we could use as reference.

**Comment by estruyf** [comment]
Again, that would make it an amazing addition!

**Comment by estruyf** [comment]
@waldekmastykarz this has now been implemented. Used your stop words list + some additional logic to remove special characters and punctuations. Version `0.0.8` should be available soon.

**Comment by waldekmastykarz** [comment]
You're a hero! 👏
