### ISSUE TITLE
Enhancement: Enable paging on the content overview page

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#401]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Implement the same paging behavior from the media view on the content overview.

**Additional context**

![image](https://user-images.githubusercontent.com/2900833/189085997-9726900d-c325-4d8a-9bd5-2d63f0539532.png)

**Comment by michaeltlombardi** [comment]
This is phenomenal, I see it working in the beta and it's a big usability improvement for me!

**Comment by estruyf** [comment]
For me as well, it's stupid I haven't been thinking about it earlier. 🤓
