### ISSUE TITLE
Enhancement: Enable custom sorting on integer fields

### ISSUE THREAD

**Issue by michaeltlombardi** [estruyf/vscode-front-matter#402]
**Is your feature request related to a problem? Please describe.**

I'm trying to define a custom sorting option for my content, which logically follows weights by folder and subfolder. Unfortunately, the only valid options for `type` in `frontMatter.content.sorting` seem to be `date` and `string`. This definition is invalid:

**Describe the solution you'd like**

I would like for this definition to be valid and order my content by weight from lowest integer value to highest:

```json
"frontMatter.content.sorting": [
  {
    "id": "byWeight",
    "title": "By Weight",
    "name": "weight",
    "order": "asc",
    "type": "integer"
  }
]
```

**Describe alternatives you've considered**

I can't think of any, since Front Matter isn't aware of how my static site generator will eventually order my content.

**Additional context**

N/A

**Comment by estruyf** [comment]
Support has been added. Type should be `number` as this is how it was already internally implemented for other fields.

**Comment by michaeltlombardi** [comment]
Good news and bad news - good news, the sorting works! Bad news, the configuration file still thinks `number` is an invalid value.

![screenshot of the settings file for a custom sorter hovering on the "number" value for type, displaying a warning that lists the valid values as "string" and "date"](https://user-images.githubusercontent.com/14190564/189499205-cdd0054a-1cf5-44fc-915e-2c8f564fc565.png)

**Comment by estruyf** [comment]
That's great news. 

The JSON schema has not yet been updated, that happens when an update to the docs happens. This is why you still see the warning.

**Comment by michaeltlombardi** [comment]
Okay, gotcha! That makes sense to me. Thank you so much for this improvement!

**Comment by estruyf** [comment]
A new schema version was released on the beta docs, which should fix the schema issue.

**Comment by michaeltlombardi** [comment]
I updated to the latest version (according to VS Code, anyway - `v8.1.303582`) but no luck.

![Screenshot showing the failed validation continues in latest preview](https://user-images.githubusercontent.com/14190564/189669587-57d01f63-cbda-4f9d-ae60-12522139bb98.png)

**Comment by estruyf** [comment]
To what URL is the schema set in your `frontmatter.json` file? Probably `https://frontmatter.codes/frontmatter.schema.json`? The beta schema is available on: `https://beta.frontmatter.codes/frontmatter.schema.json`, in some cases it might even get cached.

**Comment by michaeltlombardi** [comment]
Yup! That fixed it for me! 😊 I'll leave it on beta since I'm almost certainly going to stay out on the edge like this 😅
