### ISSUE TITLE
Enhancement: Add Support for Taxonomy.View in View Modes

### ISSUE THREAD

**Issue by jordanlambrecht** [estruyf/vscode-front-matter#408]
The following two items are not in the documentation and do not lint correctly: 
```
 "frontMatter.global.modes": [
    {
      "id": "minimal",
      "features": [
        "dashboard.taxonomy.view",
        "dashboard.taxonomy.manage"
      ]
    }
  ],
```

They seem to work, though. 

Documentation page: https://frontmatter.codes/docs/panel#view-modes

**Comment by estruyf** [comment]
Good catch @jordanlambrecht. The schema and docs seem to be missing the `dashboard.taxonomy.view` feature flag.

`dashboard.taxonomy.manage` does not exist at the moment - do you see the need for this? If so, we'll track this in another issue.

**Comment by estruyf** [comment]
Schema and docs got updated.

**Comment by jordanlambrecht** [comment]
> Good catch @jordanlambrecht. The schema and docs seem to be missing the `dashboard.taxonomy.view` feature flag.
> 
> `dashboard.taxonomy.manage` does not exist at the moment - do you see the need for this? If so, we'll track this in another issue.

Not necessarily, but users may be confused because the option exists for the Snippets dashboard. I would almost say it's unnecessary for the Snippets settings because why would you _not_ want to have the ability to edit something via the dashboard?

Thanks for making such a great product =]

**Comment by estruyf** [comment]
@jordanlambrecht thanks for the feedback 💚. For feedback, it was added because in an authoring mode, it can be that you just want to use what is defined. For taxonomy, authors might want to remap. That is why the manage type is only available for snippets and not for the taxonomy view.

It can be added to disable the `actions` from the taxonomy view.
