### ISSUE TITLE
Enhancement: Add "Frontmatter Dashboard" and "Create New Content" to the default Other Actions

### ISSUE THREAD

**Issue by jordanlambrecht** [estruyf/vscode-front-matter#414]
Right now, the userflow is a bit clunky to get to the frontmatter dashboard and to create new content if a .mdx file is focused. You have to close the .mdx file and open one that is a different filetype, like a .js, to access the dashboard quickly or to make a new post. It would speed things up significantly if a user could do that from the Other Actions pane by default.

**Comment by estruyf** [comment]
This can be added, but the dashboard can also be opened from the `FM` actions at the panel's top or the editor title.

![Screenshot 2022-09-19 at 09 34 26](https://user-images.githubusercontent.com/2900833/190969863-fe6c0c45-5807-4402-8e7b-f48c5d7310ce.png)
