### ISSUE TITLE
Issue: Slug field is not auto-populated on .mdx creation

### ISSUE THREAD

**Issue by jordanlambrecht** [estruyf/vscode-front-matter#415]
I have a post type that contains a slug field. When creating a new post, it does not automatically populate that field (such as a Date field does). Additionally, updating the content of that field does not automatically rename the file unless you hit the "Optimize Slug" button.

**Comment by estruyf** [comment]
In the upcoming release, a new `slug` field can be used from the panel, and with the `{slug}` placeholder, it can be automatically populated.

#349 should cover this issue.

**Comment by estruyf** [comment]
Documentation from the Slug field can be found here: https://frontmatter.codes/docs/content-creation/fields#slug

Example:

```json
{
  "title": "Slug",
  "name": "slug",
  "type": "slug",
  "default": "{{slug}}"
},
```
