### ISSUE TITLE
Enhancement: Add hyperlink option to editor toolbar

### ISSUE THREAD

**Issue by jordanlambrecht** [estruyf/vscode-front-matter#417]
It would be great to have the ability to insert hyperlinks in the editor toolbar. Right now, that seems to be the only 'typical' thing that most gfm editors have that is missing:

<img width="278" alt="Screen Shot 2022-09-18 at 13 47 10" src="https://user-images.githubusercontent.com/54866853/190923502-397bd716-1b84-4f8f-83ed-954a34a29b55.png">

**Comment by estruyf** [comment]
![image](https://user-images.githubusercontent.com/2900833/190980241-2ee9423e-e481-44d2-a037-2f1be0f8d7f0.png)

The strikethrough action got moved to the options menu, and the hyperlink action got added.

**Comment by jordanlambrecht** [comment]
> ![image](https://user-images.githubusercontent.com/2900833/190980241-2ee9423e-e481-44d2-a037-2f1be0f8d7f0.png)
> 
> The strikethrough action got moved to the options menu, and the hyperlink action got added.

Wow, that was fast. You're awesome dude.
