### ISSUE TITLE
Feedback: Link to hugo is pointing to 404

### ISSUE THREAD

**Issue by ohlrogge** [estruyf/vscode-front-matter#419]
Good morning,

just a tiny feedback :)

The link to hugo configuration https://frontmatter.codes/docs/hugo-configuration is pointing towards 404.

---
#### Document Details

⚠ *Do not edit this section*

* ID: static-site-generators/index
* URL: https://frontmatter.codes/docs/static-site-generators/index
* Content Source: /content/docs/static-site-generators/index.md

**Comment by estruyf** [comment]
Thanks @ohlrogge! We'll fix the link.
