### ISSUE TITLE
Recommendations table layout issues

### ISSUE THREAD

**Issue by bendera** [estruyf/vscode-front-matter#42]
Hi,

The Recommendations table falls apart after resizing.

![image](https://user-images.githubusercontent.com/3748508/126865430-fd6b9776-401e-440d-92c5-33d491b71c44.png)

Just kidding. I gonna fix it. Anyway, I would modify the table somehow like this:

![image](https://user-images.githubusercontent.com/3748508/126865937-6d2b859c-663f-4301-b672-9b63766adbd9.png)

You could save some space with this layout. It's just an idea.

**Comment by estruyf** [comment]
I like the suggestion. 

![image](https://user-images.githubusercontent.com/2900833/126868297-30855d98-1ccb-4818-b688-83bba7a9c67f.png)

The reason I want to use the icon instead of changing the color was to get it consistent with the keywords table.

**Comment by bendera** [comment]
I've updated the table component, let me know if you are facing any issues.

**Comment by estruyf** [comment]
Feel free to send in a PR @bendera

**Comment by estruyf** [comment]
`v2.0.1` will include a fix for this issue. Thanks again for reporting this @bendera!
