### ISSUE TITLE
Issue: Create New Content Button is greyed-out

### ISSUE THREAD

**Issue by dylan-k** [estruyf/vscode-front-matter#422]
**Describe the bug**
The "Create New Content" button is greyed-out. I'm not sure why.

**To Reproduce**
1. Go to edit a post
2. Click on the Front Matter button to show the side panel
3. Under actions, the Create new content button is greyed-out

**Expected behavior**
I image the "create new content" would create an empty post to quickly start writing it.

**Screenshots**
![Greyed Out Button](https://user-images.githubusercontent.com/2204716/191858935-405429f9-c6c0-411f-b7e6-1d335b7c1101.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Latest versions of vscode and Front Matter

**Additional context**
I've just set up an existing Hugo project to use Front Matter, and most things are working smoothly, but I can't use the "Create New Content" button. I completed the initial setup steps. I have two folders configured in `frontMatter.content.pageFolders`. In the `frontMatter.taxonomy.contentType` setting, I've indicated what template to use in my `archetypes` folder.

**Comment by estruyf** [comment]
@dylan-k thanks for opening an issue around this. I see that you haven't initialized the project yet. This will create the necessary files and folders Front Matter requires. Once completed, this button should become available to you, and the `initialize project` button will disappear.

You can also initialize your project by opening the dashboard.

**Comment by estruyf** [comment]
Found out that this button still has some old logic attached to it, fix will get implemented.

**Comment by dylan-k** [comment]
I've already been using the dashboard and it works for the most part, but the initialize button doesn't seem to do anything. Perhaps that's what the fix will address? The docs say that initialize will create a template but I don't see one in the directory.

**Comment by estruyf** [comment]
The fix should indeed fix this, v8.1.1 is now building and gets released in a couple of minutes. That button was still coupled somehow to the old template functionality.

**Comment by dylan-k** [comment]
Updated to the latest version, and it works now. Thank you :)
