### ISSUE TITLE
Enhancement:  `frontMatter.framework.id`: "HEXO"

### ISSUE THREAD

**Issue by lorezyra** [estruyf/vscode-front-matter#427]
**Is your feature request related to a problem? Please describe.**
"HEXO" is not listed as a framework despite the icon listed on the website. Rather than "other" can we add Hexo to this list?

**Describe the solution you'd like**
Add "HEXO" to the list of frameworks directly supported by FrontMatter.

**Describe alternatives you've considered**
Only alternative is to not use FM...

**Additional context**
I'm very new to FM. Found it a few days ago... It seems to have a lot of potential to make my workflows easier, but should not add to the pain of my website development.

**Comment by estruyf** [comment]
In the upcoming version, there will be an Hexo option for you to pick from.

![Xnapper-2022-10-07-13 28 34](https://user-images.githubusercontent.com/2900833/194543005-392c8d6e-79cf-48c7-8862-cba30eeb3761.png)
