### ISSUE TITLE
Categories picker height is too small

### ISSUE THREAD

**Issue by appieschot** [estruyf/vscode-front-matter#43]
When selecting a category even though there are 28 options it only shows the first option (can scroll down) but due to the small size the scrollbar is hard to reach. 

![image](https://user-images.githubusercontent.com/15227781/127112488-9fc763ee-3ff2-481b-b127-5509303255f1.png)

Sizing of the tags window is correct

Windows 10 / VSCode 1.58.2 (user setup) / vscode-front-matter v2.0.0

**Comment by estruyf** [comment]
Thanks @appieschot, I can see the issue on my end as well. Will submit a fix for this.

**Comment by estruyf** [comment]
`v2.0.1` will include a fix for this issue. Thanks again for reporting this @appieschot!

**Comment by appieschot** [comment]
Works flawlessly after updating 🤗
