### ISSUE TITLE
Enhancement: Type to Search for Snippets

### ISSUE THREAD

**Issue by michaeltlombardi** [estruyf/vscode-front-matter#440]
**Is your feature request related to a problem? Please describe.**

I've been adding the base Hugo snippets to my site in addition to my own custom snippets and the menu of available snippets is starting to get hard to navigate.

**Describe the solution you'd like**

I would like to be able to quickly search my snippets with either a fuzzy or simple match when trying to add a snippet to my content.

**Describe alternatives you've considered**

Perhaps an alternative, but more likely a separate feature request, I think it would be useful to have a command available to choose and insert a snippet from the command palette. Being able to type <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>p</kbd> -> `insert snippet` -> <kbd>enter</kbd> -> `mermaid` -> <kbd>enter</kbd> to go from my markdown to the insertion modal would be less disruptive for me, though I expect more users will benefit from the searchable snippet view on the dashboard.

**Additional context**

![Screenshot showing the snippets overflowing out of view in the dashboard as well as empty space highlighted where search could fit.](https://user-images.githubusercontent.com/14190564/194686701-f9cfe7cf-6a98-4a9c-a548-e1135821a075.png)

I think the unused space below the dashboard tab headers and left of the `Create new snippet` button could potentially be used for this functionality without being too intrusive.

**Comment by estruyf** [comment]
Makes sense! Should indeed become available in the UI. I would also say that when you click on the insert snippet action, the dashboard loads, and the search input is focused for you to instantly start searching through your snippets.

> command available to choose and insert a snippet from the command palette

A command already exists for inserting snippets when working on a file: `frontMatter.insertSnippet` (Front Matter: Insert snippet into your content) - this is the command used behind the scissor action.

For each available command in VSCode, you can register your own keybindings. In my case, I configured it to be <kbd>shift</kbd>+<<kbd>cmd</kbd>+<kbd>i</kbd>.

![image](https://user-images.githubusercontent.com/2900833/195039236-8fab4277-6457-4e6d-8bbf-e8b164273c85.png)

**Comment by estruyf** [comment]
I think this will help you out @michaeltlombardi - currently, the filtering is based on the snippet its title; should I include description as well?

https://user-images.githubusercontent.com/2900833/199998910-139260ee-ad3a-4b1d-961c-32eaeaf314fe.mov
