### ISSUE TITLE
Enhancement: Display description for all input fields

### ISSUE THREAD

**Issue by michaeltlombardi** [estruyf/vscode-front-matter#441]
**Is your feature request related to a problem? Please describe.**

The improvement in #391 made it much easier to understand metadata, but I noticed that the improved behavior didn't land for editing data files from the dashboard or inserting snippets. In both cases, the **description** key appears unused, neither appearing in the view nor when hovering over the inputs or their labels.

**Describe the solution you'd like**

I would like for the **description** key, when defined for input fields, to display in the same context similarly to how it does for content metadata fields. This would make it easier to understand what the inputs are for without having to refer to documentation.

**Describe alternatives you've considered**

Alternative to always displaying the description text, displaying that text when the user hovers on the label for that input would also be useful and possibly less disruptive to the UX, though also less discoverable I think.

**Additional context**

![Screenshot of a snippet modal beside its definition, showing the use of the description key but no indication in the modal of what the inputs do.](https://user-images.githubusercontent.com/14190564/194686867-d0d85587-9437-4a02-b198-b1025d06793c.png)

![Screenshot of editing a data file in the dashboard beside the data type's definition, showing the use of the description key but no indication in the dashboard of what the inputs do.](https://user-images.githubusercontent.com/14190564/194687037-88179aff-05c5-43bf-9257-628b8d593c0a.png)

**Comment by estruyf** [comment]
Input descriptions should now appear on snippet forms and data forms.
