### ISSUE TITLE
Enhancement: Collapsible data type selector in dashboard's data view

### ISSUE THREAD

**Issue by michaeltlombardi** [estruyf/vscode-front-matter#442]
**Is your feature request related to a problem? Please describe.**
When editing data files, the "Select your data type" side bar is always open, taking up space in the editor even when I'm not using it. This becomes most apparent when I'm doing side-by-side data input with content writing.

**Describe the solution you'd like**

I would like to be able to click a button to hide/show or slide in/out the selection menu on an as-needed basis, defaulting to open.

**Describe alternatives you've considered**

N/A

**Additional context**

![Screenshot showing the selection side bar taking up nearly have the available screen for the dashboard view in a split-editor instance of VS Code with the file tree on the left and a markdown document on the right.](https://user-images.githubusercontent.com/14190564/194687374-a4ad7ca2-b677-4f23-90d0-35aaf803eda5.png)

**Comment by estruyf** [comment]
When you selected a data file, the sidebar is hidden and you will get a dropdown selection at the top.

![Image](https://github.com/estruyf/vscode-front-matter/assets/2900833/6f71aeb7-d3b4-4c6f-84fd-b9b2df153ee3)
