### ISSUE TITLE
Enhancement: Support for dynamic values in Front Matter › Git: Commit Message?

### ISSUE THREAD

**Issue by balaji-dutt** [estruyf/vscode-front-matter#447]
### Discussed in https://github.com/estruyf/vscode-front-matter/discussions/446

It would be great if the `frontMatter.git.commitMessage` setting supported the use of Dynamic text replacements, such as `{{now}}` or perhaps `(datetime)`

**Comment by estruyf** [comment]
Thanks @balaji-dutt for creating this issue!

**Comment by estruyf** [comment]
Example:

```json
{
  "$schema": "https://beta.frontmatter.codes/frontmatter.schema.json",
  "frontMatter.git.enabled": true,
  "frontMatter.git.commitMessage": "Synced by Front Matter - {{now}}"
}
```

This will result in: `Synced by Front Matter - 2022-11-04T09:27:02.554Z`
