### ISSUE TITLE
Enhancement: Use filename if the markdown file does not contain a title

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#449]
Each markdown file is required to have a front-matter section. It will exclude the file from the dashboard if it does not contain one.

To ensure all files are shown, it would be better to fall back on the filename when no title is defined in the file.

![image](https://user-images.githubusercontent.com/2900833/199933054-2f5f8cd7-e070-4295-a7fc-1aaf9658e949.png)

**Comment by estruyf** [comment]
![Xnapper-2022-11-04-09 59 48](https://user-images.githubusercontent.com/2900833/199933410-a9c884c0-cbb4-477e-81ad-1255b2b8f7f7.png)

**Comment by dennisl68-castra** [comment]
Would it be possible to mark those files as non-compliant so that we don't forget about fixing them?

**Comment by estruyf** [comment]
@dennisl68-castra, in some cases or for some frameworks, they would be compliant, but I get your point. Think a validation based on the used content-type is in place, and if it contains required fields that are not provided, it should show up in the UI. 

If you have an idea of how to make it appear in the UI, feel free to share.

Also best that we create a new issue with this enhancement.
