### ISSUE TITLE
Enhancement: Option to hide non-needed panes and features be default

### ISSUE THREAD

**Issue by DennisL68** [estruyf/vscode-front-matter#453]
**Describe the solution you'd like**
The current solution do work with Git based on-prem Wikis such as Gollum and Wiki.js out of the box (well, for my needs anyway). But I'd like a simple option to hide and or minimize some of the FM Panes and features not necessary.

* Minimize `Global Settings`
* Hide `SEO Status` and disable `Keywords`
* Hide `Actions` (especially `Optimize slug`)

**Comment by estruyf** [comment]
Thank you @DennisL68 for opening an issue and giving Front Matter a try.

We have View Modes for this in order to define what you want to see: https://frontmatter.codes/docs/panel#view-modes

**Comment by DennisL68** [comment]
Just what I was looking for :)
