### ISSUE TITLE
Issue: frontmatter.global.modes doesn't work in file view

### ISSUE THREAD

**Issue by DennisL68** [estruyf/vscode-front-matter#455]
**Describe the bug**
When adding frontmatter settings to settings.json using
~~~
    "frontMatter.global.activeMode": "minimal",
    "frontMatter.global.modes": [
        {
            "id": "minimal",
            "features": [
            "panel.globalSettings",
            "panel.seo",
            "panel.actions",
            "panel.otherActions",
            "dashboard.data.view",
            "dashboard.snippets.view"
            ]
        }
    ]
~~~
and when viewing a file, random panes disappears.

**To Reproduce**
1. Open settings.json
2. Add the JSON section in the bug description above to the end of the settings file
3. Restart VS Code
4. Open a FM project and go to the extension 
5. View a markdown file in the FM project

**Expected behavior**
The panes and dashboards should be shown in accordance with the settings.json even when working with a file.

**Screenshots**

![image](https://user-images.githubusercontent.com/20666032/200398025-63d35393-8f4d-4b40-b57a-fdbc1b7703a0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2, build 19044,2130
- VS Code : 
    Version: 1.73.0 (user setup)
    Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
    Date: 2022-11-01T15:34:06.111Z (6 days ago)
    Electron: 19.0.17
    Chromium: 102.0.5005.167
    Node.js: 16.14.2
    V8: 10.2.154.15-electron.0
    OS: Windows_NT x64 10.0.19044
    Sandboxed: No
- FM: v8.1.2

Edit: I was actually doing this the wrong way around. Initially I thought these settings was for disabling the view. Not building customized views.

**Comment by estruyf** [comment]
Depending on which file you've opened or tab, there will be sections shown or removed.

For instance, the SEO or metadata section are only available on supported file/types.

**Comment by estruyf** [comment]
The reason why the SEO section is not shown is probably that there is no front matter data on the file (title and description).

Actions are empty, because of the following reasons:

- You don't have a title set in the front matter
- You are using `other` as a framework
- You did not provide a `frontMatter.framework.startCommand` setting value (for the known frameworks, it will use the default ones)

**Comment by estruyf** [comment]
For the SEO section, would you rather like to see this?

![image](https://user-images.githubusercontent.com/2900833/200536290-8a723386-dc18-4db1-a753-bc3fda1ec976.png)

**Comment by dennisl68-castra** [comment]
Yes, I am using "other" as framework.

**Comment by dennisl68-castra** [comment]
The SEO section would benefit by your suggestion. 

But I think a shorter description as "Title and Description is needed" is preferred?

**Comment by DennisL68** [comment]
This isn't an issue. Just a case of not reading the documentation properly :)
