### ISSUE TITLE
Issue: Deleted content does not get added in git when syncing

### ISSUE THREAD

**Issue by albbus-stack** [estruyf/vscode-front-matter#465]
All the deleted content, this being articles or images, is not added to git when syncing. Only the modified and not added files are being added to the git commit.

**Steps to reproduce**
To reproduce the behavior:
1. Create a new file
1. Commit it
1. Delete it and perform a sync with front matter

You are going to notice that the deleted file has not been committed.

**Expected Behaviour**
Even the deleted files should be added in the git commit since it's a clear modification of the contents of the cms.

**Solution**
Around [these](https://github.com/estruyf/vscode-front-matter/blob/1fe03197e336e8dde7cd879de97daa2eea9076df/src/listeners/general/GitListener.ts#L102) lines of ```GitListener.ts```, in the ```push()``` method, there should be another for loop iterating through the files contained in ```status.deleted``` adding them to the git commit.

Please let me know if I'm missing on something, I'll be happy to contribute in first person to the fix for this.

**Comment by estruyf** [comment]
Thank you @albbus-stack, for opening the issue and taking a look at it. If you feel you can fix it, and want to do a PR, you are more than welcome to do so.

**Comment by albbus-stack** [comment]
I've gone ahead and added the modification in the above PR, further details are explained there. I've assumed the dev branch was the correct place, if not just merge it elsewere at your liking and close this issue. Thank you and keep up the great work :octocat:

**Comment by estruyf** [comment]
Thanks @albbus-stack, your changes looked good and are now available in the latest beta version of the extension.
