### ISSUE TITLE
Issue: Registering the root of the project for content won't add the correct path

### ISSUE THREAD

**Issue by DennisL68** [estruyf/vscode-front-matter#469]
**Describe the bug**
The root folder of the project can be registered for content. But files added to it won't show in the dashboard.

**To Reproduce**
1. Navigate to the root folder of the project in `Explorer` view
2. Right click in the root and select `Front Matter: Register folder`
3. Add a new article in the project root
4. Open `FrontMatter Dashboard`
5. Notice the files from the project root is missing (trying to refresh won't help)
6. Open `frontmatter.json`
7. Change path for the root pageFolder from `"path": "[[workspace]]"` to `"path": "[[workspace]]/"`
8. Save the changes to `frontmatter.json`
9. Navigate back to `FrontMatter Dashboard`
10. Refresh the dashboard
11. Notice the previsoulsy missing files from the root is now displayed

**Expected behavior**
Adding the root of a Frontmatter project should add `/` to the path.

**Desktop (please complete the following information):**
- Version: 1.74.0 (user setup)
- Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
- Date: 2022-12-05T16:38:16.075Z
- Electron: 19.1.8
- Chromium: 102.0.5005.167
- Node.js: 16.14.2
- V8: 10.2.154.15-electron.0
- OS: Windows_NT x64 10.0.19044
- Sandboxed: No
- FrontMatter: 8.2.0

**Additional context**

**Comment by estruyf** [comment]
The project root is not recommended as it could include various files. Preferred is to put your content in a separate folder, and start from that point.

**Comment by dennisl68-castra** [comment]
Yes, bit as Git projects starts in the root we will have different ways of working. 

Besides you don't get an error when adding the root folder in Front Matter. The content just won't show up in the dashboard.

**Comment by estruyf** [comment]
A fix for this got implemented; now you can add the root folder, and the files will also show up on the dashboard. This is available in the latest beta.
