### ISSUE TITLE
Issue: Typo in FrontMatter Dashboard Data tab

### ISSUE THREAD

**Issue by DennisL68** [estruyf/vscode-front-matter#471]
**Describe the bug**
Instruction in `FrontMatter Dashboard` tab `Data` reads `Read read more to get started using data files`.

**To Reproduce**
1. Open `FrontMatter Dashboard`
2. Click on the tab `Data`

**Expected behavior**
Instructions should read `Read more to get started using data files`

**Screenshots**

![image](https://user-images.githubusercontent.com/20666032/204872719-a2440534-25b9-42f4-8ca9-1dcdd2c0b532.png)

**Desktop (please complete the following information):**
- Version: 1.73.1 (user setup)
- Commit: 6261075646f055b99068d3688932416f2346dd3b
- Date: 2022-11-09T04:27:29.066Z
- Electron: 19.0.17
- Chromium: 102.0.5005.167
- Node.js: 16.14.2
- V8: 10.2.154.15-electron.0
- OS: Windows_NT x64 10.0.19044
- Sandboxed: No
- FrontMatter: 8.1.2

**Additional context**

**Comment by estruyf** [comment]
Got updated

**Comment by dennisl68-castra** [comment]
Seems to be any easy fix ;)
