### ISSUE TITLE
Enhancement: Extend requirement for content

### ISSUE THREAD

**Issue by DennisL68** [estruyf/vscode-front-matter#473]
**Is your feature request related to a problem? Please describe.**
Currently, a markdown file has too contain the following front matter to be considered a content file
```
---  
title: ""  
description: ""  
---  
````

This mean that Title: "" won't qualify.

**Describe the solution you'd like**
Approve a file as content if using 

```
---  
Title: ""  
Description: ""  
---  
````

as well, if the framework selected supports it.

**Additional context**

**Comment by estruyf** [comment]
Thanks, @DennisL68, for the description, the solution is simple. You can configure the `frontMatter.taxonomy.seoDescriptionField` setting by setting the value to `Description`. That will allow you to use the `Description` field. Make sure to also change the name of the field in your content type.

For the title, the setting will have to be created so it will be enhanced in the upcoming version.

**Comment by estruyf** [comment]
A new setting just got added: `frontMatter.taxonomy.seoTitleField`, with this setting, you are able to set the default `title` value to `Title` and will make sure your content cards are rendered correctly and that the SEO status works.
