### ISSUE TITLE
Issue: Add missing fields adds fields to content type defintion "instead" of document

### ISSUE THREAD

**Issue by DennisL68** [estruyf/vscode-front-matter#480]
**Describe the bug**
When I choose `Add missing fields` option on a markdown file with properties not part of the content type, the central content type definition is updated with the additional field/s.

I don't want a random file with a misspelled property being the culprit of messing with the content types with out confirmation.  
Also, I somehow always expect the "missing" properties will be added to the file and not the other way around.

**To Reproduce**
Probably by design...

**Expected behavior**
1. `Add missing fields` should be labeled `Add missing fields to definition`.
2. Before updating the actual Content Type definition, have the user confirm the update first.

**Screenshots**
![image](https://user-images.githubusercontent.com/20666032/207124306-54b367ce-5f40-41df-b0e5-b29addb580db.png)

**Desktop (please complete the following information):**
- Version: 1.74.0 (user setup)
- Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
- Date: 2022-12-05T16:38:16.075Z
- Electron: 19.1.8
- Chromium: 102.0.5005.167
- Node.js: 16.14.2
- V8: 10.2.154.15-electron.0
- OS: Windows_NT x64 10.0.19044
- Sandboxed: No
- FrontMatter: 8.2.0

**Comment by estruyf** [comment]
This feature is intended to update the content-type so that it is easy to get started creating or updating content-types.

An `add missing fields to content` might also be appropriate.

**Comment by dennisl68-castra** [comment]
Yes, but it's labeled in a confusing way.

**Comment by estruyf** [comment]
Labels will be changed to the following:

![image](https://user-images.githubusercontent.com/2900833/217926509-2d6a4eab-d7cf-41d5-8f43-3424c3a813fb.png)
