### ISSUE TITLE
Issue: Set content type doesn't change the Content Type defintion

### ISSUE THREAD

**Issue by DennisL68** [estruyf/vscode-front-matter#481]
**Describe the bug**
When I choose `Set content type` option on a markdown file missing some of the properties from the content type, the central content type definition is not updated with the additional field/s.

**To Reproduce**
Probably by design...

**Expected behavior**
`Set content type` applies that the definition is to be changed. Since the option is found in `Content type`, I assume that the properties of the content type is to be changed.
Use `Apply content type` instead to indicate that the content type of the markdown file will be changed to a new type.

**Screenshots**
![image](https://user-images.githubusercontent.com/20666032/207124306-54b367ce-5f40-41df-b0e5-b29addb580db.png)

**Desktop (please complete the following information):**
- Version: 1.74.0 (user setup)
- Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
- Date: 2022-12-05T16:38:16.075Z
- Electron: 19.1.8
- Chromium: 102.0.5005.167
- Node.js: 16.14.2
- V8: 10.2.154.15-electron.0
- OS: Windows_NT x64 10.0.19044
- Sandboxed: No
- FrontMatter: 8.2.0

**Comment by estruyf** [comment]
Label has been changed with #480 - it is now `change content-type of file`.

![image](https://user-images.githubusercontent.com/2900833/217929769-0a2f3e12-24b3-4920-aea3-bd83d5d2c972.png)

Hope this makes it clearer.
