### ISSUE TITLE
Issue: Create content type offers to "override" default type

### ISSUE THREAD

**Issue by DennisL68** [estruyf/vscode-front-matter#482]
**Describe the bug**
When I choose `Create content type` option on a markdown file with properties I'd like to use for a new content type, I get the option to `Do you want to override the default content type?`

This implies that the default Content Type definition will be preserved and just overridden in this case and more options will follow.

I don't want a random file with a misspelled property being the culprit of messing with the default content type.

**To Reproduce**
Probably by design...

**Expected behavior**
* Change the question to  `Do you want to replace the default content type?`

**Screenshots**
![image](https://user-images.githubusercontent.com/20666032/207129835-df3a5fc4-40af-44e7-b238-ed12339e3fe4.png)

**Desktop (please complete the following information):**
- Version: 1.74.0 (user setup)
- Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
- Date: 2022-12-05T16:38:16.075Z
- Electron: 19.1.8
- Chromium: 102.0.5005.167
- Node.js: 16.14.2
- V8: 10.2.154.15-electron.0
- OS: Windows_NT x64 10.0.19044
- Sandboxed: No
- FrontMatter: 8.2.0

**Comment by estruyf** [comment]
As it is an override of the fields used in the default content type, maybe it is better to use: `Do you want to override the default content type with the fields used in the current field?`. What do you think?

**Comment by dennisl68-castra** [comment]
The configuration in the frontmatter.json for `default` is changed. 

So I would say the default content type is over written and not over ridden.

**Comment by estruyf** [comment]
Good point! 

`Do you want to overwrite the default content type configuration with the fields used in the current field?`

**Comment by dennisl68-castra** [comment]
That would clarify the point :)
