### ISSUE TITLE
Issue: Opening the parent folder of a frontmatter project will have frontmatter use it as a project as well

### ISSUE THREAD

**Issue by DennisL68** [estruyf/vscode-front-matter#483]
**Describe the bug**
When setting the vscode working folder to the parent of several Front Matter projects, the parent is treated as the default frontmatter project.

**To Reproduce**
1. Initialize three separate frontmatter test projects using the `other` framework as subfolders in a folder labeled `test` (close VS Code in between each new project)
2. Create a sample markdown file per project using 'Create new content`
3. Open the parent folder `test` in VS Code as the workspace
4. Open a markdown file in one of the front matter projects
5. Select the extension Front Matter

Note that Front Matter asks you to promote "local settings" to "global settings".
Note that a frontmatter.json file is added to the non frontmatter project folder `test`

**Expected behavior**
Front Matter shouldn't be greedy and claim folders to be projects that is not meant to be projects.
If the root of a workspace doesn't contain a `.frontmatter`folder, it's not a Front Matter project.

**Screenshots**
![image](https://user-images.githubusercontent.com/20666032/207131470-8efd2263-937d-4eb1-b607-e635fe8e4a49.png)

![image](https://user-images.githubusercontent.com/20666032/207132454-3b99bb81-922f-40e9-8a83-e1f256065cc7.png)

![image](https://user-images.githubusercontent.com/20666032/207135074-bc4331bc-8104-4c8e-b4e8-eea65a58bfd5.png)

**Desktop (please complete the following information):**
- Version: 1.74.0 (user setup)
- Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
- Date: 2022-12-05T16:38:16.075Z
- Electron: 19.1.8
- Chromium: 102.0.5005.167
- Node.js: 16.14.2
- V8: 10.2.154.15-electron.0
- OS: Windows_NT x64 10.0.19044
- Sandboxed: No
- FrontMatter: 8.2.0

**Additional context**

**Comment by estruyf** [comment]
This should not happen, as it should use the `test1` folder as the root for Front Matter, or it should ask you which one to use. Will have to check what might be wrong here and how it can be solved.

**Comment by dennisl68-castra** [comment]
If Front Matter always is using VS Code workspace (regardless of where it actually is) as the root folder I can see how this can get messed up.

**Comment by estruyf** [comment]
I have been testing the steps you mentioned before, but I need help getting Front Matter to trigger the exact behavior you are seeing.

![image](https://user-images.githubusercontent.com/2900833/209321369-0c918395-7f91-463a-8e5c-59faaf587cb8.png)

What did you have in your `settings.json` file? Can it be that a Front Matter CMS is setting defined? If that is the case, it is expected that this question will be asked.

**Comment by dennisl68-castra** [comment]
I'm on Christmas vacation at the moment, but will get back to you next week.

**Comment by estruyf** [comment]
Thanks and happy holidays @dennisl68-castra

**Comment by DennisL68** [comment]
I can't reproduce this issue any longer...

**Comment by estruyf** [comment]
Closing the issue as it cannot get reproduced anymore. In case it happens again, feel free to open it.
