### ISSUE TITLE
Issue: Excerpt is misspelled as exercpt in the front matter panel

### ISSUE THREAD

**Issue by jeffabailey** [estruyf/vscode-front-matter#486]
**Describe the bug**

The excerpt is misspelled as exercpt in the front matter panel

**To Reproduce**

1. Go to the front matter panel on a page.
2. Scroll to the **exercpt** field.
3. Notice it's misspelled.

**Expected behavior**

The field and the front matter line created by the input should be spelled:

**excerpt**

**Screenshots**

<img width="327" alt="image" src="https://user-images.githubusercontent.com/776901/209452143-8b67a2a9-852f-473a-b699-f535e8deaedd.png">

**Comment by jeffabailey** [comment]
Hugo refers to it as **excerpt**.

https://gohugo.io/content-management/summaries/#:~:text=more%20tag%E2%80%9D%20or%20%E2%80%9C-,excerpt,-separator%E2%80%9D%20in%20other

**Comment by estruyf** [comment]
@jeffabailey I think this is a misconfiguration in your `frontmatter.json` file for the content-type field. Front Matter does not use the `excerpt` field, so it is a manual configuration. Would you be able to check this?

**Comment by jeffabailey** [comment]
Interesting. I didn't configure this, but it's there.

<img width="693" alt="image" src="https://user-images.githubusercontent.com/776901/209573025-799950a0-2a8e-4eeb-a1a9-863e9980de4e.png">

I've updated the field, and now it's showing up correctly.

Thanks!

**Comment by estruyf** [comment]
Thanks @jeffabailey for the update. How did you create the content type? The content-type configuration looks like it was generated from an existing article, so I believe it was misspelled in one of the articles where you let Front Matter create it.

Glad you found it.

**Comment by jeffabailey** [comment]
I'm not sure.

I migrated from Wordpress to Hugo, but I don't see a reference to exercpt in the code.

It created the content type. I'm guessing there was a typo on my part along the way.
