### ISSUE TITLE
Issue: .frontmatter folder is created before project is initialized

### ISSUE THREAD

**Issue by DennisL68** [estruyf/vscode-front-matter#488]
**Describe the bug**
Just by entering the FrontMatter Dashboard, a `.frontmatter` folder is created although I've not yet decided to create a FrontMatter project.

**To Reproduce**
1. Create an empty folder
2. Open that folder as workspace in VS Code
3. Select FrontMatter extension
4. Open the FrontMatter Dashboard.

**Expected behavior**
FrontMatter shouldn't be greedy and claim folders until I initialize a FrontMatter project.
**Screenshots**
![image](https://user-images.githubusercontent.com/20666032/210242498-b7fbdfc6-e469-47aa-b323-fbb92908031c.png)

**Desktop (please complete the following information):**
Version: 1.74.2 (user setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
FrontMatter: 8.2.0

**Additional context**

**Comment by estruyf** [comment]
Thanks @DennisL68 for opening this issue, I found the cause and it has been fixed. Now the folder gets created when the project actually get initialized, not before. It is testable in the latest beta version of the extension.
