### ISSUE TITLE
Issue: Remote Images in "image" type results in "error loading field"

### ISSUE THREAD

**Issue by traeblain** [estruyf/vscode-front-matter#494]
**Describe the bug**
When a remote resource (remote image) is used in the "image" type, an error is provided and now image is generated for the isPreviewImage in the post/page list.

**To Reproduce**
1. Setup an image type field
2. Add a remote resource to the field (i.e. https:://example.com/image.jpg)
3. Look at Front-Matter sidebar
4. See error "error loading field"
5. See no image in Preview on the post/page list

**Expected behavior**
Still show the image thumb in FrontMatter (remove option still available), and see the image in the preview on the dashboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/912852/214411688-1d4c2d68-034d-41af-9be1-754d88e0c362.png)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser: chrome
 - Version: 109

**Additional context**
I know there the "remote media" enhancement #445 that is looking to enhance the media library, but if you don't use a local media library (i.e. CDN media storage) you cannot even use the links without dealing with this error.  I understand Front Matter isn't ready to deal with remote libraries yet, but if I paste in the URL to an image field manually, expectation is that it would at least still show...even if it's not local.

**Comment by estruyf** [comment]
It is by design, as the field expects to render only images from the current project.

It is an excellent enhancement to get this also supported!

**Comment by traeblain** [comment]
Awesome, hope it happens.  I use Cloudinary, and I know getting those media libraries setup is down the road, but simply supporting remote images will make Front Matter the perfect CMS for my use case.  Good work all.

**Comment by estruyf** [comment]
Support has been added to the latest beta version @traeblain - feel free to try it.
