### ISSUE TITLE
Enhancement: Add support for movie media types

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#497]
In the latest versions of VSCode, the mp4 format is supported. It would be great if Front Matter supported it as well.

**Comment by estruyf** [comment]
Movie media previews will now show up in the content dashboard.

![Screenshot 2023-01-30 at 10 17 51](https://user-images.githubusercontent.com/2900833/215436488-078fb9fe-fc4f-443f-9700-12142589fbfd.png)

**Comment by michaeltlombardi** [comment]
Love this!
