### ISSUE TITLE
Enhancement: Investigate the possibility of a port of Front Matter CMS for the application Zettlr

### ISSUE THREAD

**Issue by DennisL68** [estruyf/vscode-front-matter#498]
**Is your feature request related to a problem? Please describe.**
Front Matter CMS can only be used with VS Code. For some users, VS Code is a to steep step to go.

**Describe the solution you'd like**
Investigate if a port of Front Matter CMS is possible for the Open Source Solution [Zettlr](https://www.zettlr.com/) (a dedicated WYSYWYG Markdown Editor)

**Describe alternatives you've considered**
As far as I can tell, no other application supports CMS for YAML Frontmatter as this extension do.

**Additional context**
I'd really like to see this extension spread to other platforms/applications such as GitLab, Azure DevOps, GitHub and Zettlr.

**Comment by estruyf** [comment]
Would you happen to know if Zettlr has extensions?

The extension can be used on codespaces like GitHub and Gitpod.

**Comment by DennisL68** [comment]
It currently doesn't support extensions to my knowledge.
I'll ask...

**Comment by DennisL68** [comment]
He doesn't currently seem to be interested in supporting plugins.
(Although, he is interested in CMS features in the future.)

**Comment by estruyf** [comment]
Good to know, thank you for asking!
