### ISSUE TITLE
how to set my timezone?

### ISSUE THREAD

**Issue by StefanoCecere** [estruyf/vscode-front-matter#5]
it seems to use Timezone 0 (GMT)
i'm on GMT+2

and times are inserted with 2 hours anticipation...
any clue?

**Comment by StefanoCecere** [comment]
ok i solved setting the Date Format to

```yyyy-MM-dd'T'HH:mm:ss.SSSxxx```

but now i get this result:

```date: '2019-09-14T13:42:13.221+02:00'```

but id' like the result without the ``, like

```date: 2019-09-14T13:42:13.221+02:00```

is it possibile?

**Comment by estruyf** [comment]
@StefanoCecere, I did an update to the extension, this should now add the date when you use the format without quotes.

**Comment by StefanoCecere** [comment]
0.0.10 works perfectly!! thank you!
PS: i'm starting to use it in a huge Hugo site

**Comment by estruyf** [comment]
Thanks for verifying!
