### ISSUE TITLE
Feedback: Metadata section vs. content types in split-file configuration

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#516]
I am not sure if this is a bug or a misconfiguration, because in the past weeks I migrated my older config setup to the current state of configuration options (thank you for split config files!).

[I uploaded the current state in this commit](https://github.com/davidsneighbour/kollitsch.dev/tree/5a0b55cb9c57fd94d72b59721186eb02e0bd4676).

It appears that in my current state Frontmatter does NOT fully recognize my content types. It ignores preview images (defined in the default content type) and i have to add "type: blog" (not the default type) to my frontmatter to show the preview image in the dashboard.  

I would expect the default content type to take over, even without the frontmatter `type: contenttype` line. It does, partly, but not with the article image. Content types blog and default are configured identical and the preview image is located in the resource field group.

It also shows a weird notice in the sidebar metadata section:

![20230227-17:47:59-Selection-001](https://user-images.githubusercontent.com/83281/221543946-afad59a7-ea71-4dcd-b183-986499fa903f.png)

and THEN it shows the fields properly configured by type.

Of the three grey buttons, the first two add their changes to the `frontmatter.json` file, NOT my split file config in `.frontmatter/taxonomy/contenttypes/*.json`. The last button, select content type, shows for a split second a vscode selector popup (like CTRL+SHIFT+P) that is without selections.

So, my assumption is, that either I have something configured wrong, or that there is maybe a bug that does not treat the content type 100% separated with splitfiles.

**Comment by davidsneighbour** [comment]
After CTRL+SHIFT+P > Reload Window instead of the Dashboard the install routine pops up, asking for content folders. I guess the pagefolder config is also ignored at certain points. 

![20230227-19:58:17-Selection-001](https://user-images.githubusercontent.com/83281/221570143-62491f44-aeaf-43f2-b06a-3642c76bd9d4.png)

**Comment by yolpsoftware** [comment]
Same issue here.

**Comment by estruyf** [comment]
@yolpsoftware can you give me more information to start reproducing the issue? I believe @davidsneighbour has already figured this out.

**Comment by yolpsoftware** [comment]
@estruyf sorry I do not remember under what circumstances this has happened. I wanted to try some things out to solve it, or collect more information, but then the problem somehow disappeared.

If it happens again, I'll let you know and I'll provide more information.

**Comment by estruyf** [comment]
Thank you @yolpsoftware, will close the issue for now.

**Comment by davidsneighbour** [comment]
Sidenote: I forgot I opened this issue and it was on my side. I had made changes to the local .frontmatter directory/config and my commit-hook setup stashed uncommitted changes when I did git commits on unrelated things. This "triggered" Frontmatter a bit because the config changed twice (into stash, out of stash), which was too fast for Frontmatter.
