### ISSUE TITLE
Issue: Wrong change log date?

### ISSUE THREAD

**Issue by GuidanceZero** [estruyf/vscode-front-matter#525]
In https://frontmatter.codes/updates

[8.3.0] - 2022-02-14

Should be

[8.3.0] - 2023-02-14

**Comment by estruyf** [comment]
Oh, dates are so hard! 😄 - Thanks have changed this in the beta version. Eventually, the main version will also get it, but I won't yet do a new release for this.

Thanks again for pointing this out @GuidanceZero  🙏!
