### ISSUE TITLE
Issue: Layout issue with submenu under the paging bar

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#526]
I am on today's updated beta version of Front Matter. My dashboard looks like this:

![20230306-21:43:13-FrontMatterDashboard-workspace(Workspace)-HugoandFullStack-VisualStudioCode-001](https://user-images.githubusercontent.com/83281/223143444-b848ef6c-53be-47ea-a79b-573b47a90fc1.png)

Note how the first item in the dropdown/up menu is hidden under the pager bar. I think it might be a z-index issue because the items shown in the dropdown (including the half-hidden one) are all that are in the submenu. There aren't any more entries in there. 

The second line of entries pops up properly.

Might be easy to solve?

**Comment by estruyf** [comment]
Thanks @davidsneighbour, will take a look at it.

**Comment by estruyf** [comment]
@davidsneighbour just added a fix, let me know if this is now working on your end with the latest beta.

**Comment by davidsneighbour** [comment]
Works perfectly. Thanks for your efforts and thanks for not going crazy with our barrage of "issues" :)

**Comment by estruyf** [comment]
No worries! It is great to have people reporting these issues so that Front Matter can become better for everyone. 🙏
