### ISSUE TITLE
Issue: Astro section and YAML parser issue

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#528]
Related to thread on Discord: https://discord.com/channels/992409023607476224/1082992278341169202

If you edit a Markdown file, on the left side you have your Front Matter panel, and then switch to an Astro file via the file tabs, you get a YamlParserError error message. 
I think that's because Astro is using the front matter section, the 3 minus signs --- ... ---, for itself to put Javascript there.
In the settings it says only md, mdx and markdown files should be considered, but this doesn't seem to work.

![image](https://user-images.githubusercontent.com/2900833/223722611-19eafc67-dc82-4473-88c1-6fa15f3d4977.png)

**Comment by Mikescops** [comment]
Hey @estruyf this issue is back in `10.9.0` unfortunately.
