### ISSUE TITLE
Issue: Extra characters are being added to the frontmatter when updating values in the UI

### ISSUE THREAD

**Issue by lloydjatkinson** [estruyf/vscode-front-matter#529]
**Describe the bug**

Extra characters are inserted.

https://user-images.githubusercontent.com/5633938/223826915-5b7e6af3-747b-4e63-80e4-b519e2a9bd48.mp4

**To Reproduce**
1. Use Astro
2. Edit a value
3. Note extra characters can appear in the frontmatter

**Comment by estruyf** [comment]
Thanks @lloydjatkinson, for reporting this. I will have to check what might be going on here.

**Comment by estruyf** [comment]
I have been looking into it but have been unable to reproduce it on Windows and macOS. Would you be able to share a test project in that I can reproduce it?

Can you also test out the beta version to see if you have the issue there as well?

**Comment by estruyf** [comment]
I have been able to reproduce it in Windows. You seem to get an extra carriage return at the end for some reason.

**Comment by estruyf** [comment]
@lloydjatkinson have you been able to give the beta a try?
