### ISSUE TITLE
Issue: update from 8.2.0 to 8.3.0 breaks editing of arrays in data view

### ISSUE THREAD

**Issue by Mai-Lapyst** [estruyf/vscode-front-matter#531]
**Describe the bug**
When defining a data type which has a array as member, the fields dont get loaded and stored correctly.

**To Reproduce**
1. Create a new project
2. Initialize frontmatter
3. Add following to `frontmatter.json`
   ```json
   "frontMatter.data.types": [
     {
       "id": "bass_player",
       "schema": {
         "title": "Bass Player",
         "type": "object",
         "required": ["discography"],
         "properties": {
           "name": {
             "type": "string"
           },
           "discography": {
             "type": "array",
             "items": {
               "type": "string"
             }
           }
         }
       }
     }
   ],
   "frontMatter.data.folders": [
     {
       "id": "bass_players",
       "path": "[[workspace]]/data/jazz/bass",
       "type": "bass_player",
       "singleEntry": true
     }
   ]
   ```
5. Add a data file: `data/jazz/bass/jacopastorius.json`:
   ```json
   "name": "Jaco Pastorius",
   "discography": [
     "1974 - Modern American Music … Period! The Criteria Sessions",
     "2003 - Punk Jazz: The Jaco Pastorius Anthology (compilation)",
     "2007 - The Essential Jaco Pastorius (compilation)"
   ]
   ```
6. Open the data view in front matter

**Expected behavior**
That arrays are editable in the data view.

**Screenshots**
Version 8.2.0:
![image](https://user-images.githubusercontent.com/67418776/224521182-84f53cf5-a89d-4ad3-8041-4326b7b4e035.png)

Version 8.3.0:
![image](https://user-images.githubusercontent.com/67418776/224521214-9f557d81-b338-4f5b-bbe8-fbe8ac08dd5a.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser VScode
 - Version 1.76.0

**Additional context**
Seems mostly due to this line being commented out:
https://github.com/estruyf/vscode-front-matter/blob/d364bde59dad6e9433c4932fb7acb96ef107233c/src/components/uniforms-frontmatter/ListField.tsx#L35

**Comment by estruyf** [comment]
Thank you @Mai-Lapyst, for reporting and investigating the issue. The prettier changes that were PR-ed recently accidentally commented on this line. 

I have reverted the change and tested it with your configuration. The fix is now included in the latest beta.

**Comment by Mai-Lapyst** [comment]
@estruyf thanks for the qiuck response; have tested the beta, and can confirm that it works now
