### ISSUE TITLE
Enhancement: Retain Front Matter rail's scroll context

### ISSUE THREAD

**Issue by BillRaymond** [estruyf/vscode-front-matter#535]
**Is your feature request related to a problem? Please describe.**
While editing metadata in the Front Matter rail, you often have to switch context to a new file or tab. Take for example, selecting an image, which will open the Frontmatter dashboard.

However, when you return to the file, you are brought back up to the top of the rail (in my case it reads "Global Settings"). This context-switch requires you to scroll back down the rail to find where you left off. 

**Describe the solution you'd like**
When the user leaves a file and returns and the Front Matter rail is currently open, return to the location where the user left off.

**Describe alternatives you've considered**
Since this is an issue with the rail in general, as a user that is just getting started, I am regularly losing my place and finding editing to be hard. Here are some thoughts, in no general order:

* Remember the rail's current scroll position based each file being accessed (ex if you are writing two posts at the same time, the rail remembers the scroll location for each)
* Provide rail modes, such as "metadata", "actions", etc. When you are in editing mode, metadata starts at the top. When you are in actions, the rail moves to "other actions"
* Move the SEO Status area to the bottom of the metadata. I think users will be typing their metadata from top-to-bottom, so perhaps having the SEO status underneath the metadata editing section is more useful anyway?

**Additional context**
As you can see in the following animation, any context switching to another tab in VSC resets the rail, even when performing in-line metadata updates.

![frontmatter-context-switch-issue](https://user-images.githubusercontent.com/15895828/225119798-2dfbf503-b509-48f5-847f-923adb13ef64.gif)

**Comment by estruyf** [comment]
Thanks @BillRaymond, makes so much sense!

**Comment by estruyf** [comment]
The first implementation has been completed and can be tested out in the latest beta.

https://user-images.githubusercontent.com/2900833/225257734-1a949221-b9c0-45f8-b517-f3834401977b.mov

**Comment by BillRaymond** [comment]
Thanks! I just tested this and it does work, thank you!

So you are aware, if you are brought to the FrontMatter Dashboard and close it without selecting something, the rail returns to the top like it did previously. The reason I know this is because my content is for a podcast where I select various guests and I forgot which person I was supposed to select. This is probably an edge case but thought you would like to be aware.
