### ISSUE TITLE
Enhancement: 😀 Support for YAML non-printing characters

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#538]
Related to the following Discord thread: https://discord.com/channels/992409023607476224/1085255612939640832

Very often, the YAML front matter includes text that will display on a page, like the following:

title: Hello World 🌎

However, the proper YAML would be:
title: Hello World \U0001F4CD

FM currently adds the non-printable character (like an emoji) to the text, which errors out on build since it is not properly formatted YAML

I can understand that FM would not want to modify an existing file, but there is an opportunity to catch non-printable characters when creating/modifying metadata in the Front Matter rail

Author: @BillRaymond

**Comment by estruyf** [comment]
Yes @davidsneighbour, but for @BillRaymond it isn't it seems. That is why an extra property is introduced. If your SSG/framework wouldn't support it, you can let FM encode it for you.

**Comment by estruyf** [comment]
By default, it will keep using `Hello World 🌏`, only if you need to encode the emoji, you will have to tell FM to do this.

**Comment by BillRaymond** [comment]
> Isn't
> 
> title: "Hello World 🌏"
> 
> possible/valid too?

While you can add emojis and other non-printable characters to YAML, they are technically not allowed. See [here](https://yaml.org/spec/1.2.2/#character-set). Some YAML processors handle this for you, but others do not. In my specific situation, I use Jekyll (also the default for GitHub Pages), which errors out. That is why I requested that FM provide a conversion option.

**Comment by BillRaymond** [comment]
Thank you!

**Comment by estruyf** [comment]
Thanks @BillRaymond, it is the YAML parser which decides to add quotes or not, will take a look why and when.

**Comment by estruyf** [comment]
I have done some tests, and in my environment, when double quotes are added, it will use a double backslash, which is how it should be to correctly parse the string.

https://user-images.githubusercontent.com/2900833/226557345-c5af9121-9e85-44e9-8546-3da487597e7c.mov

**Comment by BillRaymond** [comment]
In this example, I add the Unicode escape character into the title. FM does not automatically put the title in quotes.

If the YAML is not in quotes, the Unicode is processed as regular text and does not display the non-printable character. 

However, if I manually put the title in quotes, the proper non-printable character is processed and displays on the website.

![emoji-no-yaml-quotes](https://user-images.githubusercontent.com/15895828/226780598-d588b517-0ee2-45be-abbf-be1abf0fa908.gif)

**Comment by estruyf** [comment]
Although it makes it work for your use case, it is not valid for a JSON object. We will have to think about how we can get this supported, as the double backslash is the right way to encode it.

**Comment by estruyf** [comment]
I just did a test on Jekyll, and I can just use `🌎` in the title:

![image](https://user-images.githubusercontent.com/2900833/226857767-9928f0d7-2ae4-471a-b545-97ca6e05de8f.png)

Can it be related to your theme?

**Comment by estruyf** [comment]
It seems that backslashes and YAML is a big topic, most recommend to avoid using backslashes. That said, the only valid way to have a backslash in the JS and Python YAML parser is to use two backslashes when using quotes. This is what the parser will automatically add while parsing.

**Comment by estruyf** [comment]
![image](https://user-images.githubusercontent.com/2900833/226979369-86b6ce7f-134f-4b88-8d1f-4d5db65d3eeb.png)

It is also in the YAML docs.

**Comment by estruyf** [comment]
No worries, I learned something from it as well. I might just keep the setting as is right now, in case anyone else might ever need it.

**Comment by estruyf** [comment]
All is fine, I keep it in progress, as I still need to document it.
