### ISSUE TITLE
Feedback: move taxonomy.tags/categories/et alii to the .frontmatter subdirectories or the db

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#558]
```
"frontMatter.taxonomy.tags": ["lots", "of", "tags"],
"frontMatter.taxonomy.categories": ["some", "categories"]
```

I realized these two config items are dynamically updated on content changes. Others for frontmatter values I am not using probably too. If the use of this is to fill dropdowns and keep an index of content, wouldn't it be a better place for them to be either in their own files under `.frontmatter/config/taxonomy` or even within `.frontmatter/content/taxonomyDb.json` and `categoryDb.json`? Updating the _config_ file on _content_ changes feels counterintuitive for the concept of a CMS. Especially non-hierarchical taxonomies might get updated every single time new content is added.

**Comment by estruyf** [comment]
Are you reading my mind @davidsneighbour 😄. I was thinking about that last week, but I hadn't come up with a solution yet, but you just did.

I love the `taxonomyDb.json` idea. It makes sense now that I just moved the `mediaDb.json` to a `database` folder.

**Comment by estruyf** [comment]
The tags and categories are now moved to their own `taxonomyDb.json` file. When you open a project, it will check if tags or categories are present in the DB. If not, it will update it with the one from your settings.

![Xnapper-2023-04-14-15 49 33-EEF51F45-F8AE-472C-9904-C3A5F00927FC](https://user-images.githubusercontent.com/2900833/232063761-c06d5c8b-bb3b-4099-bf64-bb8ca53424d6.png)
