### ISSUE TITLE
Issue: taxonomy filters are slightly mispositioned

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#567]
![20230407-14:49:42-Selection-001](https://user-images.githubusercontent.com/83281/230566821-d5e4547b-b37e-4794-84d9-41fdcce1af2e.png)

It looks like the tags and category filters are slightly higher positioned due to the icon positioning. If the icons have vertical-align:baseline they probably should have bottom instead.

**Comment by estruyf** [comment]
Fix is coming up
