### ISSUE TITLE
Issue: When deleting content of a Page Bundle, only index.md is being deleted.

### ISSUE THREAD

**Issue by dotjesper** [estruyf/vscode-front-matter#569]
**Describe the bug**
When deleting content of a Page Bundle, from the Front Matter dashboard, only index.md is being deleted.

**To Reproduce**
1. Create a Page Bundle posts
2. In the Dashboard, select post and Delete
3. Go to the Content folder, e.g. under posts, the empty "post folder" is still present.

**Expected behavior**
I would expect the folder to be deleted, including files and/or subfolders - alternatively, moved to ./.frontmatter/deleted/..

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Editor: VS Code 177.1
 - Front Matter 8.4

**Additional context**
None

**Comment by estruyf** [comment]
This has been implemented and can be tested in the latest beta version.
