### ISSUE TITLE
Issue: Auto Init of Frontmatter in any folder opened in VS Code

### ISSUE THREAD

**Issue by webmanufaktur** [estruyf/vscode-front-matter#573]
**Describe the bug**
Starting VS Code from Terminal/CLI results in INIT of Frontmatter.

**To Reproduce**
1. Open terminal
2. Create new project folder
3. cd into project folder
4. run `code .`
5. opens VS Code, after 1s new ,frontmatter shows up

**Expected behavior**
No new .frontmatter folder

**Screenshots**
See screencast: https://www.youtube.com/watch?v=do-pxRRg_5E

**Desktop (please complete the following information):**
 - OS: Linux, Ubuntu 23.04
 - Terminal: Kitty/Gnome Terminal

**Additional context**
Ask for context... the screencast should be clear.

**Contact me**
- DM on Twitter @acabelt - as before

**Version VS Code**
Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:52.732Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 6.2.0-20-generic
Sandboxed: No

**Version Frontmatter CMS Beta**
v8.5.4700543

**Comment by estruyf** [comment]
Can you verify if you have any `frontMatter.*` settings in your global user settings JSON file? That might be the reason why this is happening.

**Comment by estruyf** [comment]
You installed the beta - this is a feature in development #558. Will have to apply a check, so that it doesn't happen, but not a bug in the stable version. Still great for reporting it.

**Comment by estruyf** [comment]
Fix is coming up, so this should only happen if the project is initialized.

**Comment by webmanufaktur** [comment]
Thank you so much!
Still glad to have helped with some things here.
Love FMCMS!
