### ISSUE TITLE
Enhancement: Date format in preview path

### ISSUE THREAD

**Issue by svrooij** [estruyf/vscode-front-matter#593]
**Is your feature request related to a problem? Please describe.**
I migrated from Jekyll to Hugo and wanted to keep the old url format `/{year}/{month}/{day}/{slug}` this is perfectly doable in Hugo. But now I cannot get the preview path to load, since it would require having the day.

**Describe the solution you'd like**
I would like support for either `{{fm.day}}` / `{{fm.month}}` / `{{fm.year}}` in the preview path or have some sort of formatting option on the provided date value like `{{fm.date.format('yy')}}` or `{{fm.date:yy}}` depending on language features.

**Describe alternatives you've considered**
I've considered using the `{{pathToken.x}}` placeholders, but that does not work because I don't have the day folder, since my posts are stored in `content/posts/{year}/{month}/{slug}.md` format.

**Comment by svrooij** [comment]
@estruyf yes I do have the date field in the front matter. I think it's even a default field if you setup front matter CMS.

I was not sure if formatting would be an option, or if it would be easier to make 3 addition special placeholders `day / month / year` that are filled if the frontmatter has a `date` property.

**Comment by estruyf** [comment]
Indeed, OOTB Front Matter has a date field, but you can adapt it by referring to your older articles. 

This `{{fm.date:yy}}` is my preferred format right now, but more thinking towards something like this: `{{fm.date | dateFormat 'yyyy'}}`

**Comment by svrooij** [comment]
Having the `| dateFormat 'yy'` would allow using it on other fields as well. That sound like a perfect plan.

**Comment by estruyf** [comment]
@svrooij I have added it. The format changed a bit. I've asked ChatGPT what would be the ideal field definition. It was pretty close to what we already came up with.

The format for this will be: `{{fm.<field name>|format:<your format>}}`. Example: `{{fm.pubDate|format:dd/MM/yy}}`.

![Xnapper-2023-06-29-11 41 06](https://github.com/estruyf/vscode-front-matter/assets/2900833/7281590c-f120-441d-b6df-e78f23c444dc)

**Comment by svrooij** [comment]
It works perfectly, shall I close the issue? Or does that happen automatically if you release the new version

**Comment by estruyf** [comment]
@svrooij I will close it when I document and release it in the main version.
