### ISSUE TITLE
Showcase: My blog

### ISSUE THREAD

**Issue by lolbat** [estruyf/vscode-front-matter#594]
**Title you want to give your site**
What is wrong with your dog?

**Link to the site**
https://whatiswrongwithyourdog.netlify.app/

**A nice and clean description**
A blog containing my writing on tech and other issues. Slightly salty at times. 

I also have a post specifically about using VS Code and Frontmatter

https://whatiswrongwithyourdog.netlify.app/posts/visualstudiomarkdown/

**Comment by estruyf** [comment]
@lolbat your website just got added to the showcase page: https://frontmatter.codes/showcase

Thank you for writing the article on Front Matter CMS 🙏
