### ISSUE TITLE
View Modes code in docs generates incorrect reuslts

### ISSUE THREAD

**Issue by lolbat** [estruyf/vscode-front-matter#597]
**Describe the bug**
Following the steps in the documentation at 
https://frontmatter.codes/docs/panel#view-modes

does not result in the screenshot shown. 

**To Reproduce**
1. Copy code in settings.json
2. Save
3. Select Minimal mode

**Expected behavior**
The panels listed in the mode should appear

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 13.3
 - Browser this is running in VS Codium
 - Version Version: 1.79.2
Release: 23166
Commit: 19c0f5cefaeb2637b45a9c7a356151fcfdcda1e9
Date: 2023-06-15T18:10:57.030Z
Electron: 22.3.10
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0

![CleanShot 2023-06-30 at 15 24 22](https://github.com/estruyf/vscode-front-matter/assets/4564571/4df16948-b80a-42d4-8b06-7ca3d31768dd)

![CleanShot 2023-06-30 at 15 24 33](https://github.com/estruyf/vscode-front-matter/assets/4564571/d1096fd1-b37a-42c4-b0d8-6bcc6cadfafd)

**Comment by estruyf** [comment]
The screenshot/documentation needs to be updated. Thank you for pointing this out @lolbat.

**Comment by estruyf** [comment]
Documentation has been updated with a new screenshot and settings.
