### ISSUE TITLE
Enhancement: Multilingual UI

### ISSUE THREAD

**Issue by gsegit** [estruyf/vscode-front-matter#598]
Hi there ;D
Can your Ext be translated into another language, such as my native German ? Is something like that foreseen ? 

Greetings from Germany ;D

Bogus

**Comment by estruyf** [comment]
Thanks for the suggestion @gsegit. Haven't planned anything for this yet, but if you want or any other of the contributors, I'm welcome to accept PRs for this one.

**Comment by estruyf** [comment]
I have been optimizing the flow. There are two new scripts created:

- `./scripts/sync-localization.js`: This script will sync all the localization keys from EN to the other available languages. When a key is not present, it will be at the EN value + the 🚧 sign. In the future, we might use a service for automatically translating those labels and getting them validated by the users.
- `./scripts/generate-localization-enum.js`: This script created an [enum file](https://github.com/estruyf/vscode-front-matter/blob/issue/598/src/localization/localization.enum.ts) so that we do not have to guess the keys during the development.

When creating a key, start with the type of web view to where you want to add it. This can be `panel` or `dashboard`. Example:

```json
{
  "dashboard.header.createContent": "Create content",
  "dashboard.header.startup.label": "Open on startup?",

  "panel.actions.title": "Actions",
  "panel.actions.openDashboard": "Open dashboard",
  "panel.actions.openPreview": "Open preview",
  "panel.actions.startServer": "Start server",
  "panel.actions.stopServer": "Stop server",
  "panel.actions.createContent": "Create content"
}
```

> **Important**: Make sure to add the key and label to the EN - `bundle.l10n.json` file.

If you want to start using the localization labels in the web views, you must include the `l10n` dependency and `LocalizationKey` enum.

```typescript
import * as l10n from "@vscode/l10n"
import { LocalizationKey } from '../../localization';

// Usage
l10n.t(LocalizationKey.panelActionsCreateContent)
```

**Comment by estruyf** [comment]
All the hardcoded strings have been moved over to the `./l10n/bundle.l10n.json` EN localization file. The file contains the key/values for both the panel and the dashboard webviews.

**Comment by estruyf** [comment]
Commands and settings have also been localized. To support another language, create a new `package.nls.<locale>.json` file in the project's root and copy the contents of the `package.nls.json` file to it.

**Todo**

- [ ] Documentation schema script (https://github.com/FrontMatter/web-documentation-nextjs/blob/6de4b327ea00a9e7c59d5592d5662b29c84731d4/scripts/generate-schema.js) needs to be updated to replace the localization keys

**Comment by estruyf** [comment]
@mayumih387, you can test out the latest v9 beta which includes your Japanese translations.

**Comment by mayumih387** [comment]
Thank you @estruyf for your review at #598. I'll try the latest v9 beta and see if I can add further translations :)

**Comment by estruyf** [comment]
@gsegit I have added German translations (via OpenAI). Would you be able to give the latest beta a try and check if they are any good?

**Comment by gsegit** [comment]
> @gsegit I have added German translations (via OpenAI). Would you be able to give the latest beta a try and check if they are any good?

Hi there 🌞 sorry for the later answer, but i have total forget my post here 😅 Thanks you for your, i would test the translation in the next days 😎🌞

**Comment by gsegit** [comment]
Hi there ;D
Wow, very great work and now the dokumention in german ;D No, is a joke, but I think you make a very good work and is now more easier to work with hugo or so ;D

Greetings
Gerriet 
Have a nice Day ;D

**Comment by gsegit** [comment]
Hi there
The problem is, in german give a formular "Sie" and informular "du", the translation have you make openAI, the KI make no different between sie or du. I like more "du". Better is the strings to write  in a file, so can make a better translation, ok that is very hard work, but is better for user.

I hope you understand my englisch 🤣

**Comment by estruyf** [comment]
A lot of the German translations were manually provided by one of our contributors. If you see some mismatches or where translations can be enhanced, feel free to push changes via a PR, and we will be happy to merge them into the project.

The German translation file can be found here: https://github.com/estruyf/vscode-front-matter/blob/main/l10n/bundle.l10n.de.json
