### ISSUE TITLE
Issue: comma separated arrays

### ISSUE THREAD

**Issue by HareToAme** [estruyf/vscode-front-matter#601]
**Describe the bug**
I need to use comma separated arrays in front matter.
```yaml
---
test: ["a", "b"]
---
```
But it is automatically formatted as
```yaml
---
test:
  - a
  - b
---
```
I tried the following settings
```json
"frontMatter.taxonomy.commaSeparatedFields": [
    "test"
]
```
However, it is automatically formatted as
```yaml
---
test: a, b
---
```
but what I actually need is
```yaml
---
test: ["a", "b"]
---
```
Is there any way to solve this problem?

**Desktop (please complete the following information):**
 - OS: Windows 11
 -  VSCode 1.79.2
 - Front Matter v8.4.0

**Comment by estruyf** [comment]
@HareToAme Unfortunately this is not possible, internally we use a dependency that converts JSON to YAML and it does not support single-line arrays.

**Comment by HareToAme** [comment]
Thanks for your answer.
