### ISSUE TITLE
Feedback: Hugo with partial content in modules vs. Dashboard

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#602]
Hi. I have a Hugo website and recently moved out a certain content folder (not ALL content) into a module where it is mounted via the following (config/_default/module.toml):

```toml
[[mounts]]
source = "documentation/"
target = "content/components"
```

The folder `documentation` in that module is mapped into my website's content/components folder, and Hugo does its thing with that.

What is working:
- Hugo - the folder's contents appear on the website
- single content file editing with Frontmatter - the frontmatter sidebar is there and working

What is not working:
-  the posts/pages from the mounted folder do not appear on the dashboard. 

My configuration is scattered into folders, and the content folder config is this:

```json
{
  "$schema": "https://frontmatter.codes/config/content.pagefolders.schema.json",
  "title": "Components",
  "path": "[[workspace]]/../hugo-modules/documentation",
  "contentTypes": ["component"]
}
```

I tried various path values (`[[workspace]]/documentation`, `[[workspace]]/content/components`, etc) with no luck.

My workspace looks like this:

|
|-[kollitsch.dev](https://github.com/davidsneighbour/kollitsch.dev) (the website folder, also containing the workspace configuration)
|-[hugo-modules](https://github.com/davidsneighbour/hugo-modules) (folder with the module(s)
|-[hugo-theme](https://github.com/davidsneighbour/hugo-theme) (another module with the theme)

To test this you can clone the three repos into a folder next to each other, then open the workspace inside of kollitsch.dev.

It appears that `[[workspace]]` is relative to the location where the configuration is saved, not the "actual" workspace (one level above). 

Is there any way to configure the content module into the dashboard using a relative path?

**Comment by estruyf** [comment]
Hi @davidsneighbour, FM did not support this yet as it uses the workspace folder in which you added the `frontmatter.json` file.

A change is coming up to locate files outside the workspace folder. So if you use `"[[workspace]]/../hugo-modules/documentation"`, it should correctly concat the file path to the absolute folder path.

**Comment by estruyf** [comment]
I pushed out an update, let me know if it works in the latest beta.

**Comment by davidsneighbour** [comment]
I will need to verify if I messed up my configuration, but it now shows a "no markdown to 
 show" error. 

![Selection_013](https://github.com/estruyf/vscode-front-matter/assets/83281/a9623d93-7b87-43fd-ad22-0d10591f36b6)

**Comment by estruyf** [comment]
This is how it shows up on my end (filter on `components`).

![image](https://github.com/estruyf/vscode-front-matter/assets/2900833/bed7497d-98da-436c-9961-f17fef78a92a)

**Comment by estruyf** [comment]
It seems to be an issue on Windows. 🫣

**Comment by davidsneighbour** [comment]
No, on Linux then ;) I am on Ubuntu.

**Comment by davidsneighbour** [comment]
Perfect, all working  :)
