### ISSUE TITLE
Enhancement: Matching Dashboard colors with current vs code theme

### ISSUE THREAD

**Issue by Royal-lobster** [estruyf/vscode-front-matter#605]
It would be great if the front matter dashboard colors match with current theme of vs code

**Comment by estruyf** [comment]
This is possible in our experimental mode: https://frontmatter.codes/docs/experimental#enable-experimental-features

In 8.5.0 it will be enabled by default.

**Comment by Royal-lobster** [comment]
Ohh thanks a lot, its what i was looking for !
