### ISSUE TITLE
Issue: Documentation for "Start server" command missing

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#608]
Trying to change the command to start the local server fails because it seems to be undocumented. [According to the docs](https://frontmatter.codes/docs/panel#global-settings) it was in the Global Settings menu, which is hidden by default now. It is however nowhere documented that the specific config variable for the start server command is

```
"frontMatter.framework.startCommand": "npm run server",
```

There might be more config parameters that are missing

**Comment by estruyf** [comment]
The setting has been added to the documentation, and the `Global Settings` panel section has been updated.
