### ISSUE TITLE
Feedback: changing a script requires restart of vscode

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#612]
I have a custom script configured in `.frontmatter/config/custom/scripts/youtube.json`:

```json
{
  "$schema": "https://frontmatter.codes/config/custom.scripts.schema.json",
  "title": "Generate social image for Youtube",
  "script": "./.frontmatter/scripts/create-youtube-header-image.js",
  "command": "~/.config/nvm/versions/node/v20.4.0/bin/node",
  "type": "content"
}
```

Changing the value of command was not recognized on repeated attempts until I closed and re-opened VSCode.

I tried:
- closing/reopening the sidebar
- closing the dashboard tab
- closing, reopening the file that this script runs on

I probably could have disabled and reenabled the plugin to the same effect as restarting the IDE. 

If that is by design, ok. It might be a bug though or you might be able to somehow watch and reload something that happens in one of the config folders?

**Comment by estruyf** [comment]
I just did some tests, and by default, there is a file listener for saving events. When you save a config file, there should be a reload of the configuration happening.

You can also check this in the output of VSCode:

![image](https://github.com/estruyf/vscode-front-matter/assets/2900833/86756a16-8e4e-4f97-a8d4-98453362de5e)

Can you verify this on your end? It would be helpful to know what is getting logged.

**Comment by davidsneighbour** [comment]
Just saw that answer, sorry. I'll check tomorrow.
