### ISSUE TITLE
Feedback: Is there any way that let me to custom prefix for new content file name?

### ISSUE THREAD

**Issue by 100gle** [estruyf/vscode-front-matter#613]
Now the default file name for new content is `{{year}}-{{month}}-{{day}}-{{title}}`.

```
2023-08-01-FrontMatter-Crash-Course.md
```

But I wanna custom prefix just like `{{year}}{{month}}{{day}}-{{title}}` when new content be created.

```
20230801-FrontMatter-Crash-Course.md
```

Is there any way let me to do that?

**Comment by estruyf** [comment]
You can change the prefix for the file creation on page folder or content-type level. You can find more about it here: https://frontmatter.codes/docs/content-creation/additional-config#file-prefixes

**Comment by 100gle** [comment]
> You can change the prefix for the file creation on page folder or content-type level. You can find more about it here: https://frontmatter.codes/docs/content-creation/additional-config#file-prefixes

Thanks for the help!
