### ISSUE TITLE
Issue: Content filter for external content not working

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#616]
**Describe the bug**
Around #602, the filtering of the external post types stopped working. Post types with `../` in their path won't appear.

Sample config:

```json
{
  "$schema": "https://frontmatter.codes/config/content.pagefolders.schema.json",
  "title": "Components",
  "path": "[[workspace]]/../hugo-modules/documentation",
  "contentTypes": ["component"]
}
```

**To Reproduce**
1. Clone [kollitsch.dev](https://github.com/davidsneighbour/kollitsch.dev), [hugo-modules](https://github.com/davidsneighbour/hugo-modules), and [hugo-theme](https://github.com/davidsneighbour/hugo-theme) into the same folder next to each other
2. Load the workspace via kollitsch.dev/kollitsch-dev.workspace
3. Check the Frontmatter Dashboard
4. set "Showing" filter to anything other than "components" < the posts group is loaded
5. set "Showing" filter to "components" < the last selection stays visible

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser Chrome latest
 - VSCode and Plugin are on the latest versions (not preview or beta)

**Comment by estruyf** [comment]
Found the issue and got it fixed.
