### ISSUE TITLE
Issue: frontMatter.taxonomy.indentArrays = false has no effect

### ISSUE THREAD

**Issue by steelcoder** [estruyf/vscode-front-matter#629]
**Describe the bug**
Setting the configuration `"frontMatter.taxonomy.indentArrays": false` in order to remove the indentation of arrays within the front matter does not seem to have the desired effect. When trying to maintain a list without indentation, the software keeps re-indenting the list upon changes to other fields.

**To Reproduce**
1. Configure the software with `"frontMatter.taxonomy.indentArrays": false`.
2. Create or modify a front matter section with a list, e.g.:
```
keywords:
  - word 1
  - word 2
```
3. Change a different field within the same front matter, such as `slug`.
4. Observe that the previously unindented list (`keywords` in this example) gets indented automatically.

**Expected behavior**
The list under `keywords` or any other taxonomy should remain unindented when `frontMatter.taxonomy.indentArrays` is set to `false`, regardless of changes to other fields.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS: macOS
- Version: 13.5 (Apple Silicon)

**Additional context**
v.8.4.0

**Comment by estruyf** [comment]
The library we use for parsing YAML uses a new option for this. I just updated it, and you can try it in the latest beta version.
