### ISSUE TITLE
Issue: customTaxonomy displays shows wrong additional entries from the posts in dashboard

### ISSUE THREAD

**Issue by kristofzerbe** [estruyf/vscode-front-matter#633]
**Describe the bug**
After introducing following custom ``customTaxonomy``, the TAXONOMY view on the dashboard displays additional, wrong one-char-entries (see screenshot):

```
  "frontMatter.taxonomy.customTaxonomy": [
    {
      "id": "series",
      "options": [
        "A New Blog",
        "Discoveries",
        "Great Finds",
        "Golem",
        "IndieWeb",
        "Lightroom Presets",
        "Step By Step",
        "SV Wehen Wiesbaden"
      ]
    }
  ]
  ...
  "frontMatter.taxonomy.contentTypes": [
    {
    "name": "default",
    "pageBundle": false,
    "fields": [
      ...
      {
        "title": "Series",
        "name": "series",
        "type": "taxonomy",
        "taxonomyId": "series"
      },
      ... 
    ]
  ]
```

![image](https://github.com/estruyf/vscode-front-matter/assets/243113/d8b82d48-349d-4bed-956d-08a9ac3c3f1e)

I have checked all my posts for invalid Front Matter and tried to put quotes around the SERIES entry, where my default Front Matter doesn't use quotes. I also have tried to configure ``noPropertyValueQuotes``, but this doesn't help either:

```
  "frontMatter.taxonomy.noPropertyValueQuotes": [
    "series"
  ]
```

**To Reproduce**
1. Clone https://github.com/kristofzerbe/kiko.io
2. Open dashboard
3. Switch to Taxonomies View

I can reproduce the behaviour on 2 Windows 10 machines locally (Front Matter v9.1.5938539-beta BETA) and on gitpod.com within a virtual Linux environment (Front Matter v9.0.0).

**Comment by kristofzerbe** [comment]
Ah ... because not all of my posts have a SERIES! Thnx for your upcoming fix :)

**Comment by estruyf** [comment]
> Ah ... because not all of my posts have a SERIES! Thnx for your upcoming fix :)

No, because you use the `series` field as a string, instead of an array (what FM expects). ☺️
