### ISSUE TITLE
Issue: UI themes make some links hard to discover or see

### ISSUE THREAD

**Issue by scottsweb** [estruyf/vscode-front-matter#635]
**Describe the bug**
Now that Front Matter CMS supports the same theme as VSCodium things look great, but some links are not visible until you hover over them, or hide when you hover over them.

**To Reproduce**
1. Install the Nord colour theme for your editor: https://open-vsx.org/extension/arcticicestudio/nord-visual-studio-code or https://marketplace.visualstudio.com/items?itemName=arcticicestudio.nord-visual-studio-code
2. Enable Front Matter CMS
3. Interact with the UI

**Expected behavior**
All links should be visible.

**Screenshots**
![Kapture 2023-08-25 at 12 48 33](https://github.com/estruyf/vscode-front-matter/assets/411945/2531a170-c579-4f31-b059-ba66489559f3)

**Desktop:**
 - OS: `Mac OS 13.5`
 - Browser: `VSCodium`
 - Version: `1.81.1`
 - Front Matter: `9.0.0`

**Comment by estruyf** [comment]
Thanks this got fixed in the latest beta of 9.1.0.
