### ISSUE TITLE
Issue: Media browser lightbox transparency

### ISSUE THREAD

**Issue by scottsweb** [estruyf/vscode-front-matter#636]
**Describe the bug**
This might be related to my bad choice of theme: #635 

When browsing and previewing media in the library, the lightbox is semi-transparent make it hard to see the image clearly. Some images also have a background image bleed through in the thumbnail list.

**To Reproduce**
1. Go to 'Media'
2. Click on an image
3. The image in the light box is transparent
4. With small or transaprent images, sometimes the background image can be seen in grid view

**Expected behavior**

For media to be clearly visible.

**Screenshots**
 
<img width="321" alt="Screenshot 2023-08-25 at 12 58 43" src="https://github.com/estruyf/vscode-front-matter/assets/411945/3428f25e-f917-4f7d-9637-91f0563fc6b2">

<img width="1903" alt="Screenshot 2023-08-25 at 13 02 53" src="https://github.com/estruyf/vscode-front-matter/assets/411945/ca0b6872-cde2-4c4f-868f-98ea5eb91197">

**Desktop:**
 - OS: `Mac OS 13.5`
 - Browser: `VSCodium`
 - Version: `1.81.1`
 - Front Matter: `9.0.0`

**Comment by estruyf** [comment]
Thanks this got fixed in the latest beta of 9.1.0.

**Comment by scottsweb** [comment]
Thanks!
