### ISSUE TITLE
_drafts folder like Jekyll for Hexo

### ISSUE THREAD

**Issue by kristofzerbe** [estruyf/vscode-front-matter#638]
In the doc there is pointed out, that Jekyll users don't need the ``draftField``:

> Important: If you use Jekyll, you do not have to use the draft field, as Front Matter supports the _drafts, _posts folders and collections from Jekyll. If you use Jekyll, make sure to set the frontMatter.framework.id setting to jekyll.

Hexo works also with ``_posts`` and ``_drafts``, therefore it would be helpful, if ``"frontMatter.framework.id": "hexo"`` is set, no ``draftField`` configuration would be needed anymore.

**Comment by estruyf** [comment]
Thanks @kristofzerbe for the information! I will do some tests and work out a similar approach in Hexo.

**Comment by estruyf** [comment]
I have been working on this, and better Hexo support is now. It starts with the initialization:

<img width="928" alt="image" src="https://github.com/estruyf/vscode-front-matter/assets/2900833/59a9e88c-5377-4b3e-9c19-29218b2dcd8e">

The same logic for the `draft` status as Jekyll has been implemented.

<img width="1212" alt="Xnapper-2023-09-13-14 36 26" src="https://github.com/estruyf/vscode-front-matter/assets/2900833/3d76d3d4-0288-425c-83e6-e53d7058a9cb">

You'll be able to test it out in the latest beta version

**Comment by kristofzerbe** [comment]
Works like a charm in v9.3.6172561-beta. No additional attribute anymore ... \o/

![image](https://github.com/estruyf/vscode-front-matter/assets/243113/2de361ed-61b2-415b-b62a-8d83100df2d0)

Don't know if it has something to do with this change regarding Hexo: The dashboard crashes on hitting the reload button. I have open up a new issue on that: https://github.com/estruyf/vscode-front-matter/issues/664

Thnx
