### ISSUE TITLE
Showcase: 

### ISSUE THREAD

**Issue by palmiak** [estruyf/vscode-front-matter#656]
**Title you want to give your site**

Using the Front Matter CMS with Elio Struyf

**Link to the site**

https://www.youtube.com/watch?v=YX4HBXHojOA

**A nice and clean description**

A video of a Code and Coffee Show about the Front Matter CMS

**Comment by estruyf** [comment]
Thanks @palmiak - it has been added to the showcase page - https://frontmatter.codes/showcase
