### ISSUE TITLE
Issue: The start server command for the Next template failed to execute. nuxt should add the 'dev' command

### ISSUE THREAD

**Issue by Ahidada** [estruyf/vscode-front-matter#665]
**Describe the bug**
The start server command for the Next template failed to execute.
nuxt should add the 'dev' command

**To Reproduce**
1. Go to 'init nuxt template'
2. Click on 'Start server'

**Expected behavior**
The command was successfully executed.

**Screenshots**
Command execution failed

**Desktop (please complete the following information):**
 - OS: Mac
 - Version 9.2.0

**Comment by estruyf** [comment]
Thanks @Ahidada for opening this issue. It should be fixed in the latest beta and will be added to version `9.3.0`.
