### ISSUE TITLE
Enhancement: Ability to extend media file metadata by defining custom fields

### ISSUE THREAD

**Issue by polynook** [estruyf/vscode-front-matter#666]
**Is your feature request related to a problem? Please describe.**

I like to store captions with images and videos. Then, I use media snippets to insert a custom React component and set the caption value accordingly using placeholders.

Videos, however, do not have a caption field.

![Code_2023-09-16_20-33-17](https://github.com/estruyf/vscode-front-matter/assets/71569839/5c788249-7393-49c4-8fe4-d937f2969b87)

Here are a couple use cases where custom metadata is desirable:
- I have an image that displays an art piece created by another person. In this image's metadata, I'd like to store the name of this person and a link to their webpage. Then, wherever I reuse this image, I can insert this data into the markup of my custom snippet via placeholders as a form of attribution.
- Store a small generated Base64 encoded image string that can be used to display in-place of an image while it is loading.

**Describe the solution you'd like**
Ability to define [fields](https://frontmatter.codes/docs/content-creation/fields) on media files so that custom metadata could be attached.

This could be implemented similar to [content types](https://frontmatter.codes/docs/content-creation/content-types). where we could define our own media content types (e.g., image, generalVideo, courseVideo, textFile, etc.) and attach custom metadata to each type.

For the "image's author name and link" metadata example above, this could be a key-value pair field, or a contentRelationship field, where the metadata would be linked to a [data file](https://frontmatter.codes/docs/datafiles-view).

**Describe alternatives you've considered**
I considered storing caption text in the title field of a video but it feels hacky and would not be helpful if additional metadata needed to be attached.

**Comment by estruyf** [comment]
Thanks @polynook; this is a great idea.

How would you like to set the content type for a media file? For instance, you have two images, one of the author, and one just an image for adding to your article. Both of these images are PNGs. How would you see the CMS selecting the right content type, or would it be an option to allow you to pick the content type from a dropdown first?

**Comment by estruyf** [comment]
As this is a more significant task, I have created another task in which I have handled to show the caption field for video files: https://github.com/estruyf/vscode-front-matter/issues/669

**Comment by polynook** [comment]
This is how I envision this:

All images, videos (and other media files supported by Front Matter) uploaded to Front Matter would automatically have assigned a default `media content type` defined internally in Front Matter. Example for image:

```json
{
    "name": "Image",
    "fields": [
        {
            "title": "Title",
            "name": "title",
            "type": "string",
            "required": false
        },
        {
            "title": "Caption",
            "name": "caption",
            "type": "string",
            "required": false
        },
        {
            "title": "Alt text",
            "name": "altText",
            "type": "string",
            "required": false
        },
    ],
    // A regex pattern or some other algorithm for Front Matter to recognize which media fiels are images.
    "fileType": "/(.*\.(?:png|svg|webp|avif))/",
}
```

Optionally, if a user desires, they could override this content type for any image.

Custom `media content type` defintion in `frontmatter.json`:

```json
"frontMatter.taxonomy.mediaContentTypes": [
    {
        "name": "Image",
        "fields": [
            {
                "title": "Title",
                "name": "title",
                "type": "string",
                "required": false
            },
            {
                "title": "Caption",
                "name": "caption",
                "type": "string",
                "required": false
            },
            {
                "title": "Alt text",
                "name": "altText",
                "type": "string",
                "required": true
            },
            {
                "title": "Blurred Placeholder",
                "name": "blurredPlaceholder",
                "type": "string",
                // i.e. the value generated and set by a media script and should not be editable by hand by a user in the UI
                "editableInUI": false
            },
            // A new field that would allow defining key-value pairs
            {
                "title": "Authors",
                "name": "authors",
                "type": "map",
                "key": {
                    "title": "Name",
                    "name": "name",
                    "type": "string",
                    "required": true
                },
                "value": {
                    "title": "URL",
                    "name": "url",
                    "type": "string",
                    "required": true
                },
            },
            {
                "title": "Tags",
                "name": "tags",
                "type": "tags"
            },
        ],
        // Define this media content type only for PNG images. This means that inside Media view, only PNG files would be able to be converted to this media type.
        "fileType": "/(.*\.(?:png))/",
    }
]
```

Then, in the Media view, we could select one or more images and assign a custom `media content type` to them. Then, when editing their metadata, we would see our own custom fields there instead of the default ones.

Then, I can use a media snippet to insert an image component into an MDX file:

```json
"frontMatter.content.snippets": {
    "Image": {
      "description": "Custom Image",
      "body": [
        "<Figure>",
        "    <Image src=\"[[&mediaUrl]]\" alt=\"[[alt]]\" placeholder=\"[[placeholder]]\" />",
        "    <Caption>",
        "        [[caption]]",
        // authors.key and authors.value would be values from the selected key-value pair inside the UI when adding media snippet to content.
        "        <Author name=\"[[authors.key]]\" url=\"[[authors.value]]\" />"
        "    </Caption>",
        "</Figure>"
      ],
      "isMediaSnippet": true
    }
}
```

In this implementation, a user could choose manually which images (or other media files) should belong to a specific `media content type`.

When inserting this image into content, the user wouldn't be able to choose which `media content type` they wish to insert, because otherwise, stored metadata associated with the previous `media content type` would be lost.

The workflow would essentially be this:
1. User needs to attach custom metadata to a media file that they store inside Front Matter public media folder (image, video, text file, `.ts` script, etc.).
2. User defines `custom media type` with relevant fields for required metadata.
3. In Media viewer, user selects the files they wish to have this custom metadata. Not every image file may need to have custom metadata, so the user selects only a few images he want to have this custom metadata and assigns them to use their custom defined `media content type`. Not selected image files are unaffected and still remain using the default media type.
4. User clicks on the pencil icon on the selected image to edit its metadata and sees their custom defined fields.

**Comment by estruyf** [comment]
Thanks @polynook for your insights!

**Comment by estruyf** [comment]
WIP

- [ ] Create `frontMatter.media.contentTypes` setting
- [ ] Show the media files according to the content type
- [ ] Show the input form for the media metadata based on the content type
- [ ] Allow snippets to use the new fields
- [ ] Allow to extend the configuration with the new setting
- [ ] Allow to spit the configuration (check if correctly merged)
- [ ] Update the documentation
