### ISSUE TITLE
Issue: Media search does not find files when searching from a page other than the first

### ISSUE THREAD

**Issue by polynook** [estruyf/vscode-front-matter#668]
**Describe the bug**
When there is more than one page in Media browser, the search finds files only when searching while being on page 1. If I go to any other page and search from there, no files from other pages are found.

https://github.com/estruyf/vscode-front-matter/assets/71569839/4386c1a9-16c3-4ccc-a8d4-38e27f99458c

**To Reproduce**
1. Have enough media files so that there is more than one page.
2. Go to any page but the first.
3. Type into the search bar something to find media files in other pages.
4. No results are found.

**Expected behavior**
Search should work regardless of what page a user is on.

**Comment by estruyf** [comment]
Thank you @polynook for opening this issue. Found the issue and fixed it in the latest beta.
