### ISSUE TITLE
Enhancement: Allow the `frontmatter.json` config to live in a sub-folder

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#676]
As some want to keep the root of their project clean, it would be helpful to allow the `frontmatter.json` file to live within a subfolder.

> **Important**: for workspaces, it would be advised to keep the `frontmatter.json` file in the root of the SSG project as it is used for Front Matter to know the start location.

**Comment by n-arakawa** [comment]
In this context, hope to
 - ’frontMatter.content.pageFolders’ can be relative to this sub-folder(ｗhere frontmatter.json is located)
 - Server（e.g. `hugo`) start at this sub-folder

```
worskpace/
└── doc
    ├── content
    ├── frontmatter.json
    └── hugo-config.toml
```

**Comment by estruyf** [comment]
@n-arakawa, I see that you are using a workspace. Currently, that is not supported, as the extension will search for the `frontmatter.json` file to decide where the SSG project is located. Looking through sub-folders of all workspace folders complicates it a bit or could end up using the wrong folder. More work is required for that. 

Feel free to open another issue for this kind of enhancement if you want to get it in the product.

**Comment by n-arakawa** [comment]
Thank you for your answer.
I may have confused 
 - SSG project
 - VScode workspace
 - git repository

**Comment by estruyf** [comment]
Sorry, @n-arakawa, now I got confused too, could you share your project repository its folders, and where in the structure the `frontmatter.json` file is located?

**Comment by n-arakawa** [comment]
Sorry for my poor explonation.
In this case I do not use `VScode workspace.`
The folder name "workspace" in the previous post is incorrect.

I have a git repository (`repo1`) and a documentation subdirectory (i.e. `hugo-doc`).

```
repo1/
└── hugo-doc
    ├── config.toml
    ├── content
    │   └── post
    │       └── first_post.md
    ├── frontmatter.json
```


When I start `code repo1/hugo-doc`, `frontmatter` works fine.
However if I say `code repo1`
 - Cannot find `content` directory. This is because `content` must exist directly under `[[workspace]]`.
 - Cannnot start hugo server. This is because hugo server start at `[[workspace]]` and there is no hugo config(`config.toml`)

I hope to:
 - Set "content" relative to "frontmatter.json"
 - Start hugo server in `frontmatter.json` directory


frontmatter.json
```
{
  "$schema": "https://frontmatter.codes/frontmatter.schema.json",
  "frontMatter.framework.id": "hugo",
  "frontMatter.content.publicFolder": "static",
  "frontMatter.preview.host": "http://localhost:1313",
  "frontMatter.content.pageFolders": [{
    "title": "content",
    "path": "[[workspace]]/content",
    "previewPath": "/{{pathToken.relPath}}/",
    "contentTypes": ["post"]
  }],
  "frontMatter.taxonomy.dateFormat": "yyyy-MM-dd",
  "frontMatter.framework.startCommand": "hugo server -D"
}
```

**Comment by estruyf** [comment]
Thank you, @n-arakawa. This clarifies it.

Front Matter is intended to start from the root project folder or a VS Code Workspace, where it will look for the folders where it can find the `frontmatter.json` file.

As you are opening it one level up and not using a VS Code Workspace, these checks are not passed, and that is why the `[[workspace]]` path will be `/repo1`.

I'm unsure of the best approach to support your use case, as it would complicate the logic of getting to know the start location.

**Comment by n-arakawa** [comment]
I understand that it's difficult to accommodate my use case.
In the short term, I'll disable FrontMatter in the repo1 workspace to suppress`Folder "${folder.title} (${folder.path})" does not exist. Please remove it from the settings.` notifications.

**Comment by n-arakawa** [comment]
@estruyf 
> is that because there are more folders in it that you want to work with?

yes. My "repo1" is not just a documentation project, it's a software project in itself. I plan to manage the documentation part of the project with vscode-front-matter.

**Comment by estruyf** [comment]
What holds you from creating a VS Code Workspace? That way, you could open `repo1` as a workspace with all the folders.

**Comment by n-arakawa** [comment]
Thank you for your advice!
This can be a good solution when there are no  top-level plain files.

**Comment by n-arakawa** [comment]
Thank you for your advice!
Creating a workspace with two folders "repo1" and "repo1/hugo-doc" seems to solve the problem.
