### ISSUE TITLE
Enhancement: Scheduled posts

### ISSUE THREAD

**Issue by perragnar** [estruyf/vscode-front-matter#688]
I schedule posts on my website by setting the date to a future date. It's hard to see scheduled posts in the dashboard.
It would be nice to be able to see scheduled posts in the dashboard with a Scheduled status badge and be able to list and group them.

<img width="1434" alt="Screenshot 2023-10-12 at 10 55 45" src="https://github.com/estruyf/vscode-front-matter/assets/1774047/5d110c0d-8ddb-4333-a6c9-93b13ba4e948">

**Comment by estruyf** [comment]
Thanks @perragnar! This is a great suggestion!

**Comment by estruyf** [comment]
@perragnar I have added the enhancement to the latest beta version. It will work in combination with the default `draft` field where a check is implemented when it isn't in the draft, and the date is in the future; the label will be set to `scheduled`.

<img width="1504" alt="Xnapper-2023-10-19-16 03 51-5FA6F413-7416-49F3-9C46-DF47657433EA" src="https://github.com/estruyf/vscode-front-matter/assets/2900833/0b0218aa-50e5-4d39-90c5-e81d6f4be5e8">

There will be a new `scheduled` tab as well + grouping on draft/published will add the scheduled group as well.

Feel free to try it and let me know how it works.

**Comment by perragnar** [comment]
That's awesome! Will try it out more later but it looks great. Thanks!

<img width="1756" alt="Screenshot 2023-10-19 at 16 50 47" src="https://github.com/estruyf/vscode-front-matter/assets/1774047/4c8ba4c6-6ca5-4e3f-acd6-7246ca35309f">
