### ISSUE TITLE
Feedback: Missing text in a translation

### ISSUE THREAD

**Issue by gsegit** [estruyf/vscode-front-matter#693]
Hi there ;D
I noticed that the translation of the text (see screenshot) is not quite complete. I looked in the bundle json file and didn't find the text there either. 
Can you fix that ? ;D
![frontmatterpanelfolderregristrieren](https://github.com/estruyf/vscode-front-matter/assets/104396251/2f667c95-72da-4385-a010-ad3bbc6ccad4)

That is the button for the create content

**Comment by estruyf** [comment]
That is correct; localization has been included in the webviews, but still, these prompts and notification messages have to be localized too.

**Comment by estruyf** [comment]
All the frontend and backend strings are now localized in the latest beta version. Feel free to verify as it should solve this issue as well.
