### ISSUE TITLE
Feedback: Problem by create from the content

### ISSUE THREAD

**Issue by gsegit** [estruyf/vscode-front-matter#694]
Hello ;D
I noticed a small problem when creating an article for the first time. If I want to create a first article, I have to register the folder. When I start the server, the Hugo server starts in the folder of the workspace folder. I don't know, but is it possible that I'm doing something wrong?

Have a nice Day ;D

**Comment by estruyf** [comment]
Hi @gsegit, I just included a check when you use workspaces. When that is the case, the terminal will start from the workspace folder, which contains the `frontmatter.json` file.

**Comment by gsegit** [comment]
Hi there 
At first, thanks for you work and read my feedback, is little bit difficult for, english is not my mother language and i hope make not so big gramatik fouls lol
Well, i will test the nightly version and make feedack.

Have a nice day 😀
