### ISSUE TITLE
Issue: isStarted flag inherited when   `"terminal.integrated.enablePersistentSessions": true`

### ISSUE THREAD

**Issue by n-arakawa** [estruyf/vscode-front-matter#696]
**Describe the bug**
isStarted flag inherited between vscode session when   `"terminal.integrated.enablePersistentSessions": true`
Therefore dashboard  gui shows 'stop server' at start time.

**To Reproduce**
- set `vscode` config   `"terminal.integrated.enablePersistentSessions": true`
- start server via frontmatter dashboard
- stop `vscode`
- restart `vscode`
  

**Expected behavior**

isStarted flag  should be `false` when  `vscode` starts.

**Desktop (please complete the following information):**
 - OS: Ubuntu2304

**Additional context**
frontmatter: v9.3.0
VSCODE: 1.83.1

**Comment by estruyf** [comment]
Implemented the fix for this and it is testable in the latest beta version.

**Comment by n-arakawa** [comment]
![Screenshot from 2023-10-26 16-32-08](https://github.com/estruyf/vscode-front-matter/assets/2455518/d9a62dac-f9ed-46f9-96dc-75e984fae19a)

My screen shot just after restart VScode and open frontmatter dashboard.

"* History Retorted" may do some something tricky.

**Comment by estruyf** [comment]
Thanks, this will indeed be handled by this change in the beta version.
