### ISSUE TITLE
Couldn't find message for key setting.frontMatter.panel.actions.disabeld.markdownDescription.

### ISSUE THREAD

**Issue by dylan-k** [estruyf/vscode-front-matter#697]
In the VsCode Shared Output panel, there's a warning message repeated frequently: 

`[warning] [vscode-front-matter]: Couldn't find message for key setting.frontMatter.panel.actions.disabeld.markdownDescription.`

**To Reproduce**
1. Open a project that uses Front Matter in VsCode
2. View Output, Select "Shared"
3. Log of shared output messages shows `[warning] [vscode-front-matter]: Couldn't find message for key setting.frontMatter.panel.actions.disabeld.markdownDescription.` repeated

**Expected behavior**
Ideally, this warning would not appear. It could be more clear how to resolve it?

**Screenshots**
![2023-10-26 13_33_30-Window](https://github.com/estruyf/vscode-front-matter/assets/2204716/d865189a-05c0-4c00-a1ab-78ab0a8e9ae3)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode Version 1.83.1
 - Front Matter Version 9.3.0

**Comment by dylan-k** [comment]
Here's what the setting looks like with that name. Does this look right?

![2023-10-26 13_43_11-Window](https://github.com/estruyf/vscode-front-matter/assets/2204716/b6cdf471-a0e1-4dbb-8670-cc312599f488)

**Comment by estruyf** [comment]
Fix is coming out in v9.3.1
