### ISSUE TITLE
Issue: Material Theme has bright red lines

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#699]
**Describe the bug**
I am not a big theme buff, but today I thought "let's install a theme" and after I installed the  ["Community Material Theme Darker High Contrast"](https://github.com/material-theme/vsc-community-material-theme) all lines in the FM Dashboard were bright red.

![Selection_003](https://github.com/estruyf/vscode-front-matter/assets/83281/deb014ba-21a7-4ff0-b1b0-3e51c20f3d38)

This clashes with the turquoise of FM. Restarting didn't change anything. Changing back to the normal theme fixes it. Thus ends my journey into VSCode themes. 

I could not find anything else being of this color in the theme.

I am not sure if this is a bug as in those borders taking their color value from different settings in specific themes or if this is just something people who like themes (not me) have to live with.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Latest non-beta FrontMatter

**Comment by estruyf** [comment]
The color is coming from the theme you've selected, in this case, the border of some element for the `Community Material Theme Darker High Contrast` is set to red.

I will do a change to another border color variable, which will fix the issue for the theme and other themes should not be impacted by it.

**Comment by estruyf** [comment]
@davidsneighbour available for testing in the latest beta.

**Comment by davidsneighbour** [comment]
Yes, looking good. Thanks.
