### ISSUE TITLE
Issue: Front Matter fails to create content

### ISSUE THREAD

**Issue by polynook** [estruyf/vscode-front-matter#701]
**Describe the bug**
Creating new content from within Front Matter fails. 

**To Reproduce**
1. Install Front Matter BETA `v9.4.6736196`
2. CTRL+SHIFT+P -> Front matter: Create new content
3. Fill out the prompts
4. Nothing happens — content is not created.

**Expected behavior**
Content should be created.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Front Matter BETA `v9.4.6736196`

**Additional context**
Last working BETA version `v9.4.6691219`

**Comment by estruyf** [comment]
Thanks @polynook this is related to an upcoming change for the `contentRelationship` good you reported it. I have implemented the fix.
