### ISSUE TITLE
Issue: cannot run on local after installing with pnpm

### ISSUE THREAD

**Issue by Balastrong** [estruyf/vscode-front-matter#708]
**Describe the bug**
Running the app on local throws an error:
```
[webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options.client.overlay has an unknown property 'runtimeErrors'. These properties are valid:
   object { errors?, warnings?, trustedTypesPolicyName? }
 ELIFECYCLE  Command failed with exit code 2.
 ELIFECYCLE  Command failed.
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:9000/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.0.129:9000/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:9000/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/leonardo/PersProgetti/vscode-front-matter/public' directory
<i> [webpack-dev-server] Gracefully shutting down. To force exit, press ^C again. Please wait...
ERROR: "watch:panel" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.
```

**To Reproduce**
1. Clone the repo
2. Run `pnpm i`
3. Run `pnpm dev:ext`

**Expected behavior**
The app starts running

**Desktop (please complete the following information):**
 - OS: MacOS 14.0

**Comment by estruyf** [comment]
Hey @Balastrong ☺️, happy to see you here. Can you try from a `npm i`? `pnpm` might be a bit outdated as another contributor provided it. I might need to keep it in sync again.

**Comment by Balastrong** [comment]
Heya! Tried now with npm and worked fine :D

I'd say we should update the docs to recommend using npm then. Probably also decide if we should support two different package managers or just one, but that's another topic :)

**Comment by estruyf** [comment]
Good to know; npm has always worked for me, so it might be good to keep on that path.

**Comment by estruyf** [comment]
Reverted the contribution docs to `npm`.
