### ISSUE TITLE
Bug report: Transliteration error in action Optimise slug

### ISSUE THREAD

**Issue by Aharito** [estruyf/vscode-front-matter#711]
**Describe the bug**
The 'ь' character is not transliterated by click the Optimise slug, despite it presented is in the `vscode-front-matter/src/constants file
/charMap.ts` [here](https://github.com/estruyf/vscode-front-matter/blob/f4816afa6599581751449b51d4fc2ac3be1a58dd/src/constants/charMap.ts#L177) and [here](https://github.com/estruyf/vscode-front-matter/blob/f4816afa6599581751449b51d4fc2ac3be1a58dd/src/constants/charMap.ts#L210)

**To Reproduce**
1. Create any `.md` file in FrontMatterCMS project.
2. Initialize project
3. Goto FrontMatter Actions
4. In "Title" field write for example 'конь' (a word with the 'ь' sybmol)
5. Click to "Optimise slug" button
6. The 'slug: konь' string appears on front matter area in file

**Expected behavior**
Symbols 'ь' (lowercase) and 'Ь' (uppercase) must be transiterated as empty string ''

**Screenshots**
![image](https://github.com/estruyf/vscode-front-matter/assets/6253807/f24de563-5620-4314-9cbc-cf5b5efa41f2)

**Desktop (please complete the following information):**
 - OS: Win 10
 - VSCode Version: 1.83.0

**Comment by estruyf** [comment]
I see; that is the only character that doesn't have value. You are better suited to know if it needs a value or not. 

Does `ь` need to be replaced by another character, or should it be empty?

**Comment by estruyf** [comment]
At least the bug is fixed right now in the latest beta version.

**Comment by Aharito** [comment]
> Does `ь` need to be replaced by another character, or should it be empty?

It should be empty.

P.S. Thank for quick answer and for great FrontMatter extension!

**Comment by estruyf** [comment]
Great! Thanks for the feedback.
