### ISSUE TITLE
Issue: deleting media file in the inspector with search input resets results

### ISSUE THREAD

**Issue by polynook** [estruyf/vscode-front-matter#712]
**Describe the bug**
I couldn't come up with a better title for the issue so here is a video:

https://github.com/estruyf/vscode-front-matter/assets/71569839/6d2ab51b-854c-4b9b-9e1a-089d34d090d0

Same behavior can be observed by editing metadata and saving the changes as well.

**To Reproduce**
See video above.

**Expected behavior**
The search filter should remain active after deleting media.

**Comment by estruyf** [comment]
A video is more than enough. Thanks! Found the issue and it gets fixed in the upcoming beta.
