### ISSUE TITLE
Clicking on a taxonomy count from the Taxonomies tab does not filter the contents overview

### ISSUE THREAD

**Issue by Balastrong** [estruyf/vscode-front-matter#714]
**Describe the bug**
When you click on a taxonomy count and get redirected to the overview there is no tag filter - all items are displayed

![image](https://github.com/estruyf/vscode-front-matter/assets/7253929/5545bc5b-5f7d-4c22-b96e-6d187b371990)

**To Reproduce**
1. Go to the Taxonomies tab
2. Click on a number

**Expected behavior**
I was expecting the articles to be filtered by the taxonomy I just clicked on the previous screen.

**Additional context**
I had a look at the code and I noticed when clicking on that number, this should happen:
https://github.com/estruyf/vscode-front-matter/blob/f4816afa6599581751449b51d4fc2ac3be1a58dd/src/dashboardWebView/components/TaxonomyView/TaxonomyLookup.tsx#L53-L55

The atom is set and so is the filter.
https://github.com/estruyf/vscode-front-matter/blob/f4816afa6599581751449b51d4fc2ac3be1a58dd/src/dashboardWebView/components/Header/Header.tsx#L132-L133

However, before the user can see the result, this happens:
https://github.com/estruyf/vscode-front-matter/blob/f4816afa6599581751449b51d4fc2ac3be1a58dd/src/dashboardWebView/components/App.tsx#L58-L65

On line 60 the path is set to `/contents` and the filter is gone. As a result, all items are displayed.

By commenting line 60 the navigation+filter works fine, but I don't know why that logic is there and if it can be removed

**Comment by estruyf** [comment]
The last code block is required when you are using the `Open media dashboard`, `Open snippets dashboard`, ... commands. It will tell the webview the correct view to open.

**Comment by estruyf** [comment]
The issue seems to be due to the `setView(<view type>);` I added in each view a couple of months ago. I will remove this, as there is no clear need for it.

**Comment by Balastrong** [comment]
Great, thanks!
