### ISSUE TITLE
Feedback: no Discord  ?

### ISSUE THREAD

**Issue by gsegit** [estruyf/vscode-front-matter#726]
Hi there ;D
I have found on your website a limk to your discord server, but i can*t found this. Is the server down or so ?

Greetings from germany and have chill holidays 🤟😎

**Comment by estruyf** [comment]
Hi @gsegit, the link should still work; it might have been a temporary issue. Could you let me know if it still happens?

https://discord.com/invite/JBVtNMsJFB

**Comment by gsegit** [comment]
Hi there ;D
Ok, I can join the Discord ;D

**Comment by gsegit** [comment]
Hi there ;D
Ok, I can join the Discord ;D
