### ISSUE TITLE
Front Matter CMS consumes 100% CPU

### ISSUE THREAD

**Issue by gkossakowski** [estruyf/vscode-front-matter#728]
Type: <b>Bug</b>

Open .astro file and start typing. The CPU will be consumed 100%.

Extension version: 9.4.0
VS Code version: Cursor 0.22.1 (20d6b2fe0f43a91764e828b77e985d1380d3ca20, 2024-01-08T23:25:28.010Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|32, 28, 25|
|Memory (System)|32.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by estruyf** [comment]
@gkossakowski, thanks for opening this issue. Can you share your configuration and a sample `.astro` file to reproduce it?

**Comment by estruyf** [comment]
Closing the issue as no feedback was given.
