### ISSUE TITLE
Issue: Metadata is overwritten with metadata from the other file when switching tabs

### ISSUE THREAD

**Issue by mayumih387** [estruyf/vscode-front-matter#734]
First of all, I appreciate this great plugin and always keep it updated!

## Describe the bug

Metadata on .md files flashes and sometimes overwrites other files' metadata.
Also, even if no change is made, the file is treated as "edited/unsaved" (unsaved circle added to the tab) when you switch the tabs.

## To Reproduce

1. Use v9.5.7529693 or later
2. Open several files
3. Swich the tabs
4. You can see 1) the metadata flashes, 2) the file status becomes "editted/unsaved", and 3) suddenly metadata is overwritten as other files metadata

## Expected behavior

- No metadata overwriting
- No flashes when switching tabs
- Treated the tab as remaining "saved" if no change is made when switching tabs

### Case: A

[Screencast from 2024-01-17 16-18-16.webm](https://github.com/estruyf/vscode-front-matter/assets/67089907/ca42c419-8d54-4900-8193-c3e2401049d7)

I just switch the tabs on this movie. (0:19) We can see that the metadata has been may suddenly inserted into frontmatter.json.

### Case: B

It can happen with other .md files, too.

[Screencast from 2024-01-17 16-45-26.webm](https://github.com/estruyf/vscode-front-matter/assets/67089907/00c6fef9-90eb-4f90-b5a9-feb14271cc28)

(0:07~) Metadata `title` is overwritten. ("My Second Post" becomes "New Beginnings" which is the `title` of the other markdown file)

We can also see that the metadata flashes every time I switch tabs.

## Desktop environment

 - OS: Fedora 39 (Workstation Edition), Linux 6.6.9-200.fc39.x86_64
 - VSCode 1.85.1 & VSCodium 1.85.1
 - Front Matter Beta v9.5.7530510 or later

## Additional context

It doesn't happen with v9.5.7529693.

It seems that some changes between v9.5.7529693 and v9.5.7530510 may affect this.

Here is the [test repository](https://github.com/mayumih387/vscode-test) if frontmatter.json is needed.

---

Thanks for your support!

**Comment by estruyf** [comment]
Thanks, @mayumih387. I have already discovered this issue. This is due to a change coming from #730. Working on a fix.

**Comment by estruyf** [comment]
Fix is being released.

**Comment by mayumih387** [comment]
Thank you!
