### ISSUE TITLE
Enhancement: configurable dashboard grid

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#737]
**Is your feature request related to a problem? Please describe.**

Recently the dashboard grid changed for some reason and became very small. On my screen I see 5 columns of cards with posts. This makes it quite small to read. I would very much prefer to have for instance 3 columns and depending on the available width 2 or one single column of cards. 

I think that maybe the dashboard started to use the full available window width of code instead of the width the dashboard itself has. Or you changed focus to showing more items. 

**Describe the solution you'd like**

It would be nice to have

- an option to set up breakpoints for width vs number of columns or
- an option to set some form of zoom value (150%) that in itself refactors the amount of columns and resizes everything on the dashboard.

Here is a quick screenshot of how it looks on my screen:

![Front Matter Dashboard - kollitsch dev (Workspace) - Visual Studio Code_001](https://github.com/estruyf/vscode-front-matter/assets/83281/f6217c10-9621-40ff-9d15-57e45bce2ebf)

**Comment by davidsneighbour** [comment]
Adding: I did CTRL+P and then searched for Zoom and came upon a zoom feature for Code. Tried "View: Reset Zoom" with no change.

**Comment by estruyf** [comment]
Thanks, @davidsneighbour, for the feedback. The grid changed indeed a couple of versions ago. The dashboard width zone became larger and allowed five items instead of four. 

Right now, it becomes a gird of five when the width is larger than 1280px. Taking your feedback into consideration, I will change this to 1500px.

**Comment by estruyf** [comment]
@davidsneighbour I have implemented what I mentioned above, and the dashboard now also uses all available widths.

Zoom for the dashboards uses the zoom from VSCode, so changing this might affect VSCode in general.

Let me know your thoughts about the implemented change (available in beta).
