### ISSUE TITLE
Enhancement: Show when the caching is not yet ready in the Content list

### ISSUE THREAD

**Issue by antoninadert** [estruyf/vscode-front-matter#741]
**Is your feature request related to a problem? Please describe.**
When doing a fresh install, in the dashboard, posts don't show up and the page acts like if there was no md file at all.
User can get confused before it starts showing again, generally after a few minutes

**Describe the solution you'd like**
Show a spinning wheel with a message like : we are loading Content data from the cache, please wait a moment.
Instead of the message "No post can be found"

**Comment by estruyf** [comment]
There is a process indicator, but we could also add something to the dashboard. Thank you for the suggestion.

![Xnapper-2024-01-24-14 20 27](https://github.com/estruyf/vscode-front-matter/assets/2900833/7b0035b5-152f-4099-bb60-63f16c06c992)

**Comment by estruyf** [comment]
A new loading message was added to the content dashboard. 

<img width="1920" alt="image" src="https://github.com/estruyf/vscode-front-matter/assets/2900833/a41b03be-61d4-41b9-bb2f-8a5d1d77f208">

**Comment by antoninadert** [comment]
That looks like a nice improvement !

Le mer. 24 janv. 2024 à 15:45, Elio Struyf ***@***.***> a
écrit :
