### ISSUE TITLE
Issue: Date field in field group (block) is always created in ISO format

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#745]
Date fields should take the date format setting or `dateFormat` property into account. Date fields in field groups are not currently stored in ISO.

![image](https://github.com/estruyf/vscode-front-matter/assets/2900833/41036676-21e6-4e93-939a-15e8a804f3df)

**Comment by estruyf** [comment]
![image](https://github.com/estruyf/vscode-front-matter/assets/2900833/c271ee4b-0758-4518-802b-6ac2e0a174d3)

**Comment by SummittDweller** [comment]
I've tested this in the beta and it's working nicely for me.
