### ISSUE TITLE
Enhancement: Filter based on the author

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#75]
Filter based on the `author` of the page.

**Comment by michaeltlombardi** [comment]
Is it possible that this and #74 might both be addressed by adding a search syntax or a UI element to the Content view to allow a user to filter pages on arbitrary metadata?

## Search Syntax

By default, the search could continue to work as it does today[^1]. With a search syntax, it could also allow you to specify a `<key>:<value>` or `<key>=<value>` (or `<key>!=<value>`) syntax or something similar to filter on metadata defined in the configuration/known by default.

If we go this route, it might be useful to have the UI filter elements operate functionally as search updates, adding the syntax they represent to the search query.

## Filter UI

For this, I think perhaps a button to bring up a modal (or that prepopulates a dropdown?) could be useful to allow users to select the key they want to filter on and then supply the value they want to use.

**Comment by estruyf** [comment]
Since version 10, filters have been configurable. You can configure the filter to use any front matter field you want and to show/hide the default ones.

More information can be found here: https://frontmatter.codes/docs/dashboard/content-view#configure-filters
