### ISSUE TITLE
Issue: Variable interpolation is not working in array/list for placeholder

### ISSUE THREAD

**Issue by Mikescops** [estruyf/vscode-front-matter#752]
**Describe the bug**
When using a default placeholder that is an array, the variables are not interpolated inside.

**To Reproduce**
Create a new field in your contenttype with the following:

```json
               {
                    "title": "aliases",
                    "name": "aliases",
                    "type": "list",
                    "default": [
                        "post/{{slug}}"
                    ],
                    "hidden": true
                }
```

You should get the following:

```md
---
title: test-title
slug: test-title
aliases:
  - post/{{slug}}
---
```

**Expected behavior**
The slug variable should be rendered properly.

```md
---
title: test-title
slug: test-title
aliases:
  - post/test-title
---
```

Note that using  `"default": "post/{{slug}}"` properly renders  `"default": "post/test-title"` so the problem is related to how array are managed.

**Comment by estruyf** [comment]
Thanks, @Mikescops; this is indeed not yet supported, but let us make it happen! 💪

**Comment by Mikescops** [comment]
> @Mikescops was added and is testable in the latest beta version.

sounds like it broke the normal string interpolation 😓 

<img width="287" alt="image" src="https://github.com/estruyf/vscode-front-matter/assets/4266283/f01b4c2e-b622-4585-a228-bca2739692e6">

<img width="585" alt="image" src="https://github.com/estruyf/vscode-front-matter/assets/4266283/112c5ded-d793-4d37-9534-65a54c3b7e5c">

**Comment by estruyf** [comment]
That is correct 🤦‍♂️, should be better with the new fix

**Comment by Mikescops** [comment]
Much better, thanks!

<img width="409" alt="image" src="https://github.com/estruyf/vscode-front-matter/assets/4266283/7f03bd19-22d6-450b-bde1-c50d5214208c">
