### ISSUE TITLE
Feedback: Small understanding problem with Front Matter. 

### ISSUE THREAD

**Issue by gsegit** [estruyf/vscode-front-matter#762]
Hello ;D

I have a small understanding problem with Front Matter. 

I want to create a page with Hugo, for this I create a folder Front Matter as a project folder, in it I create a subfolder called Hugosites.

Ok, now I want to create a page with Hugo called Magicplace, for this I create a folder with the name magicplace, I register it for Front Matter, so that it knows this is my folder for Hugp. Now I create an article, for this I go to Create content. Then I go to Start Server and get an error message 

Error: command error: Unable to locate config file or config directory. Maybe you need to create a new site.
Run `hugo help new` for details.

What am I doing wrong ?

Greetings

Gerriet

Translated with DeepL.com (free version)

**Comment by estruyf** [comment]
Hi @gsegit, have you checked the following documentation: https://frontmatter.codes/docs/ssg-and-frameworks/hugo-configuration - this should help you getting started with using Front Matter CMS for your Hugo site.
