### ISSUE TITLE
Issue: Dashboard tab title "data" in lowercase

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#771]
I thought I opened an issue about this a while back, but can't find it somehow, so bear with me if this is a double:

This is a tiny request, but my OCD points me at this every time I open the dashboard:

![Selection_612x100_20240313-19:44:55](https://github.com/estruyf/vscode-front-matter/assets/83281/621dea10-37eb-4d2f-b0e6-9814fce2c44a)

The "data" tab should be "Data". Or is it a philosophical decision to have only that tab lowercase?

**Comment by estruyf** [comment]
Thanks @davidsneighbour, fix is coming up in the latest beta.
