### ISSUE TITLE
Issue: Automatically adding/re-adding FM files to *all* my VS code projects whenever I open them

### ISSUE THREAD

**Issue by tohagan** [estruyf/vscode-front-matter#774]
**Describe the bug**

**To Reproduce**
1. Install Front Matter (non-beta)
2. Open any VS Code project without FM files
3. The following files get added each time I open a VSCode project  and I have to keep deleting them every time I re-open a VSCode project.

![image](https://github.com/estruyf/vscode-front-matter/assets/301525/d53fcfbc-164c-44f5-9ac6-571c9e0d9d69)

**Expected behavior**

Should only initialize an FM project when the dashboard is first opened.
Probably should ask to do so.

**Screenshots**

**Desktop (please complete the following information):**
 - Win 10

**Comment by estruyf** [comment]
That is weird, those files only get generated when the initialize command is executed.

What gets logged to the output in VSCode for Front Matter? https://frontmatter.codes/docs/troubleshooting#looking-what-is-happening-behind-the-scenes

**Comment by estruyf** [comment]
Oh, I might have an idea!

Can you verify if you have any `frontMatter.` settings in your `./.vscode/settings.json` file? Besides the initialization, there is also an option where the `frontmatter.json` file can be created. As the extension verified you are using any of the CMS settings.

**Comment by tohagan** [comment]
`settings.json` contained this setting but I don't believe I'd ever pressed the "Initialize Project" button.
Oh well at least removing this might cure it.

```json
{
  "frontMatter.content.pageFolders": []
}
```

**Comment by tohagan** [comment]
Ok I'm seeing this issue again in a different workspace with multiple subprojects.  I definitely didn't bump the Initialize button on this project. It's creating a `frontmatter.json` file. Nothing related in `./.vscode/settings.json` for either workspace or workspace projects.

**Comment by estruyf** [comment]
@tohagan that is a different kind of issue, will open a new one for it.
