### ISSUE TITLE
Feedback: Custom scripts appear only on main dashboard

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#777]
I have a bunch of custom actions [defined in a subfolder config](https://github.com/davidsneighbour/kollitsch.dev/tree/main/.frontmatter/config/custom/scripts). Recently, I'm not sure when exactly, it might have been a while, the buttons to run these scripts disappeared from the sidebar panel when I was inside my content files. I know the buttons were there. Now they are not. 

I find the actions however in the three dots menu on the main dashboard.

Did that change somehow or did another config option hide these actions? I removed `frontMatter.panel.actions.disabled` from my config to no change. 

My main config is [here](https://github.com/davidsneighbour/kollitsch.dev/blob/main/frontmatter.json) and [here](https://github.com/davidsneighbour/kollitsch.dev/tree/main/.frontmatter).

**Comment by estruyf** [comment]
Do you mean these actions?

![image](https://github.com/estruyf/vscode-front-matter/assets/2900833/cf9dbb1c-c7bd-4f33-b0a7-f509b7114695)

**Comment by estruyf** [comment]
I just verified it on Windows with both the stable and beta versions.

![image](https://github.com/estruyf/vscode-front-matter/assets/2900833/fa19bd5a-50e6-45c9-ae3d-5cc2da41fd30)

Don't spot any issues. 🤔

**Comment by estruyf** [comment]
Found it! It was only in that file. Saw that my VSCode instance gave an error on the YAML.

<img width="1320" alt="image" src="https://github.com/estruyf/vscode-front-matter/assets/2900833/ec51c72e-4045-45ee-83b8-abedd47402a6">

Updating the YAML content for **description** and **summary** to following contents fixed it:

```yaml
description: '"Flow State" by Above & Beyond is in my opinion an ideal soundtrack for enhancing concentration and workflow.'
summary: "\"Flow State\" by Above & Beyond is in my opinion an ideal soundtrack for enhancing concentration and workflow. The album's 49 minutes of ambient compositions and neo-classical soundscapes create a serene and non-intrusive background, conducive to entering a state of deep focus, often referred to as the \"flow state\" in programming and other cognitive-intensive tasks."
```

Now the panel rendered correctly.

**Comment by estruyf** [comment]
I'm going to implement a change that shows an error message like this:

![image](https://github.com/estruyf/vscode-front-matter/assets/2900833/29f2a301-ffca-4fcb-b51b-7dd9845f9aea)
