### ISSUE TITLE
Issue: A workspace folder selection shows up when no initialization is required

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#786]
Ok I'm seeing this issue again in a different workspace with multiple subprojects.  I definitely didn't bump the Initialize button on this project. It's creating a `frontmatter.json` file. Nothing related in `./.vscode/settings.json` for either workspace or workspace projects.

I just found that keying `Ctrl-S` to save a file I've just edited pops up this from FrontMatter asking me to select a workspace project instead of saving the file. So that might explain what's happening.

![image](https://github.com/estruyf/vscode-front-matter/assets/301525/1e4ee818-411b-4340-a059-03782abe8c88)

_Originally posted by @tohagan in https://github.com/estruyf/vscode-front-matter/issues/774#issuecomment-2027922254_

**Comment by estruyf** [comment]
@tohagan In the new beta (building atm), a fix prevents FM CMS from starting up when there is no `.frontmatter` or `frontmatter.json` file in your workspace. Only when you trigger one of the FM commands will it start. This should prevent it from showing the above workspace folder selection when it doesn't need to do it.

**Comment by tohagan** [comment]
Thanks very much. Will try to get some time to test the Beta this weekend.
