### ISSUE TITLE
Enhancement: False values in boolean fields shouldn't be hidden in Front Matter

### ISSUE THREAD

**Issue by marekbrze** [estruyf/vscode-front-matter#789]
**Is your feature request related to a problem? Please describe.**
I have a `draft` field in my Astro Content Collection. When setting the field to false the whole draft line is hidden from the Front Matter, but the field is required by my Content Collection.

**Describe the solution you'd like**
The best way would be to have an addition property on the boolean fields to decide if `false` values should hide the whole line from the front matter.

**Describe alternatives you've considered**
I could use choices field to have different stages of the drafts, but that's only the one use case for the setting. I have other boolean values that need to be explicitly set.

**Comment by estruyf** [comment]
Hi @marekbrze, on the content type level, you can set the `clearEmpty` to false (also the default), which should prevent clearing/hiding the line from your front matter.

https://frontmatter.codes/docs/content-creation/content-types#content-type-properties

**Comment by marekbrze** [comment]
Oh, I overlooked this setting. Works now! Thanks for the help!
