### ISSUE TITLE
Issue: the presence of a colon in a string field causes crashes 

### ISSUE THREAD

**Issue by nathanchere** [estruyf/vscode-front-matter#792]
**Describe the bug**
The presence of a colon in a non-quoted string field causes issues.

1. The syntax highlighting mistakenly captures text beyond the first colon as part of the key.
2. The FM activity tab sometimes appears as if no frontmatter schema or content is defined, and sometimes it just outright crashes.

**To Reproduce**
An example of frontmatter which breaks the  Frontmatter CMS plugin for vscode:

```
---
title: Introducing: Star Wars 13
caption: You thought they couldn't ruin Star Wars any further. You were wrong.
---
```

In this case the syntax highlighting shows "title: Introducing:" as the key instead of identifying "Introducing: " as part of the value

**Expected behavior**
Handle it without crashing. It can be worked around by putting double-quotes around the title (which is done automatically if you enter the colon in the FM activity tab instead of directly in the code editor).

**Desktop (please complete the following information):**

I've reproduced it on the following:

 - Arch Linux, vscode 1.88.0, FrontMatter CMS 10.0.2
 - Arch Linux, vscodium 1.88.0, FrontMatter CMS 10.0.2
 - Windows 10, vscode 1.88, FrontMatter CMS 10.0.2

**Comment by estruyf** [comment]
Thanks, @nathanchere, for opening the issue. The YAML parser fails to parse the front matter section and you should see the following error message:
