### ISSUE TITLE
Issue:  YAMLParseError in beta V10.1.8599652

### ISSUE THREAD

**Issue by Digital-Grinnell** [estruyf/vscode-front-matter#794]
**Describe the bug**
I was running the beta version and upon update to v10.1.8599652 I started getting "YAMLParseError" messages whenever I opened or had my scripts process any .md with a leading "---" YAML frontmatter marker.    Removing the "---" did remove the error, but naturally broke my Markdown.  

**To Reproduce**
1. Enable beta v10.1.8599652 
2. Open any .md file with YAML frontmatter and an opening '---' line
3. See the error

**Expected behavior**
A '---' opening line before the YAML frontmatter is normal and necessary.  But if I remove it the syntax error goes away, but leaves my Markdown unuseable.  Likewise, if I disable the beta version and switch to the production release (v10.0.2 in my case) the error is no longer present.

**Desktop**
 - OS: MacOS v12.7.4  or   Ubuntu 22.04 LTS
 - Browser:  Firefox

**Additional Context**
Note that I have a Python script run from a FM button and that script is also broken by this bug.  The script parses each .md file in my content folder presumably in a similar manner as the VSCode editor does.  With the beta version enabled the script no  longer works, but it also returns no errors.  After switching to the production version all is well again.

**Comment by estruyf** [comment]
Hi @Digital-Grinnell, thank you for opening the issue. Can you test out other BETA versions? The version you've mentioned only included an HTML class fix, and I can't seem to reproduce the issue. Looking for a clue why it would occur.

**Comment by estruyf** [comment]
Could you provide me with some sample content on which you have the issue?

**Comment by Digital-Grinnell** [comment]
Sure, it was happening on every piece of .md content in my site.  The last one I edited was:

---
title: The Tama Co. Rifles
date: 2024-04-10
slug: tama-rifles
dateRange: Wed.  April 10
shortTitle: Tama Co. Rifles
oneSheet: /one-sheet-images/2024.04.10-Tama-County-Rifles-Wieting.png
showType: Live Performance
runningTime: 90
mpaaRating: Not Rated
imdbURL: ""
occurrences:
  - date: 2024-04-10 19:00:00-0500
    format: Not Applicable
    fieldGroup: show_occurrence
studioInfo:
  studio: ""
  studioFee: 0
  studioPercentage: 0
draft: false
type: show
---
The Rifles were Tama County's first military company organized for the Civil War. As Company C in the 10th Iowa Infantry, the Rifles were part of some of the war's most important campaigns, from the Siege of Vicksburg to Sherman's March to the Sea. Drawing on numerous sources -- including letters and journals written by the men themselves-- we'll explore their lives, their service, and their sacrifices, as well as the families and communities they left behind.


Let me know if you need more or sent differently.

Thanks, and take care.

-Mark M.

From: Elio Struyf ***@***.***>
Date: Wednesday, April 10, 2024 at 10:22 AM
To: estruyf/vscode-front-matter ***@***.***>
Cc: Digital ***@***.***>, Mention ***@***.***>
Subject: Re: [estruyf/vscode-front-matter] Issue: YAMLParseError in beta V10.1.8599652 (Issue #794)
Caution: External Email

Could you provide me with some sample content on which you have the issue?

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_estruyf_vscode-2Dfront-2Dmatter_issues_794-23issuecomment-2D2047845035&d=DwMFaQ&c=HUrdOLg_tCr0UMeDjWLBOM9lLDRpsndbROGxEKQRFzk&r=D8E-oGNaPT9srWV6jE8UP5unsmKEmmHEH-tzgmjBvLk&m=vMn2TxvBZxDLKaDM9ypH5XSInDkPOm1KT20o3UWTX4C0EomOcDIryg6PoRJRJsDZ&s=w-leOMkL4WQ5NBjJ-NDsKPmWHf1CLJ62S3RVkt3y9rM&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADTEQ6AUUA5JLEVKDV6YPWLY4VKKJAVCNFSM6AAAAABGAUKYYGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANBXHA2DKMBTGU&d=DwMFaQ&c=HUrdOLg_tCr0UMeDjWLBOM9lLDRpsndbROGxEKQRFzk&r=D8E-oGNaPT9srWV6jE8UP5unsmKEmmHEH-tzgmjBvLk&m=vMn2TxvBZxDLKaDM9ypH5XSInDkPOm1KT20o3UWTX4C0EomOcDIryg6PoRJRJsDZ&s=mxWBU0xUl02eqMXZ-W1i01C4sMrKC_0pbj22oW2Pbb0&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>
This email was sent from outside Grinnell College. Treat attachments and links with caution. If this message looks suspicious, use the report phish button.

**Comment by davidsneighbour** [comment]
Do you maybe have the [YAML extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) installed? I am also experiencing weird YAML errors, but in other files (for instance, template files), where the YAML parser cites frontmatter issues in a content file (not the current file loaded). Going into that content file and then saving it silences the error for a bit, until it finds another content file to complain about. 

I thought this might be a YAML plugin issue, not a frontmatter issue.

Latest Beta version, also for the past two days.

**Comment by estruyf** [comment]
I found the issue. It was an experiment for #792, but as it was still in testing, I have reverted that change. The new beta should fix it.

**Comment by davidsneighbour** [comment]
> I found the issue. It was an experiment for #792, but as it was still in testing, I have reverted that change. The new beta should fix it.

My errors disappeared after this update.

**Comment by estruyf** [comment]
Thanks @davidsneighbour for verifying
