### ISSUE TITLE
Enhancement: Support Asciidoc as the content body, similar to current Markdown support.

### ISSUE THREAD

**Issue by zivbk1** [estruyf/vscode-front-matter#833]
**Is your feature request related to a problem? Please describe.**

I use structured data in frontmatter to define the page layout, but I have content 'blocks' in the design that use the 'body' content of the AsciiDoc file.  I have linked to a simple example file below showing some frontmatter and AsciiDoc content.

**Describe the solution you'd like**

Do what you do for Markdown support, but for the AsciiDoc format too.

**Describe alternatives you've considered**

I considered just using Markdown, but it supports a minimal subset of the features in AsciiDoc that I need to use for my technical documentation content.

**Additional context**

[AsciiDoc has a very similar syntax to Markdown](https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/).

You can use [asciidoctor.js](https://docs.asciidoctor.org/asciidoctor.js/latest/) for content preview.

[Example file](https://gitlab.com/tgdp/www/-/blob/main/src/content/about.adoc?ref_type=heads&plain=1) with a single design block defined in the front matter called 'content', that injects the AsciiDoc content below front matter into that part of the page.  Here is the final rendering of that page on the site. https://www.thegooddocsproject.dev/about

**Comment by estruyf** [comment]
Thanks @zivbk1 for this suggestion, I'll take a look into it.

**Comment by bwklein** [comment]
This will be helpful for at least 3 projects I am working on now that have migrated from Markdown to AsciiDoc for long-form content.

**Comment by estruyf** [comment]
I looked into it and tried to see what is possible with FM without any code change. In my test project, I used the following configuration:

```json
{
  "$schema": "https://beta.frontmatter.codes/frontmatter.schema.json",
  "frontMatter.content.supportedFileTypes": [
    "md",
    "mdx",
    "markdown",
    "adoc"
  ],
  "frontMatter.content.pageFolders": [{
    "title": "AsciiDoc",
    "path": "[[workspace]]/content/asciidoc",
    "contentTypes": ["AsciiDoc"]
  }],
  "frontMatter.taxonomy.contentTypes": [{
    "name": "AsciiDoc",
    "pageBundle": false,
    "fileType": "adoc",
    "fields": [{
        "title": "Default title",
        "name": "title",
        "type": "string"
      },
      {
        "title": "Layout",
        "name": "layout",
        "type": "string"
      },
      {
        "title": "Blocks",
        "name": "blocks",
        "type": "block",
        "fieldGroup": [
          "AsciiDoc"
        ]
      }
    ]
  }],
  "frontMatter.taxonomy.fieldGroups": [{
    "id": "AsciiDoc",
    "labelField": "title",
    "fields": [{
        "title": "Title",
        "name": "title",
        "type": "string",
        "single": true
      },
      {
        "title": "Block ref",
        "name": "block_ref",
        "type": "string",
        "single": true
      }
    ]
  }]
}
```

This allows you to change the front matter in your `adoc` file.

![image](https://github.com/user-attachments/assets/fdca7fba-727c-41f9-af32-69dca450a810)

What are exactly the improvements you are looking for that FM needs to support for AsciiDoc?

**Comment by zivbk1** [comment]
This is great! I think the only part missing now would be the WYSIWYG tools for things like headings, links, images, bold, italics, etc. that used slightly different syntax than Markdown. The hope is an equivalent editing experience, with snippets and all the other good stuff.

**Comment by estruyf** [comment]
@bwklein I have included support for Asciidocs. When you add `adoc` to the supported file types, the WYSIWYG tools become available and their markers have been updated to match the Asciidoc markup.

Give it a try in the latest beta and let me know if anything needs to be changed.

**Comment by zivbk1** [comment]
You are awesome!  I am going to try this today on a new project.

**Comment by bwklein** [comment]
Trying it out and have some feedback.

When I click the 'Other markup options' button I see a list like this.

![image](https://github.com/user-attachments/assets/16e835e0-4a26-40a3-944a-cd2b1de0d6ff)

It looks like labels and details are missing from various commands.

**Comment by bwklein** [comment]
Would be nice to have the Framework id of SvelteKit built-in.

**Comment by bwklein** [comment]
Support the following features for adoc.

- frontMatter.content.fmHighlight
- frontMatter.content.hideFm
- frontMatter.content.hideFmMessage

**Comment by estruyf** [comment]
> It looks like labels and details are missing from various commands.

Will check what is going on here. It seems the localization functionality isn't working.

**Comment by estruyf** [comment]
@bwklein the localization issue should have been fixed in the latest beta version.

**Comment by estruyf** [comment]
@zivbk1 that is using two `::` instead of one `:` ?

**Comment by zivbk1** [comment]
Yes, the second colon tells the compiler to make a 'block' instead of an 'inline' image.

**Comment by estruyf** [comment]
> Support the following features for adoc.
> 
> frontMatter.content.fmHighlight
> frontMatter.content.hideFm
> frontMatter.content.hideFmMessage

When you add `adoc` to the supported file types, it should automatically use these features.

**Comment by estruyf** [comment]
This functionality is now part of the `v10.4.0` main release.
