### ISSUE TITLE
Feedback: Zero value shouldn't be treated as empty field

### ISSUE THREAD

**Issue by ngdangtu-vn** [estruyf/vscode-front-matter#845]
![image](https://github.com/user-attachments/assets/b096201d-ae6d-4859-9cce-11f27674cefd)

When I set 0 to number field, it always treats as empty field. And if that field is required, it will reporting error. I don't think it is good design because in many cases, `0` has meaning. I suggest we should treat `0` like other digits and `null`/`undefined` as an empty field.

Info:
- framework: Astro `4.15.1`  
  ```
   experimental: {
      contentLayer: true,
      contentIntellisense: true,
   },
  ```
- os: Linux
- vscode: `1.92.2`

**Comment by estruyf** [comment]
Thanks @ngdangtu-vn for opening this issue. I have implemented a fix for this in the latest beta. Feel free to give it a try and let me know how it works.

**Comment by ngdangtu-vn** [comment]
Cool, how do I test it?

**Comment by ngdangtu-vn** [comment]
Just tested, it works beautiful. Thanks!

**Comment by estruyf** [comment]
This functionality is now part of the `v10.4.0` main release.
