### ISSUE TITLE
Issue: AI respect limits of fields when auto generate test for description, title, etc.

### ISSUE THREAD

**Issue by aavdberg** [estruyf/vscode-front-matter#847]
**Describe the bug**
When i use AI to generate a description in the meta-data is generates a very long text that is longer then allowed/recommended 

**To Reproduce**

1. Go to post
2. Click on Copilot icon at description
3. See error

**Expected behavior**
respect the field limit when generating a text with AI

**Screenshots**
![image](https://github.com/user-attachments/assets/3fd3c018-e387-4db0-9571-320b6cdd008b)

**Device:**

- OS: [e.g. iOS] Windows
- Front Matter CMS Version [e.g. 10.2.0] latest
- Browser [e.g. chrome, safari] Edge

**Additional context**

**Comment by estruyf** [comment]
The `title` and `description` fields limit can be set with the corresponding `frontMatter.taxonomy.seoTitleLength` and `frontMatter.taxonomy.seoDescriptionLength` settings.

These settings are also used for generating the tilte(s) and description.

Source: https://github.com/estruyf/vscode-front-matter/blob/d240e8fdc867589af8b4a0e2c3fe04f2d5e1ee65/src/services/Copilot.ts

AI could in some cases generate longer titles/descriptions. It is best to verify what is provided by AI.

**Comment by estruyf** [comment]
Closing the issue
