### ISSUE TITLE
Issue: Data dashboard > add new item button white on white in a dark theme

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#858]
![image](https://github.com/user-attachments/assets/bf8b48fb-6328-4158-8821-a483bdf329b8)

In the Dracula theme the button to add a new item (left side) has white writing on white background. I thought it might be an issue in the theme, but note that the buttons on the right side are black on white, so my assumption is that there is something else going on?

**Comment by estruyf** [comment]
Hi @davidsneighbour, I've changed the button to the new [vscrui](https://www.npmjs.com/package/vscrui) button component, which should fix the issue.
