### ISSUE TITLE
Enhancement: Support Markdown in the WYSIWYG field

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#866]
### Discussed in https://github.com/estruyf/vscode-front-matter/discussions/865

<div type='discussions-op-text'>

<sup>Originally posted by **MrHinsh** October  8, 2024</sup>
I use markdown in all of my `content` variables in the front matter. I really don't see why one would want HTML in there when its in a *.md file and the rest is markdown. 

How can I have a multi-line textbox but prevent any HTML from being added?</div>

---

As the WYSIWYG field option only supports HTML at the moment. An enhancement is required to support markdown.

**Comment by MrHinsh** [comment]
FYI it would be Markdown output!

**Comment by estruyf** [comment]
@MrHinsh yes, the plan is to output markdown instead of HTML.

**Comment by MrHinsh** [comment]
Just wanted to be 100% :)

**Comment by estruyf** [comment]
@MrHinsh, I've provided an option to change the behavior of the WYSIWYG field so that it can output markdown.

You can install the latest beta version (disable or uninstall the main version).

Configuration for the field looks as follows

```json
{
  "title": "Markdown",
  "name": "markdown",
  "type": "string",
  "wysiwyg": "markdown"
}
```

**Comment by MrHinsh** [comment]
Enabled and testing!

**Comment by MrHinsh** [comment]
Hey.. I dont get the button to launch from the beta?

![image](https://github.com/user-attachments/assets/9d268d6a-c472-4903-86ad-f8474db5ea43)

**Comment by MrHinsh** [comment]
Never mind... restarted VS...
