### ISSUE TITLE
Issue: Content snippets are shown as Media snippets and vice-versa in the "Snippets" tab

### ISSUE THREAD

**Issue by pottekkat** [estruyf/vscode-front-matter#876]
**Describe the bug**

Snippet with `"isMediaSnippet": true` is shown as "Content snippet" but a snippet without this value is shown as a "Media snippet" in the "Snippets" tab.

The functioning of the snippets does not seem to be affected.

**To Reproduce**

1. Create a snippet with `"isMediaSnippet": true`
2. Create a snippet without this field
3. Check the "Snippets" tab
4. You will see that the tags are inverted there

**Expected behavior**

The "Snippets" tab should show the correct type of the snippet.

**Screenshots**

**Device:**

- OS: MacOS
- Front Matter CMS Version: 10.6.114780344-beta

**Comment by estruyf** [comment]
Good catch, I have included the change in the beta.
