### ISSUE TITLE
Issue: 10.5.0 breaks autoupdating "lastmod" field; 10.5.1 did not fix it.

### ISSUE THREAD

**Issue by KOT-OPET** [estruyf/vscode-front-matter#879]
**Describe the bug**
I work with Hugo projects. My front matter is usually in YAML format. I've got used to the `lastmod` frontmatter field which updates itself while I'm writing; however, this is not the case with last two versions of FM. 

**To Reproduce**

1. Go to your .md file
2. Create empty lastmod field in the front matter
3. Type something below
4. Check the different behaviors of versions 10.4 and 10.5

**Expected behavior**
Lastmod being updated by itself.

**Device:**

- OS: Macos Sonoma
- Front Matter CMS Version 10.5.1 and 10.5.0

**Comment by estruyf** [comment]
Thanks @KOT-OPET, I'll look into it why this might happen.

**Comment by estruyf** [comment]
@KOT-OPET fix is coming up in the latest beta version
