### ISSUE TITLE
Enhancement: Descriptions for schema field definitions in data view

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#880]
**Is your feature request related to a problem? Please describe.**
I am trying to set up some data file schemas. The user is located in the non-developer group. I would like to add a description to fields, in addition to the title, so that I can describe better, what data to enter into the fields.

**Describe the solution you'd like**
```json
"schema": {
  "title": "Showcases",
  "type": "object",
  "required": [
    "title",
    "description",
    "slug"
  ],
  "properties": {
    "title": {
      "type": "string",
      "title": "Title",
      "description": "a short title of max 24 characters"
    },
    "slug": {
      "type": "string",
      "title": "Slug",
      "description": "a unique string to identify this item"
    },
    "description": {
      "type": "string",
      "multiline": true,
      "title": "Description",
      "description": "A description of this case. Markdown is allowed in this field."
    },
    "byline": {
      "type": "string",
      "multiline": true,
      "title": "Byline"
    }
  }
}
```

**Describe alternatives you've considered**
None.

**Additional context**

![image](https://github.com/user-attachments/assets/34f4e6e4-3907-4bea-bf82-cafe1f88a402)

Design-wise that description could be shown right of the title and required indicator in slightly muted color.

**Comment by estruyf** [comment]
@davidsneighbour, the description should already be shown underneath the input. This is what the dashboard looks like with your provided schema:

![image](https://github.com/user-attachments/assets/c6d94aaa-6bf9-47d2-973f-9bcce0880a45)

Which version are you using?

**Comment by davidsneighbour** [comment]
It works of course 🤣 Sorry, but somehow it didn't came to my mind to look under the field.
