### ISSUE TITLE
Issue: Content relationship field type is fetching forever

### ISSUE THREAD

**Issue by aluciu** [estruyf/vscode-front-matter#885]
**Describe the bug**
Content relationship field type is not working anymore. Is now displaying `Fetching possible values...` 
My snippet from `frontmatter.json`:
```
        {
          "title": "artists",
          "name": "artists",
          "type": "contentRelationship",
          "contentTypeName": "artists",
          "contentTypeValue": "slug",
          "multiple": true
        },
```
I don't know it matters but I have ~9000 entries.

**Screenshots**
<img width="364" alt="Screenshot 2024-11-04 at 11 31 58" src="https://github.com/user-attachments/assets/59f6fc52-95f5-4a42-a106-9afc294128b6">

**Device:**

- OS: macOS 15.1
- Front Matter CMS Version 10.5.1

**Comment by estruyf** [comment]
Thanks, @aluciu. Was it working fine in a previous version?

**Comment by aluciu** [comment]
> Thanks, @aluciu. Was it working fine in a previous version?

yes, was fine before with a previous version

**Comment by estruyf** [comment]
Thanks, @aluciu. It seems this issue was introduced in #851. I have implemented a fix. Can you verify it in the latest beta version, 10.6.116640894?

**Comment by aluciu** [comment]
yes, tested now and is working again. thank you very much!

**Comment by estruyf** [comment]
Do you test this on a project that is public or are you able to add me? That would make it easier to reproduce it on my end.

**Comment by estruyf** [comment]
@aluciu, thanks for providing the repository permissions. I have provided a fix for your configuration.

**Comment by aluciu** [comment]
thank you, for you patience! i can confirm that is working.

**Comment by estruyf** [comment]
No problem, glad we got it working again. 💪
