### ISSUE TITLE
Enhancement: Optimize the dashboard design / UX

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#94]
If you are a UX specialist or a designer and want to be part of Front Matter. It would be a great start if you could review and redesign the current dashboard contents and media views.

**Comment by lorezyra** [comment]
While you wait for a UX designer, I would suggest writing up what you expect from them. How would you expect the extension to be used and what your target users are - non-programmers or just coders?

What are the pain points (like image selection)? 
My philosophy is to never burden the user's mind more than absolutely necessary. Recognize that you want to force the user through the absolute minimum number of steps to achieve their desired action.

Remember that biology plays a role in software design. This is especially true in UX.
- The brain:
  - 1st processes color
  - then comes shapes
  - then text.
  - and sometime later: comprehension of the text
- fingers / hand:
  - for mobile, where are the thumbs/fingers able to reach without losing grip on the device?
  - How far does the user need to scroll?
  - How many clicks required to complete an action?
- UX: 
  - Does the user need to read the docs before using it? Or is it easy enough for my grandmother (or 5-year old kids) to navigate?
  - Is the contrast sufficient for reading/viewing the site?
  - Does the visual profile/animation add to instructing the user on operation? (Think about how the most popular games are designed. Users typically don't read a manual before jumping into the game.)
  - For me, this is most important... Does it save my time?

**Comment by estruyf** [comment]
Closing this issue for now. Suggestions can be made in a new separate issue.
