### ISSUE TITLE
Enhancement: SEO and content optimization for the frontmatter.codes website

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#95]
Being a contributor for Front Matter is not all about writing code for the extension. You can also contribute to better SEO and/or content for the [frontmatter.codes](https://frontmatter.codes) website.

If you are interested or spotted something that can be better, let us know.

**Comment by flikteoh** [comment]
- On mobile, the side navigation on the documentation page is missing.
- More to be updated.

Do I need to create a new issue or how do we go about helping?

**Comment by estruyf** [comment]
You can create a new issue for this.

If you are willing to pick up the task, you can find the project here: https://github.com/FrontMatter/web-documentation-nextjs 

I already moved this to its own organization.

**Comment by estruyf** [comment]
No worries! All help is welcome and appreciated 🙏

**Comment by sureshkumargondi** [comment]
Hey @estruyf  Do you still need help in the SEO thing for the site? I can contribute :)

**Comment by estruyf** [comment]
@sureshkumargondi think that this is something that will never really be resolved. If you see things that can be optimized, feel free to contribute and I'll be more than happy to accept the PR.

The documentation repository can be found here: https://github.com/FrontMatter/web-documentation-nextjs
