### ISSUE TITLE
Issue: Error message when creating new content

### ISSUE THREAD

**Issue by thomasvochten** [estruyf/vscode-front-matter#96]
**Describe the bug**
Clicking the "Create content" button results in the "Front Matter: You didn't select a place where you wanted to create your content" error message, although frontMatter.content.folders have been specified in the .vscode/settings.json file. I'm using WSL (Ubuntu).

**To Reproduce**
1. Go to the FrontMatter Dashboard
2. Click on "Create content"
3. Error message appears

**Expected behavior**
Content will be created in the location specified.

**Screenshots**
![image](https://user-images.githubusercontent.com/135686/132696584-958a3051-2bd4-4e9d-a344-008e6dec2c51.png)
![image](https://user-images.githubusercontent.com/135686/132696539-c5f8c0a6-fc12-45e3-ad97-ffb735920911.png)

**Desktop**
 - OS: Windows 11 & WSL (Ubuntu)

**Comment by estruyf** [comment]
Thank you, @thomasvochten, for opening an issue. WSL can indeed cause some confusion in the extension, as it comes with Windows and Linux paths.

In the upcoming version, the folder setting has been changed to a simpler path. Would you like to give `Front Matter BETA` a try? That will include the new setting, and it will automatically update it.

**Comment by estruyf** [comment]
Oh, be aware, you can only have one version installed. So you will need to uninstall `Front Matter`, otherwise, the BETA will not enable itself. Nothing will be gone, as all settings are kept in the settings.json file.

**Comment by estruyf** [comment]
Tested on my WSL environment, and with the BETA, this is not happening. Hopefully you have the same experience.

**Comment by estruyf** [comment]
@thomasvochten does this problem still occur?

**Comment by thomasvochten** [comment]
Yes! Works just fine now - thanks for the follow-up
