### ISSUE TITLE
Showcase: 

### ISSUE THREAD

**Issue by Fasani** [estruyf/vscode-front-matter#99]
MichaelFasani.com

Personal blog of Michael Fasani, content stored as markdown in GitHub, built with Gatsby, managed with Front Matter.

https://www.michaelfasani.com

**Comment by estruyf** [comment]
Thanks @Fasani, you're now included on the showcase page in https://beta.frontmatter.codes - soon also on the main one.

**Comment by estruyf** [comment]
And now on main as well.

**Comment by Fasani** [comment]
That's great! Looking forward to the next release. Thanks!
